# This is the configuration file for mockery, a tool for generating Go mocks.
all: true
dir: mocks/{{.InterfaceDirRelative}}
log-level: Warn
filename: "mock_{{.InterfaceName}}.go"
template: testify
template-data:
  unroll-variadic: True
force-file-write: True
packages:
  gitlab.com/arielsrv/go-restclient/rest:
    config:
      recursive: true
