sonar.projectKey=arielsrv_go-restclient
sonar.organization=arielsrv
sonar.projectName=go-restclient
sonar.projectVersion=1.0

# Source code
sonar.sources=.
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.exclusions=**/mocks/**,**/examples/**,**/*_test.go,**/vendor/**,**/docs/**
sonar.coverage.exclusions=**/mocks/**,**/examples/**,**/*_test.go,**/doc.go,**/mockup.go,**/mockup_test.go,**/mockup_timeout_test.go

# Encoding
sonar.sourceEncoding=UTF-8

# Go specific
sonar.go.coverage.reportPaths=coverage.out

