// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package rest

import (
	"context"
	"net/http"

	mock "github.com/stretchr/testify/mock"
	"gitlab.com/iskaypetcom/digital/sre/tools/dev/go-restclient/rest"
)

// NewMockHTTPClient creates a new instance of MockHTTPClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHTTPClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHTTPClient {
	mock := &MockHTTPClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHTTPClient is an autogenerated mock type for the HTTPClient type
type MockHTTPClient struct {
	mock.Mock
}

type MockHTTPClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHTTPClient) EXPECT() *MockHTTPClient_Expecter {
	return &MockHTTPClient_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockHTTPClient
func (_mock *MockHTTPClient) Delete(url string, headers ...http.Header) *rest.Response {
	// http.Header
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, url)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 *rest.Response
	if returnFunc, ok := ret.Get(0).(func(string, ...http.Header) *rest.Response); ok {
		r0 = returnFunc(url, headers...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rest.Response)
		}
	}
	return r0
}

// MockHTTPClient_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockHTTPClient_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - url string
//   - headers ...http.Header
func (_e *MockHTTPClient_Expecter) Delete(url interface{}, headers ...interface{}) *MockHTTPClient_Delete_Call {
	return &MockHTTPClient_Delete_Call{Call: _e.mock.On("Delete",
		append([]interface{}{url}, headers...)...)}
}

func (_c *MockHTTPClient_Delete_Call) Run(run func(url string, headers ...http.Header)) *MockHTTPClient_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []http.Header
		variadicArgs := make([]http.Header, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockHTTPClient_Delete_Call) Return(response *rest.Response) *MockHTTPClient_Delete_Call {
	_c.Call.Return(response)
	return _c
}

func (_c *MockHTTPClient_Delete_Call) RunAndReturn(run func(url string, headers ...http.Header) *rest.Response) *MockHTTPClient_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteWithContext provides a mock function for the type MockHTTPClient
func (_mock *MockHTTPClient) DeleteWithContext(ctx context.Context, url string, headers ...http.Header) *rest.Response {
	// http.Header
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, url)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for DeleteWithContext")
	}

	var r0 *rest.Response
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...http.Header) *rest.Response); ok {
		r0 = returnFunc(ctx, url, headers...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rest.Response)
		}
	}
	return r0
}

// MockHTTPClient_DeleteWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteWithContext'
type MockHTTPClient_DeleteWithContext_Call struct {
	*mock.Call
}

// DeleteWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - headers ...http.Header
func (_e *MockHTTPClient_Expecter) DeleteWithContext(ctx interface{}, url interface{}, headers ...interface{}) *MockHTTPClient_DeleteWithContext_Call {
	return &MockHTTPClient_DeleteWithContext_Call{Call: _e.mock.On("DeleteWithContext",
		append([]interface{}{ctx, url}, headers...)...)}
}

func (_c *MockHTTPClient_DeleteWithContext_Call) Run(run func(ctx context.Context, url string, headers ...http.Header)) *MockHTTPClient_DeleteWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []http.Header
		variadicArgs := make([]http.Header, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockHTTPClient_DeleteWithContext_Call) Return(response *rest.Response) *MockHTTPClient_DeleteWithContext_Call {
	_c.Call.Return(response)
	return _c
}

func (_c *MockHTTPClient_DeleteWithContext_Call) RunAndReturn(run func(ctx context.Context, url string, headers ...http.Header) *rest.Response) *MockHTTPClient_DeleteWithContext_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockHTTPClient
func (_mock *MockHTTPClient) Get(url string, headers ...http.Header) *rest.Response {
	// http.Header
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, url)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *rest.Response
	if returnFunc, ok := ret.Get(0).(func(string, ...http.Header) *rest.Response); ok {
		r0 = returnFunc(url, headers...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rest.Response)
		}
	}
	return r0
}

// MockHTTPClient_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockHTTPClient_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - url string
//   - headers ...http.Header
func (_e *MockHTTPClient_Expecter) Get(url interface{}, headers ...interface{}) *MockHTTPClient_Get_Call {
	return &MockHTTPClient_Get_Call{Call: _e.mock.On("Get",
		append([]interface{}{url}, headers...)...)}
}

func (_c *MockHTTPClient_Get_Call) Run(run func(url string, headers ...http.Header)) *MockHTTPClient_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []http.Header
		variadicArgs := make([]http.Header, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockHTTPClient_Get_Call) Return(response *rest.Response) *MockHTTPClient_Get_Call {
	_c.Call.Return(response)
	return _c
}

func (_c *MockHTTPClient_Get_Call) RunAndReturn(run func(url string, headers ...http.Header) *rest.Response) *MockHTTPClient_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetWithContext provides a mock function for the type MockHTTPClient
func (_mock *MockHTTPClient) GetWithContext(ctx context.Context, url string, headers ...http.Header) *rest.Response {
	// http.Header
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, url)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetWithContext")
	}

	var r0 *rest.Response
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...http.Header) *rest.Response); ok {
		r0 = returnFunc(ctx, url, headers...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rest.Response)
		}
	}
	return r0
}

// MockHTTPClient_GetWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWithContext'
type MockHTTPClient_GetWithContext_Call struct {
	*mock.Call
}

// GetWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - headers ...http.Header
func (_e *MockHTTPClient_Expecter) GetWithContext(ctx interface{}, url interface{}, headers ...interface{}) *MockHTTPClient_GetWithContext_Call {
	return &MockHTTPClient_GetWithContext_Call{Call: _e.mock.On("GetWithContext",
		append([]interface{}{ctx, url}, headers...)...)}
}

func (_c *MockHTTPClient_GetWithContext_Call) Run(run func(ctx context.Context, url string, headers ...http.Header)) *MockHTTPClient_GetWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []http.Header
		variadicArgs := make([]http.Header, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockHTTPClient_GetWithContext_Call) Return(response *rest.Response) *MockHTTPClient_GetWithContext_Call {
	_c.Call.Return(response)
	return _c
}

func (_c *MockHTTPClient_GetWithContext_Call) RunAndReturn(run func(ctx context.Context, url string, headers ...http.Header) *rest.Response) *MockHTTPClient_GetWithContext_Call {
	_c.Call.Return(run)
	return _c
}

// Head provides a mock function for the type MockHTTPClient
func (_mock *MockHTTPClient) Head(url string, headers ...http.Header) *rest.Response {
	// http.Header
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, url)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Head")
	}

	var r0 *rest.Response
	if returnFunc, ok := ret.Get(0).(func(string, ...http.Header) *rest.Response); ok {
		r0 = returnFunc(url, headers...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rest.Response)
		}
	}
	return r0
}

// MockHTTPClient_Head_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Head'
type MockHTTPClient_Head_Call struct {
	*mock.Call
}

// Head is a helper method to define mock.On call
//   - url string
//   - headers ...http.Header
func (_e *MockHTTPClient_Expecter) Head(url interface{}, headers ...interface{}) *MockHTTPClient_Head_Call {
	return &MockHTTPClient_Head_Call{Call: _e.mock.On("Head",
		append([]interface{}{url}, headers...)...)}
}

func (_c *MockHTTPClient_Head_Call) Run(run func(url string, headers ...http.Header)) *MockHTTPClient_Head_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []http.Header
		variadicArgs := make([]http.Header, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockHTTPClient_Head_Call) Return(response *rest.Response) *MockHTTPClient_Head_Call {
	_c.Call.Return(response)
	return _c
}

func (_c *MockHTTPClient_Head_Call) RunAndReturn(run func(url string, headers ...http.Header) *rest.Response) *MockHTTPClient_Head_Call {
	_c.Call.Return(run)
	return _c
}

// HeadWithContext provides a mock function for the type MockHTTPClient
func (_mock *MockHTTPClient) HeadWithContext(ctx context.Context, url string, headers ...http.Header) *rest.Response {
	// http.Header
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, url)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for HeadWithContext")
	}

	var r0 *rest.Response
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...http.Header) *rest.Response); ok {
		r0 = returnFunc(ctx, url, headers...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rest.Response)
		}
	}
	return r0
}

// MockHTTPClient_HeadWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HeadWithContext'
type MockHTTPClient_HeadWithContext_Call struct {
	*mock.Call
}

// HeadWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - headers ...http.Header
func (_e *MockHTTPClient_Expecter) HeadWithContext(ctx interface{}, url interface{}, headers ...interface{}) *MockHTTPClient_HeadWithContext_Call {
	return &MockHTTPClient_HeadWithContext_Call{Call: _e.mock.On("HeadWithContext",
		append([]interface{}{ctx, url}, headers...)...)}
}

func (_c *MockHTTPClient_HeadWithContext_Call) Run(run func(ctx context.Context, url string, headers ...http.Header)) *MockHTTPClient_HeadWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []http.Header
		variadicArgs := make([]http.Header, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockHTTPClient_HeadWithContext_Call) Return(response *rest.Response) *MockHTTPClient_HeadWithContext_Call {
	_c.Call.Return(response)
	return _c
}

func (_c *MockHTTPClient_HeadWithContext_Call) RunAndReturn(run func(ctx context.Context, url string, headers ...http.Header) *rest.Response) *MockHTTPClient_HeadWithContext_Call {
	_c.Call.Return(run)
	return _c
}

// Options provides a mock function for the type MockHTTPClient
func (_mock *MockHTTPClient) Options(url string, headers ...http.Header) *rest.Response {
	// http.Header
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, url)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Options")
	}

	var r0 *rest.Response
	if returnFunc, ok := ret.Get(0).(func(string, ...http.Header) *rest.Response); ok {
		r0 = returnFunc(url, headers...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rest.Response)
		}
	}
	return r0
}

// MockHTTPClient_Options_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Options'
type MockHTTPClient_Options_Call struct {
	*mock.Call
}

// Options is a helper method to define mock.On call
//   - url string
//   - headers ...http.Header
func (_e *MockHTTPClient_Expecter) Options(url interface{}, headers ...interface{}) *MockHTTPClient_Options_Call {
	return &MockHTTPClient_Options_Call{Call: _e.mock.On("Options",
		append([]interface{}{url}, headers...)...)}
}

func (_c *MockHTTPClient_Options_Call) Run(run func(url string, headers ...http.Header)) *MockHTTPClient_Options_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []http.Header
		variadicArgs := make([]http.Header, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockHTTPClient_Options_Call) Return(response *rest.Response) *MockHTTPClient_Options_Call {
	_c.Call.Return(response)
	return _c
}

func (_c *MockHTTPClient_Options_Call) RunAndReturn(run func(url string, headers ...http.Header) *rest.Response) *MockHTTPClient_Options_Call {
	_c.Call.Return(run)
	return _c
}

// OptionsWithContext provides a mock function for the type MockHTTPClient
func (_mock *MockHTTPClient) OptionsWithContext(ctx context.Context, url string, headers ...http.Header) *rest.Response {
	// http.Header
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, url)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for OptionsWithContext")
	}

	var r0 *rest.Response
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...http.Header) *rest.Response); ok {
		r0 = returnFunc(ctx, url, headers...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rest.Response)
		}
	}
	return r0
}

// MockHTTPClient_OptionsWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OptionsWithContext'
type MockHTTPClient_OptionsWithContext_Call struct {
	*mock.Call
}

// OptionsWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - headers ...http.Header
func (_e *MockHTTPClient_Expecter) OptionsWithContext(ctx interface{}, url interface{}, headers ...interface{}) *MockHTTPClient_OptionsWithContext_Call {
	return &MockHTTPClient_OptionsWithContext_Call{Call: _e.mock.On("OptionsWithContext",
		append([]interface{}{ctx, url}, headers...)...)}
}

func (_c *MockHTTPClient_OptionsWithContext_Call) Run(run func(ctx context.Context, url string, headers ...http.Header)) *MockHTTPClient_OptionsWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []http.Header
		variadicArgs := make([]http.Header, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockHTTPClient_OptionsWithContext_Call) Return(response *rest.Response) *MockHTTPClient_OptionsWithContext_Call {
	_c.Call.Return(response)
	return _c
}

func (_c *MockHTTPClient_OptionsWithContext_Call) RunAndReturn(run func(ctx context.Context, url string, headers ...http.Header) *rest.Response) *MockHTTPClient_OptionsWithContext_Call {
	_c.Call.Return(run)
	return _c
}

// Patch provides a mock function for the type MockHTTPClient
func (_mock *MockHTTPClient) Patch(url string, body any, headers ...http.Header) *rest.Response {
	// http.Header
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, url, body)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Patch")
	}

	var r0 *rest.Response
	if returnFunc, ok := ret.Get(0).(func(string, any, ...http.Header) *rest.Response); ok {
		r0 = returnFunc(url, body, headers...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rest.Response)
		}
	}
	return r0
}

// MockHTTPClient_Patch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Patch'
type MockHTTPClient_Patch_Call struct {
	*mock.Call
}

// Patch is a helper method to define mock.On call
//   - url string
//   - body any
//   - headers ...http.Header
func (_e *MockHTTPClient_Expecter) Patch(url interface{}, body interface{}, headers ...interface{}) *MockHTTPClient_Patch_Call {
	return &MockHTTPClient_Patch_Call{Call: _e.mock.On("Patch",
		append([]interface{}{url, body}, headers...)...)}
}

func (_c *MockHTTPClient_Patch_Call) Run(run func(url string, body any, headers ...http.Header)) *MockHTTPClient_Patch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 any
		if args[1] != nil {
			arg1 = args[1].(any)
		}
		var arg2 []http.Header
		variadicArgs := make([]http.Header, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockHTTPClient_Patch_Call) Return(response *rest.Response) *MockHTTPClient_Patch_Call {
	_c.Call.Return(response)
	return _c
}

func (_c *MockHTTPClient_Patch_Call) RunAndReturn(run func(url string, body any, headers ...http.Header) *rest.Response) *MockHTTPClient_Patch_Call {
	_c.Call.Return(run)
	return _c
}

// PatchWithContext provides a mock function for the type MockHTTPClient
func (_mock *MockHTTPClient) PatchWithContext(ctx context.Context, url string, body any, headers ...http.Header) *rest.Response {
	// http.Header
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, url, body)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for PatchWithContext")
	}

	var r0 *rest.Response
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, any, ...http.Header) *rest.Response); ok {
		r0 = returnFunc(ctx, url, body, headers...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rest.Response)
		}
	}
	return r0
}

// MockHTTPClient_PatchWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PatchWithContext'
type MockHTTPClient_PatchWithContext_Call struct {
	*mock.Call
}

// PatchWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - body any
//   - headers ...http.Header
func (_e *MockHTTPClient_Expecter) PatchWithContext(ctx interface{}, url interface{}, body interface{}, headers ...interface{}) *MockHTTPClient_PatchWithContext_Call {
	return &MockHTTPClient_PatchWithContext_Call{Call: _e.mock.On("PatchWithContext",
		append([]interface{}{ctx, url, body}, headers...)...)}
}

func (_c *MockHTTPClient_PatchWithContext_Call) Run(run func(ctx context.Context, url string, body any, headers ...http.Header)) *MockHTTPClient_PatchWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		var arg3 []http.Header
		variadicArgs := make([]http.Header, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockHTTPClient_PatchWithContext_Call) Return(response *rest.Response) *MockHTTPClient_PatchWithContext_Call {
	_c.Call.Return(response)
	return _c
}

func (_c *MockHTTPClient_PatchWithContext_Call) RunAndReturn(run func(ctx context.Context, url string, body any, headers ...http.Header) *rest.Response) *MockHTTPClient_PatchWithContext_Call {
	_c.Call.Return(run)
	return _c
}

// Post provides a mock function for the type MockHTTPClient
func (_mock *MockHTTPClient) Post(url string, body any, headers ...http.Header) *rest.Response {
	// http.Header
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, url, body)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Post")
	}

	var r0 *rest.Response
	if returnFunc, ok := ret.Get(0).(func(string, any, ...http.Header) *rest.Response); ok {
		r0 = returnFunc(url, body, headers...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rest.Response)
		}
	}
	return r0
}

// MockHTTPClient_Post_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Post'
type MockHTTPClient_Post_Call struct {
	*mock.Call
}

// Post is a helper method to define mock.On call
//   - url string
//   - body any
//   - headers ...http.Header
func (_e *MockHTTPClient_Expecter) Post(url interface{}, body interface{}, headers ...interface{}) *MockHTTPClient_Post_Call {
	return &MockHTTPClient_Post_Call{Call: _e.mock.On("Post",
		append([]interface{}{url, body}, headers...)...)}
}

func (_c *MockHTTPClient_Post_Call) Run(run func(url string, body any, headers ...http.Header)) *MockHTTPClient_Post_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 any
		if args[1] != nil {
			arg1 = args[1].(any)
		}
		var arg2 []http.Header
		variadicArgs := make([]http.Header, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockHTTPClient_Post_Call) Return(response *rest.Response) *MockHTTPClient_Post_Call {
	_c.Call.Return(response)
	return _c
}

func (_c *MockHTTPClient_Post_Call) RunAndReturn(run func(url string, body any, headers ...http.Header) *rest.Response) *MockHTTPClient_Post_Call {
	_c.Call.Return(run)
	return _c
}

// PostWithContext provides a mock function for the type MockHTTPClient
func (_mock *MockHTTPClient) PostWithContext(ctx context.Context, url string, body any, headers ...http.Header) *rest.Response {
	// http.Header
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, url, body)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for PostWithContext")
	}

	var r0 *rest.Response
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, any, ...http.Header) *rest.Response); ok {
		r0 = returnFunc(ctx, url, body, headers...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rest.Response)
		}
	}
	return r0
}

// MockHTTPClient_PostWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostWithContext'
type MockHTTPClient_PostWithContext_Call struct {
	*mock.Call
}

// PostWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - body any
//   - headers ...http.Header
func (_e *MockHTTPClient_Expecter) PostWithContext(ctx interface{}, url interface{}, body interface{}, headers ...interface{}) *MockHTTPClient_PostWithContext_Call {
	return &MockHTTPClient_PostWithContext_Call{Call: _e.mock.On("PostWithContext",
		append([]interface{}{ctx, url, body}, headers...)...)}
}

func (_c *MockHTTPClient_PostWithContext_Call) Run(run func(ctx context.Context, url string, body any, headers ...http.Header)) *MockHTTPClient_PostWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		var arg3 []http.Header
		variadicArgs := make([]http.Header, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockHTTPClient_PostWithContext_Call) Return(response *rest.Response) *MockHTTPClient_PostWithContext_Call {
	_c.Call.Return(response)
	return _c
}

func (_c *MockHTTPClient_PostWithContext_Call) RunAndReturn(run func(ctx context.Context, url string, body any, headers ...http.Header) *rest.Response) *MockHTTPClient_PostWithContext_Call {
	_c.Call.Return(run)
	return _c
}

// Put provides a mock function for the type MockHTTPClient
func (_mock *MockHTTPClient) Put(url string, body any, headers ...http.Header) *rest.Response {
	// http.Header
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, url, body)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Put")
	}

	var r0 *rest.Response
	if returnFunc, ok := ret.Get(0).(func(string, any, ...http.Header) *rest.Response); ok {
		r0 = returnFunc(url, body, headers...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rest.Response)
		}
	}
	return r0
}

// MockHTTPClient_Put_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Put'
type MockHTTPClient_Put_Call struct {
	*mock.Call
}

// Put is a helper method to define mock.On call
//   - url string
//   - body any
//   - headers ...http.Header
func (_e *MockHTTPClient_Expecter) Put(url interface{}, body interface{}, headers ...interface{}) *MockHTTPClient_Put_Call {
	return &MockHTTPClient_Put_Call{Call: _e.mock.On("Put",
		append([]interface{}{url, body}, headers...)...)}
}

func (_c *MockHTTPClient_Put_Call) Run(run func(url string, body any, headers ...http.Header)) *MockHTTPClient_Put_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 any
		if args[1] != nil {
			arg1 = args[1].(any)
		}
		var arg2 []http.Header
		variadicArgs := make([]http.Header, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockHTTPClient_Put_Call) Return(response *rest.Response) *MockHTTPClient_Put_Call {
	_c.Call.Return(response)
	return _c
}

func (_c *MockHTTPClient_Put_Call) RunAndReturn(run func(url string, body any, headers ...http.Header) *rest.Response) *MockHTTPClient_Put_Call {
	_c.Call.Return(run)
	return _c
}

// PutWithContext provides a mock function for the type MockHTTPClient
func (_mock *MockHTTPClient) PutWithContext(ctx context.Context, url string, body any, headers ...http.Header) *rest.Response {
	// http.Header
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, url, body)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for PutWithContext")
	}

	var r0 *rest.Response
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, any, ...http.Header) *rest.Response); ok {
		r0 = returnFunc(ctx, url, body, headers...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rest.Response)
		}
	}
	return r0
}

// MockHTTPClient_PutWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutWithContext'
type MockHTTPClient_PutWithContext_Call struct {
	*mock.Call
}

// PutWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - body any
//   - headers ...http.Header
func (_e *MockHTTPClient_Expecter) PutWithContext(ctx interface{}, url interface{}, body interface{}, headers ...interface{}) *MockHTTPClient_PutWithContext_Call {
	return &MockHTTPClient_PutWithContext_Call{Call: _e.mock.On("PutWithContext",
		append([]interface{}{ctx, url, body}, headers...)...)}
}

func (_c *MockHTTPClient_PutWithContext_Call) Run(run func(ctx context.Context, url string, body any, headers ...http.Header)) *MockHTTPClient_PutWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		var arg3 []http.Header
		variadicArgs := make([]http.Header, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockHTTPClient_PutWithContext_Call) Return(response *rest.Response) *MockHTTPClient_PutWithContext_Call {
	_c.Call.Return(response)
	return _c
}

func (_c *MockHTTPClient_PutWithContext_Call) RunAndReturn(run func(ctx context.Context, url string, body any, headers ...http.Header) *rest.Response) *MockHTTPClient_PutWithContext_Call {
	_c.Call.Return(run)
	return _c
}
