// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	http "net/http"

	mock "github.com/stretchr/testify/mock"

	rest "gitlab.com/iskaypetcom/digital/sre/tools/dev/go-restclient/rest"
)

// MockIRequestBuilder is an autogenerated mock type for the IRequestBuilder type
type MockIRequestBuilder struct {
	mock.Mock
}

type MockIRequestBuilder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIRequestBuilder) EXPECT() *MockIRequestBuilder_Expecter {
	return &MockIRequestBuilder_Expecter{mock: &_m.Mock}
}

// AsyncDelete provides a mock function with given fields: url, f, headers
func (_m *MockIRequestBuilder) AsyncDelete(url string, f func(*rest.Response), headers ...http.Header) {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, url, f)
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// MockIRequestBuilder_AsyncDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AsyncDelete'
type MockIRequestBuilder_AsyncDelete_Call struct {
	*mock.Call
}

// AsyncDelete is a helper method to define mock.On call
//   - url string
//   - f func(*rest.Response)
//   - headers ...http.Header
func (_e *MockIRequestBuilder_Expecter) AsyncDelete(url interface{}, f interface{}, headers ...interface{}) *MockIRequestBuilder_AsyncDelete_Call {
	return &MockIRequestBuilder_AsyncDelete_Call{Call: _e.mock.On("AsyncDelete",
		append([]interface{}{url, f}, headers...)...)}
}

func (_c *MockIRequestBuilder_AsyncDelete_Call) Run(run func(url string, f func(*rest.Response), headers ...http.Header)) *MockIRequestBuilder_AsyncDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(string), args[1].(func(*rest.Response)), variadicArgs...)
	})
	return _c
}

func (_c *MockIRequestBuilder_AsyncDelete_Call) Return() *MockIRequestBuilder_AsyncDelete_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIRequestBuilder_AsyncDelete_Call) RunAndReturn(run func(string, func(*rest.Response), ...http.Header)) *MockIRequestBuilder_AsyncDelete_Call {
	_c.Call.Return(run)
	return _c
}

// AsyncDeleteWithContext provides a mock function with given fields: ctx, url, f, headers
func (_m *MockIRequestBuilder) AsyncDeleteWithContext(ctx context.Context, url string, f func(*rest.Response), headers ...http.Header) {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, url, f)
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// MockIRequestBuilder_AsyncDeleteWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AsyncDeleteWithContext'
type MockIRequestBuilder_AsyncDeleteWithContext_Call struct {
	*mock.Call
}

// AsyncDeleteWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - f func(*rest.Response)
//   - headers ...http.Header
func (_e *MockIRequestBuilder_Expecter) AsyncDeleteWithContext(ctx interface{}, url interface{}, f interface{}, headers ...interface{}) *MockIRequestBuilder_AsyncDeleteWithContext_Call {
	return &MockIRequestBuilder_AsyncDeleteWithContext_Call{Call: _e.mock.On("AsyncDeleteWithContext",
		append([]interface{}{ctx, url, f}, headers...)...)}
}

func (_c *MockIRequestBuilder_AsyncDeleteWithContext_Call) Run(run func(ctx context.Context, url string, f func(*rest.Response), headers ...http.Header)) *MockIRequestBuilder_AsyncDeleteWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(func(*rest.Response)), variadicArgs...)
	})
	return _c
}

func (_c *MockIRequestBuilder_AsyncDeleteWithContext_Call) Return() *MockIRequestBuilder_AsyncDeleteWithContext_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIRequestBuilder_AsyncDeleteWithContext_Call) RunAndReturn(run func(context.Context, string, func(*rest.Response), ...http.Header)) *MockIRequestBuilder_AsyncDeleteWithContext_Call {
	_c.Call.Return(run)
	return _c
}

// AsyncGet provides a mock function with given fields: url, f, headers
func (_m *MockIRequestBuilder) AsyncGet(url string, f func(*rest.Response), headers ...http.Header) {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, url, f)
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// MockIRequestBuilder_AsyncGet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AsyncGet'
type MockIRequestBuilder_AsyncGet_Call struct {
	*mock.Call
}

// AsyncGet is a helper method to define mock.On call
//   - url string
//   - f func(*rest.Response)
//   - headers ...http.Header
func (_e *MockIRequestBuilder_Expecter) AsyncGet(url interface{}, f interface{}, headers ...interface{}) *MockIRequestBuilder_AsyncGet_Call {
	return &MockIRequestBuilder_AsyncGet_Call{Call: _e.mock.On("AsyncGet",
		append([]interface{}{url, f}, headers...)...)}
}

func (_c *MockIRequestBuilder_AsyncGet_Call) Run(run func(url string, f func(*rest.Response), headers ...http.Header)) *MockIRequestBuilder_AsyncGet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(string), args[1].(func(*rest.Response)), variadicArgs...)
	})
	return _c
}

func (_c *MockIRequestBuilder_AsyncGet_Call) Return() *MockIRequestBuilder_AsyncGet_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIRequestBuilder_AsyncGet_Call) RunAndReturn(run func(string, func(*rest.Response), ...http.Header)) *MockIRequestBuilder_AsyncGet_Call {
	_c.Call.Return(run)
	return _c
}

// AsyncGetWithContext provides a mock function with given fields: ctx, url, f, headers
func (_m *MockIRequestBuilder) AsyncGetWithContext(ctx context.Context, url string, f func(*rest.Response), headers ...http.Header) {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, url, f)
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// MockIRequestBuilder_AsyncGetWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AsyncGetWithContext'
type MockIRequestBuilder_AsyncGetWithContext_Call struct {
	*mock.Call
}

// AsyncGetWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - f func(*rest.Response)
//   - headers ...http.Header
func (_e *MockIRequestBuilder_Expecter) AsyncGetWithContext(ctx interface{}, url interface{}, f interface{}, headers ...interface{}) *MockIRequestBuilder_AsyncGetWithContext_Call {
	return &MockIRequestBuilder_AsyncGetWithContext_Call{Call: _e.mock.On("AsyncGetWithContext",
		append([]interface{}{ctx, url, f}, headers...)...)}
}

func (_c *MockIRequestBuilder_AsyncGetWithContext_Call) Run(run func(ctx context.Context, url string, f func(*rest.Response), headers ...http.Header)) *MockIRequestBuilder_AsyncGetWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(func(*rest.Response)), variadicArgs...)
	})
	return _c
}

func (_c *MockIRequestBuilder_AsyncGetWithContext_Call) Return() *MockIRequestBuilder_AsyncGetWithContext_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIRequestBuilder_AsyncGetWithContext_Call) RunAndReturn(run func(context.Context, string, func(*rest.Response), ...http.Header)) *MockIRequestBuilder_AsyncGetWithContext_Call {
	_c.Call.Return(run)
	return _c
}

// AsyncHead provides a mock function with given fields: url, f, headers
func (_m *MockIRequestBuilder) AsyncHead(url string, f func(*rest.Response), headers ...http.Header) {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, url, f)
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// MockIRequestBuilder_AsyncHead_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AsyncHead'
type MockIRequestBuilder_AsyncHead_Call struct {
	*mock.Call
}

// AsyncHead is a helper method to define mock.On call
//   - url string
//   - f func(*rest.Response)
//   - headers ...http.Header
func (_e *MockIRequestBuilder_Expecter) AsyncHead(url interface{}, f interface{}, headers ...interface{}) *MockIRequestBuilder_AsyncHead_Call {
	return &MockIRequestBuilder_AsyncHead_Call{Call: _e.mock.On("AsyncHead",
		append([]interface{}{url, f}, headers...)...)}
}

func (_c *MockIRequestBuilder_AsyncHead_Call) Run(run func(url string, f func(*rest.Response), headers ...http.Header)) *MockIRequestBuilder_AsyncHead_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(string), args[1].(func(*rest.Response)), variadicArgs...)
	})
	return _c
}

func (_c *MockIRequestBuilder_AsyncHead_Call) Return() *MockIRequestBuilder_AsyncHead_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIRequestBuilder_AsyncHead_Call) RunAndReturn(run func(string, func(*rest.Response), ...http.Header)) *MockIRequestBuilder_AsyncHead_Call {
	_c.Call.Return(run)
	return _c
}

// AsyncHeadWithContext provides a mock function with given fields: ctx, url, f, headers
func (_m *MockIRequestBuilder) AsyncHeadWithContext(ctx context.Context, url string, f func(*rest.Response), headers ...http.Header) {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, url, f)
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// MockIRequestBuilder_AsyncHeadWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AsyncHeadWithContext'
type MockIRequestBuilder_AsyncHeadWithContext_Call struct {
	*mock.Call
}

// AsyncHeadWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - f func(*rest.Response)
//   - headers ...http.Header
func (_e *MockIRequestBuilder_Expecter) AsyncHeadWithContext(ctx interface{}, url interface{}, f interface{}, headers ...interface{}) *MockIRequestBuilder_AsyncHeadWithContext_Call {
	return &MockIRequestBuilder_AsyncHeadWithContext_Call{Call: _e.mock.On("AsyncHeadWithContext",
		append([]interface{}{ctx, url, f}, headers...)...)}
}

func (_c *MockIRequestBuilder_AsyncHeadWithContext_Call) Run(run func(ctx context.Context, url string, f func(*rest.Response), headers ...http.Header)) *MockIRequestBuilder_AsyncHeadWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(func(*rest.Response)), variadicArgs...)
	})
	return _c
}

func (_c *MockIRequestBuilder_AsyncHeadWithContext_Call) Return() *MockIRequestBuilder_AsyncHeadWithContext_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIRequestBuilder_AsyncHeadWithContext_Call) RunAndReturn(run func(context.Context, string, func(*rest.Response), ...http.Header)) *MockIRequestBuilder_AsyncHeadWithContext_Call {
	_c.Call.Return(run)
	return _c
}

// AsyncOptions provides a mock function with given fields: url, f, headers
func (_m *MockIRequestBuilder) AsyncOptions(url string, f func(*rest.Response), headers ...http.Header) {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, url, f)
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// MockIRequestBuilder_AsyncOptions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AsyncOptions'
type MockIRequestBuilder_AsyncOptions_Call struct {
	*mock.Call
}

// AsyncOptions is a helper method to define mock.On call
//   - url string
//   - f func(*rest.Response)
//   - headers ...http.Header
func (_e *MockIRequestBuilder_Expecter) AsyncOptions(url interface{}, f interface{}, headers ...interface{}) *MockIRequestBuilder_AsyncOptions_Call {
	return &MockIRequestBuilder_AsyncOptions_Call{Call: _e.mock.On("AsyncOptions",
		append([]interface{}{url, f}, headers...)...)}
}

func (_c *MockIRequestBuilder_AsyncOptions_Call) Run(run func(url string, f func(*rest.Response), headers ...http.Header)) *MockIRequestBuilder_AsyncOptions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(string), args[1].(func(*rest.Response)), variadicArgs...)
	})
	return _c
}

func (_c *MockIRequestBuilder_AsyncOptions_Call) Return() *MockIRequestBuilder_AsyncOptions_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIRequestBuilder_AsyncOptions_Call) RunAndReturn(run func(string, func(*rest.Response), ...http.Header)) *MockIRequestBuilder_AsyncOptions_Call {
	_c.Call.Return(run)
	return _c
}

// AsyncOptionsWithContext provides a mock function with given fields: ctx, url, f, headers
func (_m *MockIRequestBuilder) AsyncOptionsWithContext(ctx context.Context, url string, f func(*rest.Response), headers ...http.Header) {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, url, f)
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// MockIRequestBuilder_AsyncOptionsWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AsyncOptionsWithContext'
type MockIRequestBuilder_AsyncOptionsWithContext_Call struct {
	*mock.Call
}

// AsyncOptionsWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - f func(*rest.Response)
//   - headers ...http.Header
func (_e *MockIRequestBuilder_Expecter) AsyncOptionsWithContext(ctx interface{}, url interface{}, f interface{}, headers ...interface{}) *MockIRequestBuilder_AsyncOptionsWithContext_Call {
	return &MockIRequestBuilder_AsyncOptionsWithContext_Call{Call: _e.mock.On("AsyncOptionsWithContext",
		append([]interface{}{ctx, url, f}, headers...)...)}
}

func (_c *MockIRequestBuilder_AsyncOptionsWithContext_Call) Run(run func(ctx context.Context, url string, f func(*rest.Response), headers ...http.Header)) *MockIRequestBuilder_AsyncOptionsWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(func(*rest.Response)), variadicArgs...)
	})
	return _c
}

func (_c *MockIRequestBuilder_AsyncOptionsWithContext_Call) Return() *MockIRequestBuilder_AsyncOptionsWithContext_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIRequestBuilder_AsyncOptionsWithContext_Call) RunAndReturn(run func(context.Context, string, func(*rest.Response), ...http.Header)) *MockIRequestBuilder_AsyncOptionsWithContext_Call {
	_c.Call.Return(run)
	return _c
}

// AsyncPatch provides a mock function with given fields: url, body, f, headers
func (_m *MockIRequestBuilder) AsyncPatch(url string, body any, f func(*rest.Response), headers ...http.Header) {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, url, body, f)
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// MockIRequestBuilder_AsyncPatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AsyncPatch'
type MockIRequestBuilder_AsyncPatch_Call struct {
	*mock.Call
}

// AsyncPatch is a helper method to define mock.On call
//   - url string
//   - body any
//   - f func(*rest.Response)
//   - headers ...http.Header
func (_e *MockIRequestBuilder_Expecter) AsyncPatch(url interface{}, body interface{}, f interface{}, headers ...interface{}) *MockIRequestBuilder_AsyncPatch_Call {
	return &MockIRequestBuilder_AsyncPatch_Call{Call: _e.mock.On("AsyncPatch",
		append([]interface{}{url, body, f}, headers...)...)}
}

func (_c *MockIRequestBuilder_AsyncPatch_Call) Run(run func(url string, body any, f func(*rest.Response), headers ...http.Header)) *MockIRequestBuilder_AsyncPatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(string), args[1].(any), args[2].(func(*rest.Response)), variadicArgs...)
	})
	return _c
}

func (_c *MockIRequestBuilder_AsyncPatch_Call) Return() *MockIRequestBuilder_AsyncPatch_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIRequestBuilder_AsyncPatch_Call) RunAndReturn(run func(string, any, func(*rest.Response), ...http.Header)) *MockIRequestBuilder_AsyncPatch_Call {
	_c.Call.Return(run)
	return _c
}

// AsyncPatchWithContext provides a mock function with given fields: ctx, url, body, f, headers
func (_m *MockIRequestBuilder) AsyncPatchWithContext(ctx context.Context, url string, body any, f func(*rest.Response), headers ...http.Header) {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, url, body, f)
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// MockIRequestBuilder_AsyncPatchWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AsyncPatchWithContext'
type MockIRequestBuilder_AsyncPatchWithContext_Call struct {
	*mock.Call
}

// AsyncPatchWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - body any
//   - f func(*rest.Response)
//   - headers ...http.Header
func (_e *MockIRequestBuilder_Expecter) AsyncPatchWithContext(ctx interface{}, url interface{}, body interface{}, f interface{}, headers ...interface{}) *MockIRequestBuilder_AsyncPatchWithContext_Call {
	return &MockIRequestBuilder_AsyncPatchWithContext_Call{Call: _e.mock.On("AsyncPatchWithContext",
		append([]interface{}{ctx, url, body, f}, headers...)...)}
}

func (_c *MockIRequestBuilder_AsyncPatchWithContext_Call) Run(run func(ctx context.Context, url string, body any, f func(*rest.Response), headers ...http.Header)) *MockIRequestBuilder_AsyncPatchWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-4)
		for i, a := range args[4:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(any), args[3].(func(*rest.Response)), variadicArgs...)
	})
	return _c
}

func (_c *MockIRequestBuilder_AsyncPatchWithContext_Call) Return() *MockIRequestBuilder_AsyncPatchWithContext_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIRequestBuilder_AsyncPatchWithContext_Call) RunAndReturn(run func(context.Context, string, any, func(*rest.Response), ...http.Header)) *MockIRequestBuilder_AsyncPatchWithContext_Call {
	_c.Call.Return(run)
	return _c
}

// AsyncPost provides a mock function with given fields: url, body, f, headers
func (_m *MockIRequestBuilder) AsyncPost(url string, body any, f func(*rest.Response), headers ...http.Header) {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, url, body, f)
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// MockIRequestBuilder_AsyncPost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AsyncPost'
type MockIRequestBuilder_AsyncPost_Call struct {
	*mock.Call
}

// AsyncPost is a helper method to define mock.On call
//   - url string
//   - body any
//   - f func(*rest.Response)
//   - headers ...http.Header
func (_e *MockIRequestBuilder_Expecter) AsyncPost(url interface{}, body interface{}, f interface{}, headers ...interface{}) *MockIRequestBuilder_AsyncPost_Call {
	return &MockIRequestBuilder_AsyncPost_Call{Call: _e.mock.On("AsyncPost",
		append([]interface{}{url, body, f}, headers...)...)}
}

func (_c *MockIRequestBuilder_AsyncPost_Call) Run(run func(url string, body any, f func(*rest.Response), headers ...http.Header)) *MockIRequestBuilder_AsyncPost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(string), args[1].(any), args[2].(func(*rest.Response)), variadicArgs...)
	})
	return _c
}

func (_c *MockIRequestBuilder_AsyncPost_Call) Return() *MockIRequestBuilder_AsyncPost_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIRequestBuilder_AsyncPost_Call) RunAndReturn(run func(string, any, func(*rest.Response), ...http.Header)) *MockIRequestBuilder_AsyncPost_Call {
	_c.Call.Return(run)
	return _c
}

// AsyncPostWithContext provides a mock function with given fields: ctx, url, body, f, headers
func (_m *MockIRequestBuilder) AsyncPostWithContext(ctx context.Context, url string, body any, f func(*rest.Response), headers ...http.Header) {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, url, body, f)
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// MockIRequestBuilder_AsyncPostWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AsyncPostWithContext'
type MockIRequestBuilder_AsyncPostWithContext_Call struct {
	*mock.Call
}

// AsyncPostWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - body any
//   - f func(*rest.Response)
//   - headers ...http.Header
func (_e *MockIRequestBuilder_Expecter) AsyncPostWithContext(ctx interface{}, url interface{}, body interface{}, f interface{}, headers ...interface{}) *MockIRequestBuilder_AsyncPostWithContext_Call {
	return &MockIRequestBuilder_AsyncPostWithContext_Call{Call: _e.mock.On("AsyncPostWithContext",
		append([]interface{}{ctx, url, body, f}, headers...)...)}
}

func (_c *MockIRequestBuilder_AsyncPostWithContext_Call) Run(run func(ctx context.Context, url string, body any, f func(*rest.Response), headers ...http.Header)) *MockIRequestBuilder_AsyncPostWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-4)
		for i, a := range args[4:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(any), args[3].(func(*rest.Response)), variadicArgs...)
	})
	return _c
}

func (_c *MockIRequestBuilder_AsyncPostWithContext_Call) Return() *MockIRequestBuilder_AsyncPostWithContext_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIRequestBuilder_AsyncPostWithContext_Call) RunAndReturn(run func(context.Context, string, any, func(*rest.Response), ...http.Header)) *MockIRequestBuilder_AsyncPostWithContext_Call {
	_c.Call.Return(run)
	return _c
}

// AsyncPut provides a mock function with given fields: url, body, f, headers
func (_m *MockIRequestBuilder) AsyncPut(url string, body any, f func(*rest.Response), headers ...http.Header) {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, url, body, f)
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// MockIRequestBuilder_AsyncPut_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AsyncPut'
type MockIRequestBuilder_AsyncPut_Call struct {
	*mock.Call
}

// AsyncPut is a helper method to define mock.On call
//   - url string
//   - body any
//   - f func(*rest.Response)
//   - headers ...http.Header
func (_e *MockIRequestBuilder_Expecter) AsyncPut(url interface{}, body interface{}, f interface{}, headers ...interface{}) *MockIRequestBuilder_AsyncPut_Call {
	return &MockIRequestBuilder_AsyncPut_Call{Call: _e.mock.On("AsyncPut",
		append([]interface{}{url, body, f}, headers...)...)}
}

func (_c *MockIRequestBuilder_AsyncPut_Call) Run(run func(url string, body any, f func(*rest.Response), headers ...http.Header)) *MockIRequestBuilder_AsyncPut_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(string), args[1].(any), args[2].(func(*rest.Response)), variadicArgs...)
	})
	return _c
}

func (_c *MockIRequestBuilder_AsyncPut_Call) Return() *MockIRequestBuilder_AsyncPut_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIRequestBuilder_AsyncPut_Call) RunAndReturn(run func(string, any, func(*rest.Response), ...http.Header)) *MockIRequestBuilder_AsyncPut_Call {
	_c.Call.Return(run)
	return _c
}

// AsyncPutWithContext provides a mock function with given fields: ctx, url, body, f, headers
func (_m *MockIRequestBuilder) AsyncPutWithContext(ctx context.Context, url string, body any, f func(*rest.Response), headers ...http.Header) {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, url, body, f)
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// MockIRequestBuilder_AsyncPutWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AsyncPutWithContext'
type MockIRequestBuilder_AsyncPutWithContext_Call struct {
	*mock.Call
}

// AsyncPutWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - body any
//   - f func(*rest.Response)
//   - headers ...http.Header
func (_e *MockIRequestBuilder_Expecter) AsyncPutWithContext(ctx interface{}, url interface{}, body interface{}, f interface{}, headers ...interface{}) *MockIRequestBuilder_AsyncPutWithContext_Call {
	return &MockIRequestBuilder_AsyncPutWithContext_Call{Call: _e.mock.On("AsyncPutWithContext",
		append([]interface{}{ctx, url, body, f}, headers...)...)}
}

func (_c *MockIRequestBuilder_AsyncPutWithContext_Call) Run(run func(ctx context.Context, url string, body any, f func(*rest.Response), headers ...http.Header)) *MockIRequestBuilder_AsyncPutWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-4)
		for i, a := range args[4:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(any), args[3].(func(*rest.Response)), variadicArgs...)
	})
	return _c
}

func (_c *MockIRequestBuilder_AsyncPutWithContext_Call) Return() *MockIRequestBuilder_AsyncPutWithContext_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIRequestBuilder_AsyncPutWithContext_Call) RunAndReturn(run func(context.Context, string, any, func(*rest.Response), ...http.Header)) *MockIRequestBuilder_AsyncPutWithContext_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: url, headers
func (_m *MockIRequestBuilder) Delete(url string, headers ...http.Header) *rest.Response {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, url)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 *rest.Response
	if rf, ok := ret.Get(0).(func(string, ...http.Header) *rest.Response); ok {
		r0 = rf(url, headers...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rest.Response)
		}
	}

	return r0
}

// MockIRequestBuilder_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockIRequestBuilder_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - url string
//   - headers ...http.Header
func (_e *MockIRequestBuilder_Expecter) Delete(url interface{}, headers ...interface{}) *MockIRequestBuilder_Delete_Call {
	return &MockIRequestBuilder_Delete_Call{Call: _e.mock.On("Delete",
		append([]interface{}{url}, headers...)...)}
}

func (_c *MockIRequestBuilder_Delete_Call) Run(run func(url string, headers ...http.Header)) *MockIRequestBuilder_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockIRequestBuilder_Delete_Call) Return(_a0 *rest.Response) *MockIRequestBuilder_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIRequestBuilder_Delete_Call) RunAndReturn(run func(string, ...http.Header) *rest.Response) *MockIRequestBuilder_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteWithContext provides a mock function with given fields: ctx, url, headers
func (_m *MockIRequestBuilder) DeleteWithContext(ctx context.Context, url string, headers ...http.Header) *rest.Response {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, url)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for DeleteWithContext")
	}

	var r0 *rest.Response
	if rf, ok := ret.Get(0).(func(context.Context, string, ...http.Header) *rest.Response); ok {
		r0 = rf(ctx, url, headers...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rest.Response)
		}
	}

	return r0
}

// MockIRequestBuilder_DeleteWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteWithContext'
type MockIRequestBuilder_DeleteWithContext_Call struct {
	*mock.Call
}

// DeleteWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - headers ...http.Header
func (_e *MockIRequestBuilder_Expecter) DeleteWithContext(ctx interface{}, url interface{}, headers ...interface{}) *MockIRequestBuilder_DeleteWithContext_Call {
	return &MockIRequestBuilder_DeleteWithContext_Call{Call: _e.mock.On("DeleteWithContext",
		append([]interface{}{ctx, url}, headers...)...)}
}

func (_c *MockIRequestBuilder_DeleteWithContext_Call) Run(run func(ctx context.Context, url string, headers ...http.Header)) *MockIRequestBuilder_DeleteWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockIRequestBuilder_DeleteWithContext_Call) Return(_a0 *rest.Response) *MockIRequestBuilder_DeleteWithContext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIRequestBuilder_DeleteWithContext_Call) RunAndReturn(run func(context.Context, string, ...http.Header) *rest.Response) *MockIRequestBuilder_DeleteWithContext_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: url, headers
func (_m *MockIRequestBuilder) Get(url string, headers ...http.Header) *rest.Response {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, url)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *rest.Response
	if rf, ok := ret.Get(0).(func(string, ...http.Header) *rest.Response); ok {
		r0 = rf(url, headers...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rest.Response)
		}
	}

	return r0
}

// MockIRequestBuilder_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockIRequestBuilder_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - url string
//   - headers ...http.Header
func (_e *MockIRequestBuilder_Expecter) Get(url interface{}, headers ...interface{}) *MockIRequestBuilder_Get_Call {
	return &MockIRequestBuilder_Get_Call{Call: _e.mock.On("Get",
		append([]interface{}{url}, headers...)...)}
}

func (_c *MockIRequestBuilder_Get_Call) Run(run func(url string, headers ...http.Header)) *MockIRequestBuilder_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockIRequestBuilder_Get_Call) Return(_a0 *rest.Response) *MockIRequestBuilder_Get_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIRequestBuilder_Get_Call) RunAndReturn(run func(string, ...http.Header) *rest.Response) *MockIRequestBuilder_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetWithContext provides a mock function with given fields: ctx, url, headers
func (_m *MockIRequestBuilder) GetWithContext(ctx context.Context, url string, headers ...http.Header) *rest.Response {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, url)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetWithContext")
	}

	var r0 *rest.Response
	if rf, ok := ret.Get(0).(func(context.Context, string, ...http.Header) *rest.Response); ok {
		r0 = rf(ctx, url, headers...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rest.Response)
		}
	}

	return r0
}

// MockIRequestBuilder_GetWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWithContext'
type MockIRequestBuilder_GetWithContext_Call struct {
	*mock.Call
}

// GetWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - headers ...http.Header
func (_e *MockIRequestBuilder_Expecter) GetWithContext(ctx interface{}, url interface{}, headers ...interface{}) *MockIRequestBuilder_GetWithContext_Call {
	return &MockIRequestBuilder_GetWithContext_Call{Call: _e.mock.On("GetWithContext",
		append([]interface{}{ctx, url}, headers...)...)}
}

func (_c *MockIRequestBuilder_GetWithContext_Call) Run(run func(ctx context.Context, url string, headers ...http.Header)) *MockIRequestBuilder_GetWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockIRequestBuilder_GetWithContext_Call) Return(_a0 *rest.Response) *MockIRequestBuilder_GetWithContext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIRequestBuilder_GetWithContext_Call) RunAndReturn(run func(context.Context, string, ...http.Header) *rest.Response) *MockIRequestBuilder_GetWithContext_Call {
	_c.Call.Return(run)
	return _c
}

// Head provides a mock function with given fields: url, headers
func (_m *MockIRequestBuilder) Head(url string, headers ...http.Header) *rest.Response {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, url)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Head")
	}

	var r0 *rest.Response
	if rf, ok := ret.Get(0).(func(string, ...http.Header) *rest.Response); ok {
		r0 = rf(url, headers...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rest.Response)
		}
	}

	return r0
}

// MockIRequestBuilder_Head_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Head'
type MockIRequestBuilder_Head_Call struct {
	*mock.Call
}

// Head is a helper method to define mock.On call
//   - url string
//   - headers ...http.Header
func (_e *MockIRequestBuilder_Expecter) Head(url interface{}, headers ...interface{}) *MockIRequestBuilder_Head_Call {
	return &MockIRequestBuilder_Head_Call{Call: _e.mock.On("Head",
		append([]interface{}{url}, headers...)...)}
}

func (_c *MockIRequestBuilder_Head_Call) Run(run func(url string, headers ...http.Header)) *MockIRequestBuilder_Head_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockIRequestBuilder_Head_Call) Return(_a0 *rest.Response) *MockIRequestBuilder_Head_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIRequestBuilder_Head_Call) RunAndReturn(run func(string, ...http.Header) *rest.Response) *MockIRequestBuilder_Head_Call {
	_c.Call.Return(run)
	return _c
}

// HeadWithContext provides a mock function with given fields: ctx, url, headers
func (_m *MockIRequestBuilder) HeadWithContext(ctx context.Context, url string, headers ...http.Header) *rest.Response {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, url)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for HeadWithContext")
	}

	var r0 *rest.Response
	if rf, ok := ret.Get(0).(func(context.Context, string, ...http.Header) *rest.Response); ok {
		r0 = rf(ctx, url, headers...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rest.Response)
		}
	}

	return r0
}

// MockIRequestBuilder_HeadWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HeadWithContext'
type MockIRequestBuilder_HeadWithContext_Call struct {
	*mock.Call
}

// HeadWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - headers ...http.Header
func (_e *MockIRequestBuilder_Expecter) HeadWithContext(ctx interface{}, url interface{}, headers ...interface{}) *MockIRequestBuilder_HeadWithContext_Call {
	return &MockIRequestBuilder_HeadWithContext_Call{Call: _e.mock.On("HeadWithContext",
		append([]interface{}{ctx, url}, headers...)...)}
}

func (_c *MockIRequestBuilder_HeadWithContext_Call) Run(run func(ctx context.Context, url string, headers ...http.Header)) *MockIRequestBuilder_HeadWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockIRequestBuilder_HeadWithContext_Call) Return(_a0 *rest.Response) *MockIRequestBuilder_HeadWithContext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIRequestBuilder_HeadWithContext_Call) RunAndReturn(run func(context.Context, string, ...http.Header) *rest.Response) *MockIRequestBuilder_HeadWithContext_Call {
	_c.Call.Return(run)
	return _c
}

// Options provides a mock function with given fields: url, headers
func (_m *MockIRequestBuilder) Options(url string, headers ...http.Header) *rest.Response {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, url)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Options")
	}

	var r0 *rest.Response
	if rf, ok := ret.Get(0).(func(string, ...http.Header) *rest.Response); ok {
		r0 = rf(url, headers...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rest.Response)
		}
	}

	return r0
}

// MockIRequestBuilder_Options_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Options'
type MockIRequestBuilder_Options_Call struct {
	*mock.Call
}

// Options is a helper method to define mock.On call
//   - url string
//   - headers ...http.Header
func (_e *MockIRequestBuilder_Expecter) Options(url interface{}, headers ...interface{}) *MockIRequestBuilder_Options_Call {
	return &MockIRequestBuilder_Options_Call{Call: _e.mock.On("Options",
		append([]interface{}{url}, headers...)...)}
}

func (_c *MockIRequestBuilder_Options_Call) Run(run func(url string, headers ...http.Header)) *MockIRequestBuilder_Options_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockIRequestBuilder_Options_Call) Return(_a0 *rest.Response) *MockIRequestBuilder_Options_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIRequestBuilder_Options_Call) RunAndReturn(run func(string, ...http.Header) *rest.Response) *MockIRequestBuilder_Options_Call {
	_c.Call.Return(run)
	return _c
}

// OptionsWithContext provides a mock function with given fields: ctx, url, headers
func (_m *MockIRequestBuilder) OptionsWithContext(ctx context.Context, url string, headers ...http.Header) *rest.Response {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, url)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for OptionsWithContext")
	}

	var r0 *rest.Response
	if rf, ok := ret.Get(0).(func(context.Context, string, ...http.Header) *rest.Response); ok {
		r0 = rf(ctx, url, headers...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rest.Response)
		}
	}

	return r0
}

// MockIRequestBuilder_OptionsWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OptionsWithContext'
type MockIRequestBuilder_OptionsWithContext_Call struct {
	*mock.Call
}

// OptionsWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - headers ...http.Header
func (_e *MockIRequestBuilder_Expecter) OptionsWithContext(ctx interface{}, url interface{}, headers ...interface{}) *MockIRequestBuilder_OptionsWithContext_Call {
	return &MockIRequestBuilder_OptionsWithContext_Call{Call: _e.mock.On("OptionsWithContext",
		append([]interface{}{ctx, url}, headers...)...)}
}

func (_c *MockIRequestBuilder_OptionsWithContext_Call) Run(run func(ctx context.Context, url string, headers ...http.Header)) *MockIRequestBuilder_OptionsWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockIRequestBuilder_OptionsWithContext_Call) Return(_a0 *rest.Response) *MockIRequestBuilder_OptionsWithContext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIRequestBuilder_OptionsWithContext_Call) RunAndReturn(run func(context.Context, string, ...http.Header) *rest.Response) *MockIRequestBuilder_OptionsWithContext_Call {
	_c.Call.Return(run)
	return _c
}

// Patch provides a mock function with given fields: url, body, headers
func (_m *MockIRequestBuilder) Patch(url string, body any, headers ...http.Header) *rest.Response {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, url, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Patch")
	}

	var r0 *rest.Response
	if rf, ok := ret.Get(0).(func(string, any, ...http.Header) *rest.Response); ok {
		r0 = rf(url, body, headers...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rest.Response)
		}
	}

	return r0
}

// MockIRequestBuilder_Patch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Patch'
type MockIRequestBuilder_Patch_Call struct {
	*mock.Call
}

// Patch is a helper method to define mock.On call
//   - url string
//   - body any
//   - headers ...http.Header
func (_e *MockIRequestBuilder_Expecter) Patch(url interface{}, body interface{}, headers ...interface{}) *MockIRequestBuilder_Patch_Call {
	return &MockIRequestBuilder_Patch_Call{Call: _e.mock.On("Patch",
		append([]interface{}{url, body}, headers...)...)}
}

func (_c *MockIRequestBuilder_Patch_Call) Run(run func(url string, body any, headers ...http.Header)) *MockIRequestBuilder_Patch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(string), args[1].(any), variadicArgs...)
	})
	return _c
}

func (_c *MockIRequestBuilder_Patch_Call) Return(_a0 *rest.Response) *MockIRequestBuilder_Patch_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIRequestBuilder_Patch_Call) RunAndReturn(run func(string, any, ...http.Header) *rest.Response) *MockIRequestBuilder_Patch_Call {
	_c.Call.Return(run)
	return _c
}

// PatchWithContext provides a mock function with given fields: ctx, url, body, headers
func (_m *MockIRequestBuilder) PatchWithContext(ctx context.Context, url string, body any, headers ...http.Header) *rest.Response {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, url, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for PatchWithContext")
	}

	var r0 *rest.Response
	if rf, ok := ret.Get(0).(func(context.Context, string, any, ...http.Header) *rest.Response); ok {
		r0 = rf(ctx, url, body, headers...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rest.Response)
		}
	}

	return r0
}

// MockIRequestBuilder_PatchWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PatchWithContext'
type MockIRequestBuilder_PatchWithContext_Call struct {
	*mock.Call
}

// PatchWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - body any
//   - headers ...http.Header
func (_e *MockIRequestBuilder_Expecter) PatchWithContext(ctx interface{}, url interface{}, body interface{}, headers ...interface{}) *MockIRequestBuilder_PatchWithContext_Call {
	return &MockIRequestBuilder_PatchWithContext_Call{Call: _e.mock.On("PatchWithContext",
		append([]interface{}{ctx, url, body}, headers...)...)}
}

func (_c *MockIRequestBuilder_PatchWithContext_Call) Run(run func(ctx context.Context, url string, body any, headers ...http.Header)) *MockIRequestBuilder_PatchWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(any), variadicArgs...)
	})
	return _c
}

func (_c *MockIRequestBuilder_PatchWithContext_Call) Return(_a0 *rest.Response) *MockIRequestBuilder_PatchWithContext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIRequestBuilder_PatchWithContext_Call) RunAndReturn(run func(context.Context, string, any, ...http.Header) *rest.Response) *MockIRequestBuilder_PatchWithContext_Call {
	_c.Call.Return(run)
	return _c
}

// Post provides a mock function with given fields: url, body, headers
func (_m *MockIRequestBuilder) Post(url string, body any, headers ...http.Header) *rest.Response {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, url, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Post")
	}

	var r0 *rest.Response
	if rf, ok := ret.Get(0).(func(string, any, ...http.Header) *rest.Response); ok {
		r0 = rf(url, body, headers...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rest.Response)
		}
	}

	return r0
}

// MockIRequestBuilder_Post_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Post'
type MockIRequestBuilder_Post_Call struct {
	*mock.Call
}

// Post is a helper method to define mock.On call
//   - url string
//   - body any
//   - headers ...http.Header
func (_e *MockIRequestBuilder_Expecter) Post(url interface{}, body interface{}, headers ...interface{}) *MockIRequestBuilder_Post_Call {
	return &MockIRequestBuilder_Post_Call{Call: _e.mock.On("Post",
		append([]interface{}{url, body}, headers...)...)}
}

func (_c *MockIRequestBuilder_Post_Call) Run(run func(url string, body any, headers ...http.Header)) *MockIRequestBuilder_Post_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(string), args[1].(any), variadicArgs...)
	})
	return _c
}

func (_c *MockIRequestBuilder_Post_Call) Return(_a0 *rest.Response) *MockIRequestBuilder_Post_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIRequestBuilder_Post_Call) RunAndReturn(run func(string, any, ...http.Header) *rest.Response) *MockIRequestBuilder_Post_Call {
	_c.Call.Return(run)
	return _c
}

// PostWithContext provides a mock function with given fields: ctx, url, body, headers
func (_m *MockIRequestBuilder) PostWithContext(ctx context.Context, url string, body any, headers ...http.Header) *rest.Response {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, url, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for PostWithContext")
	}

	var r0 *rest.Response
	if rf, ok := ret.Get(0).(func(context.Context, string, any, ...http.Header) *rest.Response); ok {
		r0 = rf(ctx, url, body, headers...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rest.Response)
		}
	}

	return r0
}

// MockIRequestBuilder_PostWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostWithContext'
type MockIRequestBuilder_PostWithContext_Call struct {
	*mock.Call
}

// PostWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - body any
//   - headers ...http.Header
func (_e *MockIRequestBuilder_Expecter) PostWithContext(ctx interface{}, url interface{}, body interface{}, headers ...interface{}) *MockIRequestBuilder_PostWithContext_Call {
	return &MockIRequestBuilder_PostWithContext_Call{Call: _e.mock.On("PostWithContext",
		append([]interface{}{ctx, url, body}, headers...)...)}
}

func (_c *MockIRequestBuilder_PostWithContext_Call) Run(run func(ctx context.Context, url string, body any, headers ...http.Header)) *MockIRequestBuilder_PostWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(any), variadicArgs...)
	})
	return _c
}

func (_c *MockIRequestBuilder_PostWithContext_Call) Return(_a0 *rest.Response) *MockIRequestBuilder_PostWithContext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIRequestBuilder_PostWithContext_Call) RunAndReturn(run func(context.Context, string, any, ...http.Header) *rest.Response) *MockIRequestBuilder_PostWithContext_Call {
	_c.Call.Return(run)
	return _c
}

// Put provides a mock function with given fields: url, body, headers
func (_m *MockIRequestBuilder) Put(url string, body any, headers ...http.Header) *rest.Response {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, url, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Put")
	}

	var r0 *rest.Response
	if rf, ok := ret.Get(0).(func(string, any, ...http.Header) *rest.Response); ok {
		r0 = rf(url, body, headers...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rest.Response)
		}
	}

	return r0
}

// MockIRequestBuilder_Put_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Put'
type MockIRequestBuilder_Put_Call struct {
	*mock.Call
}

// Put is a helper method to define mock.On call
//   - url string
//   - body any
//   - headers ...http.Header
func (_e *MockIRequestBuilder_Expecter) Put(url interface{}, body interface{}, headers ...interface{}) *MockIRequestBuilder_Put_Call {
	return &MockIRequestBuilder_Put_Call{Call: _e.mock.On("Put",
		append([]interface{}{url, body}, headers...)...)}
}

func (_c *MockIRequestBuilder_Put_Call) Run(run func(url string, body any, headers ...http.Header)) *MockIRequestBuilder_Put_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(string), args[1].(any), variadicArgs...)
	})
	return _c
}

func (_c *MockIRequestBuilder_Put_Call) Return(_a0 *rest.Response) *MockIRequestBuilder_Put_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIRequestBuilder_Put_Call) RunAndReturn(run func(string, any, ...http.Header) *rest.Response) *MockIRequestBuilder_Put_Call {
	_c.Call.Return(run)
	return _c
}

// PutWithContext provides a mock function with given fields: ctx, url, body, headers
func (_m *MockIRequestBuilder) PutWithContext(ctx context.Context, url string, body any, headers ...http.Header) *rest.Response {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, url, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for PutWithContext")
	}

	var r0 *rest.Response
	if rf, ok := ret.Get(0).(func(context.Context, string, any, ...http.Header) *rest.Response); ok {
		r0 = rf(ctx, url, body, headers...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rest.Response)
		}
	}

	return r0
}

// MockIRequestBuilder_PutWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutWithContext'
type MockIRequestBuilder_PutWithContext_Call struct {
	*mock.Call
}

// PutWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - body any
//   - headers ...http.Header
func (_e *MockIRequestBuilder_Expecter) PutWithContext(ctx interface{}, url interface{}, body interface{}, headers ...interface{}) *MockIRequestBuilder_PutWithContext_Call {
	return &MockIRequestBuilder_PutWithContext_Call{Call: _e.mock.On("PutWithContext",
		append([]interface{}{ctx, url, body}, headers...)...)}
}

func (_c *MockIRequestBuilder_PutWithContext_Call) Run(run func(ctx context.Context, url string, body any, headers ...http.Header)) *MockIRequestBuilder_PutWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(any), variadicArgs...)
	})
	return _c
}

func (_c *MockIRequestBuilder_PutWithContext_Call) Return(_a0 *rest.Response) *MockIRequestBuilder_PutWithContext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIRequestBuilder_PutWithContext_Call) RunAndReturn(run func(context.Context, string, any, ...http.Header) *rest.Response) *MockIRequestBuilder_PutWithContext_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIRequestBuilder creates a new instance of MockIRequestBuilder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIRequestBuilder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIRequestBuilder {
	mock := &MockIRequestBuilder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
