// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	http "net/http"

	mock "github.com/stretchr/testify/mock"

	rest "gitlab.com/iskaypetcom/digital/sre/tools/dev/go-restclient/rest"
)

// MockSyncHTTPClient is an autogenerated mock type for the SyncHTTPClient type
type MockSyncHTTPClient struct {
	mock.Mock
}

type MockSyncHTTPClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSyncHTTPClient) EXPECT() *MockSyncHTTPClient_Expecter {
	return &MockSyncHTTPClient_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: url, headers
func (_m *MockSyncHTTPClient) Delete(url string, headers ...http.Header) *rest.Response {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, url)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 *rest.Response
	if rf, ok := ret.Get(0).(func(string, ...http.Header) *rest.Response); ok {
		r0 = rf(url, headers...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rest.Response)
		}
	}

	return r0
}

// MockSyncHTTPClient_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockSyncHTTPClient_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - url string
//   - headers ...http.Header
func (_e *MockSyncHTTPClient_Expecter) Delete(url interface{}, headers ...interface{}) *MockSyncHTTPClient_Delete_Call {
	return &MockSyncHTTPClient_Delete_Call{Call: _e.mock.On("Delete",
		append([]interface{}{url}, headers...)...)}
}

func (_c *MockSyncHTTPClient_Delete_Call) Run(run func(url string, headers ...http.Header)) *MockSyncHTTPClient_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockSyncHTTPClient_Delete_Call) Return(_a0 *rest.Response) *MockSyncHTTPClient_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSyncHTTPClient_Delete_Call) RunAndReturn(run func(string, ...http.Header) *rest.Response) *MockSyncHTTPClient_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteWithContext provides a mock function with given fields: ctx, url, headers
func (_m *MockSyncHTTPClient) DeleteWithContext(ctx context.Context, url string, headers ...http.Header) *rest.Response {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, url)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for DeleteWithContext")
	}

	var r0 *rest.Response
	if rf, ok := ret.Get(0).(func(context.Context, string, ...http.Header) *rest.Response); ok {
		r0 = rf(ctx, url, headers...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rest.Response)
		}
	}

	return r0
}

// MockSyncHTTPClient_DeleteWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteWithContext'
type MockSyncHTTPClient_DeleteWithContext_Call struct {
	*mock.Call
}

// DeleteWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - headers ...http.Header
func (_e *MockSyncHTTPClient_Expecter) DeleteWithContext(ctx interface{}, url interface{}, headers ...interface{}) *MockSyncHTTPClient_DeleteWithContext_Call {
	return &MockSyncHTTPClient_DeleteWithContext_Call{Call: _e.mock.On("DeleteWithContext",
		append([]interface{}{ctx, url}, headers...)...)}
}

func (_c *MockSyncHTTPClient_DeleteWithContext_Call) Run(run func(ctx context.Context, url string, headers ...http.Header)) *MockSyncHTTPClient_DeleteWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockSyncHTTPClient_DeleteWithContext_Call) Return(_a0 *rest.Response) *MockSyncHTTPClient_DeleteWithContext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSyncHTTPClient_DeleteWithContext_Call) RunAndReturn(run func(context.Context, string, ...http.Header) *rest.Response) *MockSyncHTTPClient_DeleteWithContext_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: url, headers
func (_m *MockSyncHTTPClient) Get(url string, headers ...http.Header) *rest.Response {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, url)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *rest.Response
	if rf, ok := ret.Get(0).(func(string, ...http.Header) *rest.Response); ok {
		r0 = rf(url, headers...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rest.Response)
		}
	}

	return r0
}

// MockSyncHTTPClient_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockSyncHTTPClient_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - url string
//   - headers ...http.Header
func (_e *MockSyncHTTPClient_Expecter) Get(url interface{}, headers ...interface{}) *MockSyncHTTPClient_Get_Call {
	return &MockSyncHTTPClient_Get_Call{Call: _e.mock.On("Get",
		append([]interface{}{url}, headers...)...)}
}

func (_c *MockSyncHTTPClient_Get_Call) Run(run func(url string, headers ...http.Header)) *MockSyncHTTPClient_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockSyncHTTPClient_Get_Call) Return(_a0 *rest.Response) *MockSyncHTTPClient_Get_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSyncHTTPClient_Get_Call) RunAndReturn(run func(string, ...http.Header) *rest.Response) *MockSyncHTTPClient_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetWithContext provides a mock function with given fields: ctx, url, headers
func (_m *MockSyncHTTPClient) GetWithContext(ctx context.Context, url string, headers ...http.Header) *rest.Response {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, url)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetWithContext")
	}

	var r0 *rest.Response
	if rf, ok := ret.Get(0).(func(context.Context, string, ...http.Header) *rest.Response); ok {
		r0 = rf(ctx, url, headers...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rest.Response)
		}
	}

	return r0
}

// MockSyncHTTPClient_GetWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWithContext'
type MockSyncHTTPClient_GetWithContext_Call struct {
	*mock.Call
}

// GetWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - headers ...http.Header
func (_e *MockSyncHTTPClient_Expecter) GetWithContext(ctx interface{}, url interface{}, headers ...interface{}) *MockSyncHTTPClient_GetWithContext_Call {
	return &MockSyncHTTPClient_GetWithContext_Call{Call: _e.mock.On("GetWithContext",
		append([]interface{}{ctx, url}, headers...)...)}
}

func (_c *MockSyncHTTPClient_GetWithContext_Call) Run(run func(ctx context.Context, url string, headers ...http.Header)) *MockSyncHTTPClient_GetWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockSyncHTTPClient_GetWithContext_Call) Return(_a0 *rest.Response) *MockSyncHTTPClient_GetWithContext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSyncHTTPClient_GetWithContext_Call) RunAndReturn(run func(context.Context, string, ...http.Header) *rest.Response) *MockSyncHTTPClient_GetWithContext_Call {
	_c.Call.Return(run)
	return _c
}

// Head provides a mock function with given fields: url, headers
func (_m *MockSyncHTTPClient) Head(url string, headers ...http.Header) *rest.Response {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, url)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Head")
	}

	var r0 *rest.Response
	if rf, ok := ret.Get(0).(func(string, ...http.Header) *rest.Response); ok {
		r0 = rf(url, headers...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rest.Response)
		}
	}

	return r0
}

// MockSyncHTTPClient_Head_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Head'
type MockSyncHTTPClient_Head_Call struct {
	*mock.Call
}

// Head is a helper method to define mock.On call
//   - url string
//   - headers ...http.Header
func (_e *MockSyncHTTPClient_Expecter) Head(url interface{}, headers ...interface{}) *MockSyncHTTPClient_Head_Call {
	return &MockSyncHTTPClient_Head_Call{Call: _e.mock.On("Head",
		append([]interface{}{url}, headers...)...)}
}

func (_c *MockSyncHTTPClient_Head_Call) Run(run func(url string, headers ...http.Header)) *MockSyncHTTPClient_Head_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockSyncHTTPClient_Head_Call) Return(_a0 *rest.Response) *MockSyncHTTPClient_Head_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSyncHTTPClient_Head_Call) RunAndReturn(run func(string, ...http.Header) *rest.Response) *MockSyncHTTPClient_Head_Call {
	_c.Call.Return(run)
	return _c
}

// HeadWithContext provides a mock function with given fields: ctx, url, headers
func (_m *MockSyncHTTPClient) HeadWithContext(ctx context.Context, url string, headers ...http.Header) *rest.Response {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, url)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for HeadWithContext")
	}

	var r0 *rest.Response
	if rf, ok := ret.Get(0).(func(context.Context, string, ...http.Header) *rest.Response); ok {
		r0 = rf(ctx, url, headers...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rest.Response)
		}
	}

	return r0
}

// MockSyncHTTPClient_HeadWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HeadWithContext'
type MockSyncHTTPClient_HeadWithContext_Call struct {
	*mock.Call
}

// HeadWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - headers ...http.Header
func (_e *MockSyncHTTPClient_Expecter) HeadWithContext(ctx interface{}, url interface{}, headers ...interface{}) *MockSyncHTTPClient_HeadWithContext_Call {
	return &MockSyncHTTPClient_HeadWithContext_Call{Call: _e.mock.On("HeadWithContext",
		append([]interface{}{ctx, url}, headers...)...)}
}

func (_c *MockSyncHTTPClient_HeadWithContext_Call) Run(run func(ctx context.Context, url string, headers ...http.Header)) *MockSyncHTTPClient_HeadWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockSyncHTTPClient_HeadWithContext_Call) Return(_a0 *rest.Response) *MockSyncHTTPClient_HeadWithContext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSyncHTTPClient_HeadWithContext_Call) RunAndReturn(run func(context.Context, string, ...http.Header) *rest.Response) *MockSyncHTTPClient_HeadWithContext_Call {
	_c.Call.Return(run)
	return _c
}

// Options provides a mock function with given fields: url, headers
func (_m *MockSyncHTTPClient) Options(url string, headers ...http.Header) *rest.Response {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, url)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Options")
	}

	var r0 *rest.Response
	if rf, ok := ret.Get(0).(func(string, ...http.Header) *rest.Response); ok {
		r0 = rf(url, headers...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rest.Response)
		}
	}

	return r0
}

// MockSyncHTTPClient_Options_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Options'
type MockSyncHTTPClient_Options_Call struct {
	*mock.Call
}

// Options is a helper method to define mock.On call
//   - url string
//   - headers ...http.Header
func (_e *MockSyncHTTPClient_Expecter) Options(url interface{}, headers ...interface{}) *MockSyncHTTPClient_Options_Call {
	return &MockSyncHTTPClient_Options_Call{Call: _e.mock.On("Options",
		append([]interface{}{url}, headers...)...)}
}

func (_c *MockSyncHTTPClient_Options_Call) Run(run func(url string, headers ...http.Header)) *MockSyncHTTPClient_Options_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockSyncHTTPClient_Options_Call) Return(_a0 *rest.Response) *MockSyncHTTPClient_Options_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSyncHTTPClient_Options_Call) RunAndReturn(run func(string, ...http.Header) *rest.Response) *MockSyncHTTPClient_Options_Call {
	_c.Call.Return(run)
	return _c
}

// OptionsWithContext provides a mock function with given fields: ctx, url, headers
func (_m *MockSyncHTTPClient) OptionsWithContext(ctx context.Context, url string, headers ...http.Header) *rest.Response {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, url)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for OptionsWithContext")
	}

	var r0 *rest.Response
	if rf, ok := ret.Get(0).(func(context.Context, string, ...http.Header) *rest.Response); ok {
		r0 = rf(ctx, url, headers...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rest.Response)
		}
	}

	return r0
}

// MockSyncHTTPClient_OptionsWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OptionsWithContext'
type MockSyncHTTPClient_OptionsWithContext_Call struct {
	*mock.Call
}

// OptionsWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - headers ...http.Header
func (_e *MockSyncHTTPClient_Expecter) OptionsWithContext(ctx interface{}, url interface{}, headers ...interface{}) *MockSyncHTTPClient_OptionsWithContext_Call {
	return &MockSyncHTTPClient_OptionsWithContext_Call{Call: _e.mock.On("OptionsWithContext",
		append([]interface{}{ctx, url}, headers...)...)}
}

func (_c *MockSyncHTTPClient_OptionsWithContext_Call) Run(run func(ctx context.Context, url string, headers ...http.Header)) *MockSyncHTTPClient_OptionsWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockSyncHTTPClient_OptionsWithContext_Call) Return(_a0 *rest.Response) *MockSyncHTTPClient_OptionsWithContext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSyncHTTPClient_OptionsWithContext_Call) RunAndReturn(run func(context.Context, string, ...http.Header) *rest.Response) *MockSyncHTTPClient_OptionsWithContext_Call {
	_c.Call.Return(run)
	return _c
}

// Patch provides a mock function with given fields: url, body, headers
func (_m *MockSyncHTTPClient) Patch(url string, body any, headers ...http.Header) *rest.Response {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, url, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Patch")
	}

	var r0 *rest.Response
	if rf, ok := ret.Get(0).(func(string, any, ...http.Header) *rest.Response); ok {
		r0 = rf(url, body, headers...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rest.Response)
		}
	}

	return r0
}

// MockSyncHTTPClient_Patch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Patch'
type MockSyncHTTPClient_Patch_Call struct {
	*mock.Call
}

// Patch is a helper method to define mock.On call
//   - url string
//   - body any
//   - headers ...http.Header
func (_e *MockSyncHTTPClient_Expecter) Patch(url interface{}, body interface{}, headers ...interface{}) *MockSyncHTTPClient_Patch_Call {
	return &MockSyncHTTPClient_Patch_Call{Call: _e.mock.On("Patch",
		append([]interface{}{url, body}, headers...)...)}
}

func (_c *MockSyncHTTPClient_Patch_Call) Run(run func(url string, body any, headers ...http.Header)) *MockSyncHTTPClient_Patch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(string), args[1].(any), variadicArgs...)
	})
	return _c
}

func (_c *MockSyncHTTPClient_Patch_Call) Return(_a0 *rest.Response) *MockSyncHTTPClient_Patch_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSyncHTTPClient_Patch_Call) RunAndReturn(run func(string, any, ...http.Header) *rest.Response) *MockSyncHTTPClient_Patch_Call {
	_c.Call.Return(run)
	return _c
}

// PatchWithContext provides a mock function with given fields: ctx, url, body, headers
func (_m *MockSyncHTTPClient) PatchWithContext(ctx context.Context, url string, body any, headers ...http.Header) *rest.Response {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, url, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for PatchWithContext")
	}

	var r0 *rest.Response
	if rf, ok := ret.Get(0).(func(context.Context, string, any, ...http.Header) *rest.Response); ok {
		r0 = rf(ctx, url, body, headers...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rest.Response)
		}
	}

	return r0
}

// MockSyncHTTPClient_PatchWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PatchWithContext'
type MockSyncHTTPClient_PatchWithContext_Call struct {
	*mock.Call
}

// PatchWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - body any
//   - headers ...http.Header
func (_e *MockSyncHTTPClient_Expecter) PatchWithContext(ctx interface{}, url interface{}, body interface{}, headers ...interface{}) *MockSyncHTTPClient_PatchWithContext_Call {
	return &MockSyncHTTPClient_PatchWithContext_Call{Call: _e.mock.On("PatchWithContext",
		append([]interface{}{ctx, url, body}, headers...)...)}
}

func (_c *MockSyncHTTPClient_PatchWithContext_Call) Run(run func(ctx context.Context, url string, body any, headers ...http.Header)) *MockSyncHTTPClient_PatchWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(any), variadicArgs...)
	})
	return _c
}

func (_c *MockSyncHTTPClient_PatchWithContext_Call) Return(_a0 *rest.Response) *MockSyncHTTPClient_PatchWithContext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSyncHTTPClient_PatchWithContext_Call) RunAndReturn(run func(context.Context, string, any, ...http.Header) *rest.Response) *MockSyncHTTPClient_PatchWithContext_Call {
	_c.Call.Return(run)
	return _c
}

// Post provides a mock function with given fields: url, body, headers
func (_m *MockSyncHTTPClient) Post(url string, body any, headers ...http.Header) *rest.Response {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, url, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Post")
	}

	var r0 *rest.Response
	if rf, ok := ret.Get(0).(func(string, any, ...http.Header) *rest.Response); ok {
		r0 = rf(url, body, headers...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rest.Response)
		}
	}

	return r0
}

// MockSyncHTTPClient_Post_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Post'
type MockSyncHTTPClient_Post_Call struct {
	*mock.Call
}

// Post is a helper method to define mock.On call
//   - url string
//   - body any
//   - headers ...http.Header
func (_e *MockSyncHTTPClient_Expecter) Post(url interface{}, body interface{}, headers ...interface{}) *MockSyncHTTPClient_Post_Call {
	return &MockSyncHTTPClient_Post_Call{Call: _e.mock.On("Post",
		append([]interface{}{url, body}, headers...)...)}
}

func (_c *MockSyncHTTPClient_Post_Call) Run(run func(url string, body any, headers ...http.Header)) *MockSyncHTTPClient_Post_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(string), args[1].(any), variadicArgs...)
	})
	return _c
}

func (_c *MockSyncHTTPClient_Post_Call) Return(_a0 *rest.Response) *MockSyncHTTPClient_Post_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSyncHTTPClient_Post_Call) RunAndReturn(run func(string, any, ...http.Header) *rest.Response) *MockSyncHTTPClient_Post_Call {
	_c.Call.Return(run)
	return _c
}

// PostWithContext provides a mock function with given fields: ctx, url, body, headers
func (_m *MockSyncHTTPClient) PostWithContext(ctx context.Context, url string, body any, headers ...http.Header) *rest.Response {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, url, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for PostWithContext")
	}

	var r0 *rest.Response
	if rf, ok := ret.Get(0).(func(context.Context, string, any, ...http.Header) *rest.Response); ok {
		r0 = rf(ctx, url, body, headers...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rest.Response)
		}
	}

	return r0
}

// MockSyncHTTPClient_PostWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostWithContext'
type MockSyncHTTPClient_PostWithContext_Call struct {
	*mock.Call
}

// PostWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - body any
//   - headers ...http.Header
func (_e *MockSyncHTTPClient_Expecter) PostWithContext(ctx interface{}, url interface{}, body interface{}, headers ...interface{}) *MockSyncHTTPClient_PostWithContext_Call {
	return &MockSyncHTTPClient_PostWithContext_Call{Call: _e.mock.On("PostWithContext",
		append([]interface{}{ctx, url, body}, headers...)...)}
}

func (_c *MockSyncHTTPClient_PostWithContext_Call) Run(run func(ctx context.Context, url string, body any, headers ...http.Header)) *MockSyncHTTPClient_PostWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(any), variadicArgs...)
	})
	return _c
}

func (_c *MockSyncHTTPClient_PostWithContext_Call) Return(_a0 *rest.Response) *MockSyncHTTPClient_PostWithContext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSyncHTTPClient_PostWithContext_Call) RunAndReturn(run func(context.Context, string, any, ...http.Header) *rest.Response) *MockSyncHTTPClient_PostWithContext_Call {
	_c.Call.Return(run)
	return _c
}

// Put provides a mock function with given fields: url, body, headers
func (_m *MockSyncHTTPClient) Put(url string, body any, headers ...http.Header) *rest.Response {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, url, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Put")
	}

	var r0 *rest.Response
	if rf, ok := ret.Get(0).(func(string, any, ...http.Header) *rest.Response); ok {
		r0 = rf(url, body, headers...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rest.Response)
		}
	}

	return r0
}

// MockSyncHTTPClient_Put_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Put'
type MockSyncHTTPClient_Put_Call struct {
	*mock.Call
}

// Put is a helper method to define mock.On call
//   - url string
//   - body any
//   - headers ...http.Header
func (_e *MockSyncHTTPClient_Expecter) Put(url interface{}, body interface{}, headers ...interface{}) *MockSyncHTTPClient_Put_Call {
	return &MockSyncHTTPClient_Put_Call{Call: _e.mock.On("Put",
		append([]interface{}{url, body}, headers...)...)}
}

func (_c *MockSyncHTTPClient_Put_Call) Run(run func(url string, body any, headers ...http.Header)) *MockSyncHTTPClient_Put_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(string), args[1].(any), variadicArgs...)
	})
	return _c
}

func (_c *MockSyncHTTPClient_Put_Call) Return(_a0 *rest.Response) *MockSyncHTTPClient_Put_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSyncHTTPClient_Put_Call) RunAndReturn(run func(string, any, ...http.Header) *rest.Response) *MockSyncHTTPClient_Put_Call {
	_c.Call.Return(run)
	return _c
}

// PutWithContext provides a mock function with given fields: ctx, url, body, headers
func (_m *MockSyncHTTPClient) PutWithContext(ctx context.Context, url string, body any, headers ...http.Header) *rest.Response {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, url, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for PutWithContext")
	}

	var r0 *rest.Response
	if rf, ok := ret.Get(0).(func(context.Context, string, any, ...http.Header) *rest.Response); ok {
		r0 = rf(ctx, url, body, headers...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rest.Response)
		}
	}

	return r0
}

// MockSyncHTTPClient_PutWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutWithContext'
type MockSyncHTTPClient_PutWithContext_Call struct {
	*mock.Call
}

// PutWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - body any
//   - headers ...http.Header
func (_e *MockSyncHTTPClient_Expecter) PutWithContext(ctx interface{}, url interface{}, body interface{}, headers ...interface{}) *MockSyncHTTPClient_PutWithContext_Call {
	return &MockSyncHTTPClient_PutWithContext_Call{Call: _e.mock.On("PutWithContext",
		append([]interface{}{ctx, url, body}, headers...)...)}
}

func (_c *MockSyncHTTPClient_PutWithContext_Call) Run(run func(ctx context.Context, url string, body any, headers ...http.Header)) *MockSyncHTTPClient_PutWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(any), variadicArgs...)
	})
	return _c
}

func (_c *MockSyncHTTPClient_PutWithContext_Call) Return(_a0 *rest.Response) *MockSyncHTTPClient_PutWithContext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSyncHTTPClient_PutWithContext_Call) RunAndReturn(run func(context.Context, string, any, ...http.Header) *rest.Response) *MockSyncHTTPClient_PutWithContext_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSyncHTTPClient creates a new instance of MockSyncHTTPClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSyncHTTPClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSyncHTTPClient {
	mock := &MockSyncHTTPClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
