// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	rest "gitlab.com/iskaypetcom/digital/sre/tools/dev/go-restclient/rest"
)

// MockServiceCollector is an autogenerated mock type for the ServiceCollector type
type MockServiceCollector struct {
	mock.Mock
}

type MockServiceCollector_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServiceCollector) EXPECT() *MockServiceCollector_Expecter {
	return &MockServiceCollector_Expecter{mock: &_m.Mock}
}

// IncrementCounter provides a mock function with given fields: metric
func (_m *MockServiceCollector) IncrementCounter(metric rest.CounterDto) {
	_m.Called(metric)
}

// MockServiceCollector_IncrementCounter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncrementCounter'
type MockServiceCollector_IncrementCounter_Call struct {
	*mock.Call
}

// IncrementCounter is a helper method to define mock.On call
//   - metric rest.CounterDto
func (_e *MockServiceCollector_Expecter) IncrementCounter(metric interface{}) *MockServiceCollector_IncrementCounter_Call {
	return &MockServiceCollector_IncrementCounter_Call{Call: _e.mock.On("IncrementCounter", metric)}
}

func (_c *MockServiceCollector_IncrementCounter_Call) Run(run func(metric rest.CounterDto)) *MockServiceCollector_IncrementCounter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(rest.CounterDto))
	})
	return _c
}

func (_c *MockServiceCollector_IncrementCounter_Call) Return() *MockServiceCollector_IncrementCounter_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockServiceCollector_IncrementCounter_Call) RunAndReturn(run func(rest.CounterDto)) *MockServiceCollector_IncrementCounter_Call {
	_c.Call.Return(run)
	return _c
}

// RecordExecutionTime provides a mock function with given fields: metric
func (_m *MockServiceCollector) RecordExecutionTime(metric rest.TimerDto) {
	_m.Called(metric)
}

// MockServiceCollector_RecordExecutionTime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordExecutionTime'
type MockServiceCollector_RecordExecutionTime_Call struct {
	*mock.Call
}

// RecordExecutionTime is a helper method to define mock.On call
//   - metric rest.TimerDto
func (_e *MockServiceCollector_Expecter) RecordExecutionTime(metric interface{}) *MockServiceCollector_RecordExecutionTime_Call {
	return &MockServiceCollector_RecordExecutionTime_Call{Call: _e.mock.On("RecordExecutionTime", metric)}
}

func (_c *MockServiceCollector_RecordExecutionTime_Call) Run(run func(metric rest.TimerDto)) *MockServiceCollector_RecordExecutionTime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(rest.TimerDto))
	})
	return _c
}

func (_c *MockServiceCollector_RecordExecutionTime_Call) Return() *MockServiceCollector_RecordExecutionTime_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockServiceCollector_RecordExecutionTime_Call) RunAndReturn(run func(rest.TimerDto)) *MockServiceCollector_RecordExecutionTime_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockServiceCollector creates a new instance of MockServiceCollector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServiceCollector(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServiceCollector {
	mock := &MockServiceCollector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
