// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockKey is an autogenerated mock type for the Key type
type MockKey struct {
	mock.Mock
}

type MockKey_Expecter struct {
	mock *mock.Mock
}

func (_m *MockKey) EXPECT() *MockKey_Expecter {
	return &MockKey_Expecter{mock: &_m.Mock}
}

// NewMockKey creates a new instance of MockKey. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockKey(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockKey {
	mock := &MockKey{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
