// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	io "io"
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// MockMediaMarshaler is an autogenerated mock type for the MediaMarshaler type
type MockMediaMarshaler struct {
	mock.Mock
}

type MockMediaMarshaler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMediaMarshaler) EXPECT() *MockMediaMarshaler_Expecter {
	return &MockMediaMarshaler_Expecter{mock: &_m.Mock}
}

// DefaultHeaders provides a mock function with no fields
func (_m *MockMediaMarshaler) DefaultHeaders() http.Header {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for DefaultHeaders")
	}

	var r0 http.Header
	if rf, ok := ret.Get(0).(func() http.Header); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http.Header)
		}
	}

	return r0
}

// MockMediaMarshaler_DefaultHeaders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DefaultHeaders'
type MockMediaMarshaler_DefaultHeaders_Call struct {
	*mock.Call
}

// DefaultHeaders is a helper method to define mock.On call
func (_e *MockMediaMarshaler_Expecter) DefaultHeaders() *MockMediaMarshaler_DefaultHeaders_Call {
	return &MockMediaMarshaler_DefaultHeaders_Call{Call: _e.mock.On("DefaultHeaders")}
}

func (_c *MockMediaMarshaler_DefaultHeaders_Call) Run(run func()) *MockMediaMarshaler_DefaultHeaders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMediaMarshaler_DefaultHeaders_Call) Return(_a0 http.Header) *MockMediaMarshaler_DefaultHeaders_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMediaMarshaler_DefaultHeaders_Call) RunAndReturn(run func() http.Header) *MockMediaMarshaler_DefaultHeaders_Call {
	_c.Call.Return(run)
	return _c
}

// Marshal provides a mock function with given fields: body
func (_m *MockMediaMarshaler) Marshal(body any) (io.Reader, error) {
	ret := _m.Called(body)

	if len(ret) == 0 {
		panic("no return value specified for Marshal")
	}

	var r0 io.Reader
	var r1 error
	if rf, ok := ret.Get(0).(func(any) (io.Reader, error)); ok {
		return rf(body)
	}
	if rf, ok := ret.Get(0).(func(any) io.Reader); ok {
		r0 = rf(body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.Reader)
		}
	}

	if rf, ok := ret.Get(1).(func(any) error); ok {
		r1 = rf(body)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMediaMarshaler_Marshal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Marshal'
type MockMediaMarshaler_Marshal_Call struct {
	*mock.Call
}

// Marshal is a helper method to define mock.On call
//   - body any
func (_e *MockMediaMarshaler_Expecter) Marshal(body interface{}) *MockMediaMarshaler_Marshal_Call {
	return &MockMediaMarshaler_Marshal_Call{Call: _e.mock.On("Marshal", body)}
}

func (_c *MockMediaMarshaler_Marshal_Call) Run(run func(body any)) *MockMediaMarshaler_Marshal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(any))
	})
	return _c
}

func (_c *MockMediaMarshaler_Marshal_Call) Return(_a0 io.Reader, _a1 error) *MockMediaMarshaler_Marshal_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMediaMarshaler_Marshal_Call) RunAndReturn(run func(any) (io.Reader, error)) *MockMediaMarshaler_Marshal_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMediaMarshaler creates a new instance of MockMediaMarshaler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMediaMarshaler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMediaMarshaler {
	mock := &MockMediaMarshaler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
