// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockMapper is an autogenerated mock type for the Mapper type
type MockMapper struct {
	mock.Mock
}

type MockMapper_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMapper) EXPECT() *MockMapper_Expecter {
	return &MockMapper_Expecter{mock: &_m.Mock}
}

// BuildLabels provides a mock function with given fields:
func (_m *MockMapper) BuildLabels() []string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for BuildLabels")
	}

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// MockMapper_BuildLabels_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BuildLabels'
type MockMapper_BuildLabels_Call struct {
	*mock.Call
}

// BuildLabels is a helper method to define mock.On call
func (_e *MockMapper_Expecter) BuildLabels() *MockMapper_BuildLabels_Call {
	return &MockMapper_BuildLabels_Call{Call: _e.mock.On("BuildLabels")}
}

func (_c *MockMapper_BuildLabels_Call) Run(run func()) *MockMapper_BuildLabels_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMapper_BuildLabels_Call) Return(_a0 []string) *MockMapper_BuildLabels_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMapper_BuildLabels_Call) RunAndReturn(run func() []string) *MockMapper_BuildLabels_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMapper creates a new instance of MockMapper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMapper(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMapper {
	mock := &MockMapper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
