// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockNamedMedia is an autogenerated mock type for the NamedMedia type
type MockNamedMedia struct {
	mock.Mock
}

type MockNamedMedia_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNamedMedia) EXPECT() *MockNamedMedia_Expecter {
	return &MockNamedMedia_Expecter{mock: &_m.Mock}
}

// Name provides a mock function with given fields:
func (_m *MockNamedMedia) Name() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockNamedMedia_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockNamedMedia_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockNamedMedia_Expecter) Name() *MockNamedMedia_Name_Call {
	return &MockNamedMedia_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockNamedMedia_Name_Call) Run(run func()) *MockNamedMedia_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNamedMedia_Name_Call) Return(_a0 string) *MockNamedMedia_Name_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNamedMedia_Name_Call) RunAndReturn(run func() string) *MockNamedMedia_Name_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockNamedMedia creates a new instance of MockNamedMedia. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNamedMedia(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNamedMedia {
	mock := &MockNamedMedia{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
