// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockClientMetricCollector is an autogenerated mock type for the ClientMetricCollector type
type MockClientMetricCollector struct {
	mock.Mock
}

type MockClientMetricCollector_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClientMetricCollector) EXPECT() *MockClientMetricCollector_Expecter {
	return &MockClientMetricCollector_Expecter{mock: &_m.Mock}
}

// IncrementCounter provides a mock function with given fields: clientName, eventType, eventSubType, value
func (_m *MockClientMetricCollector) IncrementCounter(clientName string, eventType string, eventSubType string, value ...float64) {
	_va := make([]interface{}, len(value))
	for _i := range value {
		_va[_i] = value[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, clientName, eventType, eventSubType)
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// MockClientMetricCollector_IncrementCounter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncrementCounter'
type MockClientMetricCollector_IncrementCounter_Call struct {
	*mock.Call
}

// IncrementCounter is a helper method to define mock.On call
//   - clientName string
//   - eventType string
//   - eventSubType string
//   - value ...float64
func (_e *MockClientMetricCollector_Expecter) IncrementCounter(clientName interface{}, eventType interface{}, eventSubType interface{}, value ...interface{}) *MockClientMetricCollector_IncrementCounter_Call {
	return &MockClientMetricCollector_IncrementCounter_Call{Call: _e.mock.On("IncrementCounter",
		append([]interface{}{clientName, eventType, eventSubType}, value...)...)}
}

func (_c *MockClientMetricCollector_IncrementCounter_Call) Run(run func(clientName string, eventType string, eventSubType string, value ...float64)) *MockClientMetricCollector_IncrementCounter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]float64, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(float64)
			}
		}
		run(args[0].(string), args[1].(string), args[2].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockClientMetricCollector_IncrementCounter_Call) Return() *MockClientMetricCollector_IncrementCounter_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockClientMetricCollector_IncrementCounter_Call) RunAndReturn(run func(string, string, string, ...float64)) *MockClientMetricCollector_IncrementCounter_Call {
	_c.Call.Return(run)
	return _c
}

// RecordExecutionTime provides a mock function with given fields: clientName, eventType, eventSubType, elapsedTime
func (_m *MockClientMetricCollector) RecordExecutionTime(clientName string, eventType string, eventSubType string, elapsedTime time.Duration) {
	_m.Called(clientName, eventType, eventSubType, elapsedTime)
}

// MockClientMetricCollector_RecordExecutionTime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordExecutionTime'
type MockClientMetricCollector_RecordExecutionTime_Call struct {
	*mock.Call
}

// RecordExecutionTime is a helper method to define mock.On call
//   - clientName string
//   - eventType string
//   - eventSubType string
//   - elapsedTime time.Duration
func (_e *MockClientMetricCollector_Expecter) RecordExecutionTime(clientName interface{}, eventType interface{}, eventSubType interface{}, elapsedTime interface{}) *MockClientMetricCollector_RecordExecutionTime_Call {
	return &MockClientMetricCollector_RecordExecutionTime_Call{Call: _e.mock.On("RecordExecutionTime", clientName, eventType, eventSubType, elapsedTime)}
}

func (_c *MockClientMetricCollector_RecordExecutionTime_Call) Run(run func(clientName string, eventType string, eventSubType string, elapsedTime time.Duration)) *MockClientMetricCollector_RecordExecutionTime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string), args[3].(time.Duration))
	})
	return _c
}

func (_c *MockClientMetricCollector_RecordExecutionTime_Call) Return() *MockClientMetricCollector_RecordExecutionTime_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockClientMetricCollector_RecordExecutionTime_Call) RunAndReturn(run func(string, string, string, time.Duration)) *MockClientMetricCollector_RecordExecutionTime_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClientMetricCollector creates a new instance of MockClientMetricCollector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClientMetricCollector(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClientMetricCollector {
	mock := &MockClientMetricCollector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
