// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	http "net/http"

	mock "github.com/stretchr/testify/mock"

	rest "gitlab.com/iskaypetcom/digital/sre/tools/dev/go-restclient/rest"
)

// MockAsyncHTTPClient is an autogenerated mock type for the AsyncHTTPClient type
type MockAsyncHTTPClient struct {
	mock.Mock
}

type MockAsyncHTTPClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAsyncHTTPClient) EXPECT() *MockAsyncHTTPClient_Expecter {
	return &MockAsyncHTTPClient_Expecter{mock: &_m.Mock}
}

// AsyncDelete provides a mock function with given fields: url, f, headers
func (_m *MockAsyncHTTPClient) AsyncDelete(url string, f func(*rest.Response), headers ...http.Header) {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, url, f)
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// MockAsyncHTTPClient_AsyncDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AsyncDelete'
type MockAsyncHTTPClient_AsyncDelete_Call struct {
	*mock.Call
}

// AsyncDelete is a helper method to define mock.On call
//   - url string
//   - f func(*rest.Response)
//   - headers ...http.Header
func (_e *MockAsyncHTTPClient_Expecter) AsyncDelete(url interface{}, f interface{}, headers ...interface{}) *MockAsyncHTTPClient_AsyncDelete_Call {
	return &MockAsyncHTTPClient_AsyncDelete_Call{Call: _e.mock.On("AsyncDelete",
		append([]interface{}{url, f}, headers...)...)}
}

func (_c *MockAsyncHTTPClient_AsyncDelete_Call) Run(run func(url string, f func(*rest.Response), headers ...http.Header)) *MockAsyncHTTPClient_AsyncDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(string), args[1].(func(*rest.Response)), variadicArgs...)
	})
	return _c
}

func (_c *MockAsyncHTTPClient_AsyncDelete_Call) Return() *MockAsyncHTTPClient_AsyncDelete_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAsyncHTTPClient_AsyncDelete_Call) RunAndReturn(run func(string, func(*rest.Response), ...http.Header)) *MockAsyncHTTPClient_AsyncDelete_Call {
	_c.Run(run)
	return _c
}

// AsyncDeleteWithContext provides a mock function with given fields: ctx, url, f, headers
func (_m *MockAsyncHTTPClient) AsyncDeleteWithContext(ctx context.Context, url string, f func(*rest.Response), headers ...http.Header) {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, url, f)
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// MockAsyncHTTPClient_AsyncDeleteWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AsyncDeleteWithContext'
type MockAsyncHTTPClient_AsyncDeleteWithContext_Call struct {
	*mock.Call
}

// AsyncDeleteWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - f func(*rest.Response)
//   - headers ...http.Header
func (_e *MockAsyncHTTPClient_Expecter) AsyncDeleteWithContext(ctx interface{}, url interface{}, f interface{}, headers ...interface{}) *MockAsyncHTTPClient_AsyncDeleteWithContext_Call {
	return &MockAsyncHTTPClient_AsyncDeleteWithContext_Call{Call: _e.mock.On("AsyncDeleteWithContext",
		append([]interface{}{ctx, url, f}, headers...)...)}
}

func (_c *MockAsyncHTTPClient_AsyncDeleteWithContext_Call) Run(run func(ctx context.Context, url string, f func(*rest.Response), headers ...http.Header)) *MockAsyncHTTPClient_AsyncDeleteWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(func(*rest.Response)), variadicArgs...)
	})
	return _c
}

func (_c *MockAsyncHTTPClient_AsyncDeleteWithContext_Call) Return() *MockAsyncHTTPClient_AsyncDeleteWithContext_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAsyncHTTPClient_AsyncDeleteWithContext_Call) RunAndReturn(run func(context.Context, string, func(*rest.Response), ...http.Header)) *MockAsyncHTTPClient_AsyncDeleteWithContext_Call {
	_c.Run(run)
	return _c
}

// AsyncGet provides a mock function with given fields: url, f, headers
func (_m *MockAsyncHTTPClient) AsyncGet(url string, f func(*rest.Response), headers ...http.Header) {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, url, f)
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// MockAsyncHTTPClient_AsyncGet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AsyncGet'
type MockAsyncHTTPClient_AsyncGet_Call struct {
	*mock.Call
}

// AsyncGet is a helper method to define mock.On call
//   - url string
//   - f func(*rest.Response)
//   - headers ...http.Header
func (_e *MockAsyncHTTPClient_Expecter) AsyncGet(url interface{}, f interface{}, headers ...interface{}) *MockAsyncHTTPClient_AsyncGet_Call {
	return &MockAsyncHTTPClient_AsyncGet_Call{Call: _e.mock.On("AsyncGet",
		append([]interface{}{url, f}, headers...)...)}
}

func (_c *MockAsyncHTTPClient_AsyncGet_Call) Run(run func(url string, f func(*rest.Response), headers ...http.Header)) *MockAsyncHTTPClient_AsyncGet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(string), args[1].(func(*rest.Response)), variadicArgs...)
	})
	return _c
}

func (_c *MockAsyncHTTPClient_AsyncGet_Call) Return() *MockAsyncHTTPClient_AsyncGet_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAsyncHTTPClient_AsyncGet_Call) RunAndReturn(run func(string, func(*rest.Response), ...http.Header)) *MockAsyncHTTPClient_AsyncGet_Call {
	_c.Run(run)
	return _c
}

// AsyncGetWithContext provides a mock function with given fields: ctx, url, f, headers
func (_m *MockAsyncHTTPClient) AsyncGetWithContext(ctx context.Context, url string, f func(*rest.Response), headers ...http.Header) {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, url, f)
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// MockAsyncHTTPClient_AsyncGetWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AsyncGetWithContext'
type MockAsyncHTTPClient_AsyncGetWithContext_Call struct {
	*mock.Call
}

// AsyncGetWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - f func(*rest.Response)
//   - headers ...http.Header
func (_e *MockAsyncHTTPClient_Expecter) AsyncGetWithContext(ctx interface{}, url interface{}, f interface{}, headers ...interface{}) *MockAsyncHTTPClient_AsyncGetWithContext_Call {
	return &MockAsyncHTTPClient_AsyncGetWithContext_Call{Call: _e.mock.On("AsyncGetWithContext",
		append([]interface{}{ctx, url, f}, headers...)...)}
}

func (_c *MockAsyncHTTPClient_AsyncGetWithContext_Call) Run(run func(ctx context.Context, url string, f func(*rest.Response), headers ...http.Header)) *MockAsyncHTTPClient_AsyncGetWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(func(*rest.Response)), variadicArgs...)
	})
	return _c
}

func (_c *MockAsyncHTTPClient_AsyncGetWithContext_Call) Return() *MockAsyncHTTPClient_AsyncGetWithContext_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAsyncHTTPClient_AsyncGetWithContext_Call) RunAndReturn(run func(context.Context, string, func(*rest.Response), ...http.Header)) *MockAsyncHTTPClient_AsyncGetWithContext_Call {
	_c.Run(run)
	return _c
}

// AsyncHead provides a mock function with given fields: url, f, headers
func (_m *MockAsyncHTTPClient) AsyncHead(url string, f func(*rest.Response), headers ...http.Header) {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, url, f)
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// MockAsyncHTTPClient_AsyncHead_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AsyncHead'
type MockAsyncHTTPClient_AsyncHead_Call struct {
	*mock.Call
}

// AsyncHead is a helper method to define mock.On call
//   - url string
//   - f func(*rest.Response)
//   - headers ...http.Header
func (_e *MockAsyncHTTPClient_Expecter) AsyncHead(url interface{}, f interface{}, headers ...interface{}) *MockAsyncHTTPClient_AsyncHead_Call {
	return &MockAsyncHTTPClient_AsyncHead_Call{Call: _e.mock.On("AsyncHead",
		append([]interface{}{url, f}, headers...)...)}
}

func (_c *MockAsyncHTTPClient_AsyncHead_Call) Run(run func(url string, f func(*rest.Response), headers ...http.Header)) *MockAsyncHTTPClient_AsyncHead_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(string), args[1].(func(*rest.Response)), variadicArgs...)
	})
	return _c
}

func (_c *MockAsyncHTTPClient_AsyncHead_Call) Return() *MockAsyncHTTPClient_AsyncHead_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAsyncHTTPClient_AsyncHead_Call) RunAndReturn(run func(string, func(*rest.Response), ...http.Header)) *MockAsyncHTTPClient_AsyncHead_Call {
	_c.Run(run)
	return _c
}

// AsyncHeadWithContext provides a mock function with given fields: ctx, url, f, headers
func (_m *MockAsyncHTTPClient) AsyncHeadWithContext(ctx context.Context, url string, f func(*rest.Response), headers ...http.Header) {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, url, f)
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// MockAsyncHTTPClient_AsyncHeadWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AsyncHeadWithContext'
type MockAsyncHTTPClient_AsyncHeadWithContext_Call struct {
	*mock.Call
}

// AsyncHeadWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - f func(*rest.Response)
//   - headers ...http.Header
func (_e *MockAsyncHTTPClient_Expecter) AsyncHeadWithContext(ctx interface{}, url interface{}, f interface{}, headers ...interface{}) *MockAsyncHTTPClient_AsyncHeadWithContext_Call {
	return &MockAsyncHTTPClient_AsyncHeadWithContext_Call{Call: _e.mock.On("AsyncHeadWithContext",
		append([]interface{}{ctx, url, f}, headers...)...)}
}

func (_c *MockAsyncHTTPClient_AsyncHeadWithContext_Call) Run(run func(ctx context.Context, url string, f func(*rest.Response), headers ...http.Header)) *MockAsyncHTTPClient_AsyncHeadWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(func(*rest.Response)), variadicArgs...)
	})
	return _c
}

func (_c *MockAsyncHTTPClient_AsyncHeadWithContext_Call) Return() *MockAsyncHTTPClient_AsyncHeadWithContext_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAsyncHTTPClient_AsyncHeadWithContext_Call) RunAndReturn(run func(context.Context, string, func(*rest.Response), ...http.Header)) *MockAsyncHTTPClient_AsyncHeadWithContext_Call {
	_c.Run(run)
	return _c
}

// AsyncOptions provides a mock function with given fields: url, f, headers
func (_m *MockAsyncHTTPClient) AsyncOptions(url string, f func(*rest.Response), headers ...http.Header) {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, url, f)
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// MockAsyncHTTPClient_AsyncOptions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AsyncOptions'
type MockAsyncHTTPClient_AsyncOptions_Call struct {
	*mock.Call
}

// AsyncOptions is a helper method to define mock.On call
//   - url string
//   - f func(*rest.Response)
//   - headers ...http.Header
func (_e *MockAsyncHTTPClient_Expecter) AsyncOptions(url interface{}, f interface{}, headers ...interface{}) *MockAsyncHTTPClient_AsyncOptions_Call {
	return &MockAsyncHTTPClient_AsyncOptions_Call{Call: _e.mock.On("AsyncOptions",
		append([]interface{}{url, f}, headers...)...)}
}

func (_c *MockAsyncHTTPClient_AsyncOptions_Call) Run(run func(url string, f func(*rest.Response), headers ...http.Header)) *MockAsyncHTTPClient_AsyncOptions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(string), args[1].(func(*rest.Response)), variadicArgs...)
	})
	return _c
}

func (_c *MockAsyncHTTPClient_AsyncOptions_Call) Return() *MockAsyncHTTPClient_AsyncOptions_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAsyncHTTPClient_AsyncOptions_Call) RunAndReturn(run func(string, func(*rest.Response), ...http.Header)) *MockAsyncHTTPClient_AsyncOptions_Call {
	_c.Run(run)
	return _c
}

// AsyncOptionsWithContext provides a mock function with given fields: ctx, url, f, headers
func (_m *MockAsyncHTTPClient) AsyncOptionsWithContext(ctx context.Context, url string, f func(*rest.Response), headers ...http.Header) {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, url, f)
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// MockAsyncHTTPClient_AsyncOptionsWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AsyncOptionsWithContext'
type MockAsyncHTTPClient_AsyncOptionsWithContext_Call struct {
	*mock.Call
}

// AsyncOptionsWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - f func(*rest.Response)
//   - headers ...http.Header
func (_e *MockAsyncHTTPClient_Expecter) AsyncOptionsWithContext(ctx interface{}, url interface{}, f interface{}, headers ...interface{}) *MockAsyncHTTPClient_AsyncOptionsWithContext_Call {
	return &MockAsyncHTTPClient_AsyncOptionsWithContext_Call{Call: _e.mock.On("AsyncOptionsWithContext",
		append([]interface{}{ctx, url, f}, headers...)...)}
}

func (_c *MockAsyncHTTPClient_AsyncOptionsWithContext_Call) Run(run func(ctx context.Context, url string, f func(*rest.Response), headers ...http.Header)) *MockAsyncHTTPClient_AsyncOptionsWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(func(*rest.Response)), variadicArgs...)
	})
	return _c
}

func (_c *MockAsyncHTTPClient_AsyncOptionsWithContext_Call) Return() *MockAsyncHTTPClient_AsyncOptionsWithContext_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAsyncHTTPClient_AsyncOptionsWithContext_Call) RunAndReturn(run func(context.Context, string, func(*rest.Response), ...http.Header)) *MockAsyncHTTPClient_AsyncOptionsWithContext_Call {
	_c.Run(run)
	return _c
}

// AsyncPatch provides a mock function with given fields: url, body, f, headers
func (_m *MockAsyncHTTPClient) AsyncPatch(url string, body any, f func(*rest.Response), headers ...http.Header) {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, url, body, f)
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// MockAsyncHTTPClient_AsyncPatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AsyncPatch'
type MockAsyncHTTPClient_AsyncPatch_Call struct {
	*mock.Call
}

// AsyncPatch is a helper method to define mock.On call
//   - url string
//   - body any
//   - f func(*rest.Response)
//   - headers ...http.Header
func (_e *MockAsyncHTTPClient_Expecter) AsyncPatch(url interface{}, body interface{}, f interface{}, headers ...interface{}) *MockAsyncHTTPClient_AsyncPatch_Call {
	return &MockAsyncHTTPClient_AsyncPatch_Call{Call: _e.mock.On("AsyncPatch",
		append([]interface{}{url, body, f}, headers...)...)}
}

func (_c *MockAsyncHTTPClient_AsyncPatch_Call) Run(run func(url string, body any, f func(*rest.Response), headers ...http.Header)) *MockAsyncHTTPClient_AsyncPatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(string), args[1].(any), args[2].(func(*rest.Response)), variadicArgs...)
	})
	return _c
}

func (_c *MockAsyncHTTPClient_AsyncPatch_Call) Return() *MockAsyncHTTPClient_AsyncPatch_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAsyncHTTPClient_AsyncPatch_Call) RunAndReturn(run func(string, any, func(*rest.Response), ...http.Header)) *MockAsyncHTTPClient_AsyncPatch_Call {
	_c.Run(run)
	return _c
}

// AsyncPatchWithContext provides a mock function with given fields: ctx, url, body, f, headers
func (_m *MockAsyncHTTPClient) AsyncPatchWithContext(ctx context.Context, url string, body any, f func(*rest.Response), headers ...http.Header) {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, url, body, f)
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// MockAsyncHTTPClient_AsyncPatchWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AsyncPatchWithContext'
type MockAsyncHTTPClient_AsyncPatchWithContext_Call struct {
	*mock.Call
}

// AsyncPatchWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - body any
//   - f func(*rest.Response)
//   - headers ...http.Header
func (_e *MockAsyncHTTPClient_Expecter) AsyncPatchWithContext(ctx interface{}, url interface{}, body interface{}, f interface{}, headers ...interface{}) *MockAsyncHTTPClient_AsyncPatchWithContext_Call {
	return &MockAsyncHTTPClient_AsyncPatchWithContext_Call{Call: _e.mock.On("AsyncPatchWithContext",
		append([]interface{}{ctx, url, body, f}, headers...)...)}
}

func (_c *MockAsyncHTTPClient_AsyncPatchWithContext_Call) Run(run func(ctx context.Context, url string, body any, f func(*rest.Response), headers ...http.Header)) *MockAsyncHTTPClient_AsyncPatchWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-4)
		for i, a := range args[4:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(any), args[3].(func(*rest.Response)), variadicArgs...)
	})
	return _c
}

func (_c *MockAsyncHTTPClient_AsyncPatchWithContext_Call) Return() *MockAsyncHTTPClient_AsyncPatchWithContext_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAsyncHTTPClient_AsyncPatchWithContext_Call) RunAndReturn(run func(context.Context, string, any, func(*rest.Response), ...http.Header)) *MockAsyncHTTPClient_AsyncPatchWithContext_Call {
	_c.Run(run)
	return _c
}

// AsyncPost provides a mock function with given fields: url, body, f, headers
func (_m *MockAsyncHTTPClient) AsyncPost(url string, body any, f func(*rest.Response), headers ...http.Header) {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, url, body, f)
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// MockAsyncHTTPClient_AsyncPost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AsyncPost'
type MockAsyncHTTPClient_AsyncPost_Call struct {
	*mock.Call
}

// AsyncPost is a helper method to define mock.On call
//   - url string
//   - body any
//   - f func(*rest.Response)
//   - headers ...http.Header
func (_e *MockAsyncHTTPClient_Expecter) AsyncPost(url interface{}, body interface{}, f interface{}, headers ...interface{}) *MockAsyncHTTPClient_AsyncPost_Call {
	return &MockAsyncHTTPClient_AsyncPost_Call{Call: _e.mock.On("AsyncPost",
		append([]interface{}{url, body, f}, headers...)...)}
}

func (_c *MockAsyncHTTPClient_AsyncPost_Call) Run(run func(url string, body any, f func(*rest.Response), headers ...http.Header)) *MockAsyncHTTPClient_AsyncPost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(string), args[1].(any), args[2].(func(*rest.Response)), variadicArgs...)
	})
	return _c
}

func (_c *MockAsyncHTTPClient_AsyncPost_Call) Return() *MockAsyncHTTPClient_AsyncPost_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAsyncHTTPClient_AsyncPost_Call) RunAndReturn(run func(string, any, func(*rest.Response), ...http.Header)) *MockAsyncHTTPClient_AsyncPost_Call {
	_c.Run(run)
	return _c
}

// AsyncPostWithContext provides a mock function with given fields: ctx, url, body, f, headers
func (_m *MockAsyncHTTPClient) AsyncPostWithContext(ctx context.Context, url string, body any, f func(*rest.Response), headers ...http.Header) {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, url, body, f)
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// MockAsyncHTTPClient_AsyncPostWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AsyncPostWithContext'
type MockAsyncHTTPClient_AsyncPostWithContext_Call struct {
	*mock.Call
}

// AsyncPostWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - body any
//   - f func(*rest.Response)
//   - headers ...http.Header
func (_e *MockAsyncHTTPClient_Expecter) AsyncPostWithContext(ctx interface{}, url interface{}, body interface{}, f interface{}, headers ...interface{}) *MockAsyncHTTPClient_AsyncPostWithContext_Call {
	return &MockAsyncHTTPClient_AsyncPostWithContext_Call{Call: _e.mock.On("AsyncPostWithContext",
		append([]interface{}{ctx, url, body, f}, headers...)...)}
}

func (_c *MockAsyncHTTPClient_AsyncPostWithContext_Call) Run(run func(ctx context.Context, url string, body any, f func(*rest.Response), headers ...http.Header)) *MockAsyncHTTPClient_AsyncPostWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-4)
		for i, a := range args[4:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(any), args[3].(func(*rest.Response)), variadicArgs...)
	})
	return _c
}

func (_c *MockAsyncHTTPClient_AsyncPostWithContext_Call) Return() *MockAsyncHTTPClient_AsyncPostWithContext_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAsyncHTTPClient_AsyncPostWithContext_Call) RunAndReturn(run func(context.Context, string, any, func(*rest.Response), ...http.Header)) *MockAsyncHTTPClient_AsyncPostWithContext_Call {
	_c.Run(run)
	return _c
}

// AsyncPut provides a mock function with given fields: url, body, f, headers
func (_m *MockAsyncHTTPClient) AsyncPut(url string, body any, f func(*rest.Response), headers ...http.Header) {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, url, body, f)
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// MockAsyncHTTPClient_AsyncPut_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AsyncPut'
type MockAsyncHTTPClient_AsyncPut_Call struct {
	*mock.Call
}

// AsyncPut is a helper method to define mock.On call
//   - url string
//   - body any
//   - f func(*rest.Response)
//   - headers ...http.Header
func (_e *MockAsyncHTTPClient_Expecter) AsyncPut(url interface{}, body interface{}, f interface{}, headers ...interface{}) *MockAsyncHTTPClient_AsyncPut_Call {
	return &MockAsyncHTTPClient_AsyncPut_Call{Call: _e.mock.On("AsyncPut",
		append([]interface{}{url, body, f}, headers...)...)}
}

func (_c *MockAsyncHTTPClient_AsyncPut_Call) Run(run func(url string, body any, f func(*rest.Response), headers ...http.Header)) *MockAsyncHTTPClient_AsyncPut_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(string), args[1].(any), args[2].(func(*rest.Response)), variadicArgs...)
	})
	return _c
}

func (_c *MockAsyncHTTPClient_AsyncPut_Call) Return() *MockAsyncHTTPClient_AsyncPut_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAsyncHTTPClient_AsyncPut_Call) RunAndReturn(run func(string, any, func(*rest.Response), ...http.Header)) *MockAsyncHTTPClient_AsyncPut_Call {
	_c.Run(run)
	return _c
}

// AsyncPutWithContext provides a mock function with given fields: ctx, url, body, f, headers
func (_m *MockAsyncHTTPClient) AsyncPutWithContext(ctx context.Context, url string, body any, f func(*rest.Response), headers ...http.Header) {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, url, body, f)
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// MockAsyncHTTPClient_AsyncPutWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AsyncPutWithContext'
type MockAsyncHTTPClient_AsyncPutWithContext_Call struct {
	*mock.Call
}

// AsyncPutWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - body any
//   - f func(*rest.Response)
//   - headers ...http.Header
func (_e *MockAsyncHTTPClient_Expecter) AsyncPutWithContext(ctx interface{}, url interface{}, body interface{}, f interface{}, headers ...interface{}) *MockAsyncHTTPClient_AsyncPutWithContext_Call {
	return &MockAsyncHTTPClient_AsyncPutWithContext_Call{Call: _e.mock.On("AsyncPutWithContext",
		append([]interface{}{ctx, url, body, f}, headers...)...)}
}

func (_c *MockAsyncHTTPClient_AsyncPutWithContext_Call) Run(run func(ctx context.Context, url string, body any, f func(*rest.Response), headers ...http.Header)) *MockAsyncHTTPClient_AsyncPutWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-4)
		for i, a := range args[4:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(any), args[3].(func(*rest.Response)), variadicArgs...)
	})
	return _c
}

func (_c *MockAsyncHTTPClient_AsyncPutWithContext_Call) Return() *MockAsyncHTTPClient_AsyncPutWithContext_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAsyncHTTPClient_AsyncPutWithContext_Call) RunAndReturn(run func(context.Context, string, any, func(*rest.Response), ...http.Header)) *MockAsyncHTTPClient_AsyncPutWithContext_Call {
	_c.Run(run)
	return _c
}

// NewMockAsyncHTTPClient creates a new instance of MockAsyncHTTPClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAsyncHTTPClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAsyncHTTPClient {
	mock := &MockAsyncHTTPClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
