// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockRecordValueFunc is an autogenerated mock type for the RecordValueFunc type
type MockRecordValueFunc struct {
	mock.Mock
}

type MockRecordValueFunc_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRecordValueFunc) EXPECT() *MockRecordValueFunc_Expecter {
	return &MockRecordValueFunc_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with no fields
func (_m *MockRecordValueFunc) Execute() float64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 float64
	if rf, ok := ret.Get(0).(func() float64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(float64)
	}

	return r0
}

// MockRecordValueFunc_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockRecordValueFunc_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
func (_e *MockRecordValueFunc_Expecter) Execute() *MockRecordValueFunc_Execute_Call {
	return &MockRecordValueFunc_Execute_Call{Call: _e.mock.On("Execute")}
}

func (_c *MockRecordValueFunc_Execute_Call) Run(run func()) *MockRecordValueFunc_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRecordValueFunc_Execute_Call) Return(_a0 float64) *MockRecordValueFunc_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRecordValueFunc_Execute_Call) RunAndReturn(run func() float64) *MockRecordValueFunc_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRecordValueFunc creates a new instance of MockRecordValueFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRecordValueFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRecordValueFunc {
	mock := &MockRecordValueFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
