// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	http "net/http"

	mock "github.com/stretchr/testify/mock"

	rest "gitlab.com/iskaypetcom/digital/sre/tools/dev/go-restclient/rest"
)

// MockAsyncChanHTTPClient is an autogenerated mock type for the AsyncChanHTTPClient type
type MockAsyncChanHTTPClient struct {
	mock.Mock
}

type MockAsyncChanHTTPClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAsyncChanHTTPClient) EXPECT() *MockAsyncChanHTTPClient_Expecter {
	return &MockAsyncChanHTTPClient_Expecter{mock: &_m.Mock}
}

// ChanDelete provides a mock function with given fields: url, headers
func (_m *MockAsyncChanHTTPClient) ChanDelete(url string, headers ...http.Header) <-chan *rest.Response {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, url)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ChanDelete")
	}

	var r0 <-chan *rest.Response
	if rf, ok := ret.Get(0).(func(string, ...http.Header) <-chan *rest.Response); ok {
		r0 = rf(url, headers...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan *rest.Response)
		}
	}

	return r0
}

// MockAsyncChanHTTPClient_ChanDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChanDelete'
type MockAsyncChanHTTPClient_ChanDelete_Call struct {
	*mock.Call
}

// ChanDelete is a helper method to define mock.On call
//   - url string
//   - headers ...http.Header
func (_e *MockAsyncChanHTTPClient_Expecter) ChanDelete(url interface{}, headers ...interface{}) *MockAsyncChanHTTPClient_ChanDelete_Call {
	return &MockAsyncChanHTTPClient_ChanDelete_Call{Call: _e.mock.On("ChanDelete",
		append([]interface{}{url}, headers...)...)}
}

func (_c *MockAsyncChanHTTPClient_ChanDelete_Call) Run(run func(url string, headers ...http.Header)) *MockAsyncChanHTTPClient_ChanDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockAsyncChanHTTPClient_ChanDelete_Call) Return(_a0 <-chan *rest.Response) *MockAsyncChanHTTPClient_ChanDelete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAsyncChanHTTPClient_ChanDelete_Call) RunAndReturn(run func(string, ...http.Header) <-chan *rest.Response) *MockAsyncChanHTTPClient_ChanDelete_Call {
	_c.Call.Return(run)
	return _c
}

// ChanDeleteWithContext provides a mock function with given fields: ctx, url, headers
func (_m *MockAsyncChanHTTPClient) ChanDeleteWithContext(ctx context.Context, url string, headers ...http.Header) <-chan *rest.Response {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, url)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ChanDeleteWithContext")
	}

	var r0 <-chan *rest.Response
	if rf, ok := ret.Get(0).(func(context.Context, string, ...http.Header) <-chan *rest.Response); ok {
		r0 = rf(ctx, url, headers...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan *rest.Response)
		}
	}

	return r0
}

// MockAsyncChanHTTPClient_ChanDeleteWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChanDeleteWithContext'
type MockAsyncChanHTTPClient_ChanDeleteWithContext_Call struct {
	*mock.Call
}

// ChanDeleteWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - headers ...http.Header
func (_e *MockAsyncChanHTTPClient_Expecter) ChanDeleteWithContext(ctx interface{}, url interface{}, headers ...interface{}) *MockAsyncChanHTTPClient_ChanDeleteWithContext_Call {
	return &MockAsyncChanHTTPClient_ChanDeleteWithContext_Call{Call: _e.mock.On("ChanDeleteWithContext",
		append([]interface{}{ctx, url}, headers...)...)}
}

func (_c *MockAsyncChanHTTPClient_ChanDeleteWithContext_Call) Run(run func(ctx context.Context, url string, headers ...http.Header)) *MockAsyncChanHTTPClient_ChanDeleteWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockAsyncChanHTTPClient_ChanDeleteWithContext_Call) Return(_a0 <-chan *rest.Response) *MockAsyncChanHTTPClient_ChanDeleteWithContext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAsyncChanHTTPClient_ChanDeleteWithContext_Call) RunAndReturn(run func(context.Context, string, ...http.Header) <-chan *rest.Response) *MockAsyncChanHTTPClient_ChanDeleteWithContext_Call {
	_c.Call.Return(run)
	return _c
}

// ChanGet provides a mock function with given fields: url, headers
func (_m *MockAsyncChanHTTPClient) ChanGet(url string, headers ...http.Header) <-chan *rest.Response {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, url)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ChanGet")
	}

	var r0 <-chan *rest.Response
	if rf, ok := ret.Get(0).(func(string, ...http.Header) <-chan *rest.Response); ok {
		r0 = rf(url, headers...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan *rest.Response)
		}
	}

	return r0
}

// MockAsyncChanHTTPClient_ChanGet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChanGet'
type MockAsyncChanHTTPClient_ChanGet_Call struct {
	*mock.Call
}

// ChanGet is a helper method to define mock.On call
//   - url string
//   - headers ...http.Header
func (_e *MockAsyncChanHTTPClient_Expecter) ChanGet(url interface{}, headers ...interface{}) *MockAsyncChanHTTPClient_ChanGet_Call {
	return &MockAsyncChanHTTPClient_ChanGet_Call{Call: _e.mock.On("ChanGet",
		append([]interface{}{url}, headers...)...)}
}

func (_c *MockAsyncChanHTTPClient_ChanGet_Call) Run(run func(url string, headers ...http.Header)) *MockAsyncChanHTTPClient_ChanGet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockAsyncChanHTTPClient_ChanGet_Call) Return(_a0 <-chan *rest.Response) *MockAsyncChanHTTPClient_ChanGet_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAsyncChanHTTPClient_ChanGet_Call) RunAndReturn(run func(string, ...http.Header) <-chan *rest.Response) *MockAsyncChanHTTPClient_ChanGet_Call {
	_c.Call.Return(run)
	return _c
}

// ChanGetWithContext provides a mock function with given fields: ctx, url, headers
func (_m *MockAsyncChanHTTPClient) ChanGetWithContext(ctx context.Context, url string, headers ...http.Header) <-chan *rest.Response {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, url)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ChanGetWithContext")
	}

	var r0 <-chan *rest.Response
	if rf, ok := ret.Get(0).(func(context.Context, string, ...http.Header) <-chan *rest.Response); ok {
		r0 = rf(ctx, url, headers...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan *rest.Response)
		}
	}

	return r0
}

// MockAsyncChanHTTPClient_ChanGetWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChanGetWithContext'
type MockAsyncChanHTTPClient_ChanGetWithContext_Call struct {
	*mock.Call
}

// ChanGetWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - headers ...http.Header
func (_e *MockAsyncChanHTTPClient_Expecter) ChanGetWithContext(ctx interface{}, url interface{}, headers ...interface{}) *MockAsyncChanHTTPClient_ChanGetWithContext_Call {
	return &MockAsyncChanHTTPClient_ChanGetWithContext_Call{Call: _e.mock.On("ChanGetWithContext",
		append([]interface{}{ctx, url}, headers...)...)}
}

func (_c *MockAsyncChanHTTPClient_ChanGetWithContext_Call) Run(run func(ctx context.Context, url string, headers ...http.Header)) *MockAsyncChanHTTPClient_ChanGetWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockAsyncChanHTTPClient_ChanGetWithContext_Call) Return(_a0 <-chan *rest.Response) *MockAsyncChanHTTPClient_ChanGetWithContext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAsyncChanHTTPClient_ChanGetWithContext_Call) RunAndReturn(run func(context.Context, string, ...http.Header) <-chan *rest.Response) *MockAsyncChanHTTPClient_ChanGetWithContext_Call {
	_c.Call.Return(run)
	return _c
}

// ChanHead provides a mock function with given fields: url, headers
func (_m *MockAsyncChanHTTPClient) ChanHead(url string, headers ...http.Header) <-chan *rest.Response {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, url)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ChanHead")
	}

	var r0 <-chan *rest.Response
	if rf, ok := ret.Get(0).(func(string, ...http.Header) <-chan *rest.Response); ok {
		r0 = rf(url, headers...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan *rest.Response)
		}
	}

	return r0
}

// MockAsyncChanHTTPClient_ChanHead_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChanHead'
type MockAsyncChanHTTPClient_ChanHead_Call struct {
	*mock.Call
}

// ChanHead is a helper method to define mock.On call
//   - url string
//   - headers ...http.Header
func (_e *MockAsyncChanHTTPClient_Expecter) ChanHead(url interface{}, headers ...interface{}) *MockAsyncChanHTTPClient_ChanHead_Call {
	return &MockAsyncChanHTTPClient_ChanHead_Call{Call: _e.mock.On("ChanHead",
		append([]interface{}{url}, headers...)...)}
}

func (_c *MockAsyncChanHTTPClient_ChanHead_Call) Run(run func(url string, headers ...http.Header)) *MockAsyncChanHTTPClient_ChanHead_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockAsyncChanHTTPClient_ChanHead_Call) Return(_a0 <-chan *rest.Response) *MockAsyncChanHTTPClient_ChanHead_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAsyncChanHTTPClient_ChanHead_Call) RunAndReturn(run func(string, ...http.Header) <-chan *rest.Response) *MockAsyncChanHTTPClient_ChanHead_Call {
	_c.Call.Return(run)
	return _c
}

// ChanHeadWithContext provides a mock function with given fields: ctx, url, headers
func (_m *MockAsyncChanHTTPClient) ChanHeadWithContext(ctx context.Context, url string, headers ...http.Header) <-chan *rest.Response {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, url)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ChanHeadWithContext")
	}

	var r0 <-chan *rest.Response
	if rf, ok := ret.Get(0).(func(context.Context, string, ...http.Header) <-chan *rest.Response); ok {
		r0 = rf(ctx, url, headers...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan *rest.Response)
		}
	}

	return r0
}

// MockAsyncChanHTTPClient_ChanHeadWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChanHeadWithContext'
type MockAsyncChanHTTPClient_ChanHeadWithContext_Call struct {
	*mock.Call
}

// ChanHeadWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - headers ...http.Header
func (_e *MockAsyncChanHTTPClient_Expecter) ChanHeadWithContext(ctx interface{}, url interface{}, headers ...interface{}) *MockAsyncChanHTTPClient_ChanHeadWithContext_Call {
	return &MockAsyncChanHTTPClient_ChanHeadWithContext_Call{Call: _e.mock.On("ChanHeadWithContext",
		append([]interface{}{ctx, url}, headers...)...)}
}

func (_c *MockAsyncChanHTTPClient_ChanHeadWithContext_Call) Run(run func(ctx context.Context, url string, headers ...http.Header)) *MockAsyncChanHTTPClient_ChanHeadWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockAsyncChanHTTPClient_ChanHeadWithContext_Call) Return(_a0 <-chan *rest.Response) *MockAsyncChanHTTPClient_ChanHeadWithContext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAsyncChanHTTPClient_ChanHeadWithContext_Call) RunAndReturn(run func(context.Context, string, ...http.Header) <-chan *rest.Response) *MockAsyncChanHTTPClient_ChanHeadWithContext_Call {
	_c.Call.Return(run)
	return _c
}

// ChanOptions provides a mock function with given fields: url, headers
func (_m *MockAsyncChanHTTPClient) ChanOptions(url string, headers ...http.Header) <-chan *rest.Response {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, url)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ChanOptions")
	}

	var r0 <-chan *rest.Response
	if rf, ok := ret.Get(0).(func(string, ...http.Header) <-chan *rest.Response); ok {
		r0 = rf(url, headers...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan *rest.Response)
		}
	}

	return r0
}

// MockAsyncChanHTTPClient_ChanOptions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChanOptions'
type MockAsyncChanHTTPClient_ChanOptions_Call struct {
	*mock.Call
}

// ChanOptions is a helper method to define mock.On call
//   - url string
//   - headers ...http.Header
func (_e *MockAsyncChanHTTPClient_Expecter) ChanOptions(url interface{}, headers ...interface{}) *MockAsyncChanHTTPClient_ChanOptions_Call {
	return &MockAsyncChanHTTPClient_ChanOptions_Call{Call: _e.mock.On("ChanOptions",
		append([]interface{}{url}, headers...)...)}
}

func (_c *MockAsyncChanHTTPClient_ChanOptions_Call) Run(run func(url string, headers ...http.Header)) *MockAsyncChanHTTPClient_ChanOptions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockAsyncChanHTTPClient_ChanOptions_Call) Return(_a0 <-chan *rest.Response) *MockAsyncChanHTTPClient_ChanOptions_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAsyncChanHTTPClient_ChanOptions_Call) RunAndReturn(run func(string, ...http.Header) <-chan *rest.Response) *MockAsyncChanHTTPClient_ChanOptions_Call {
	_c.Call.Return(run)
	return _c
}

// ChanOptionsWithContext provides a mock function with given fields: ctx, url, headers
func (_m *MockAsyncChanHTTPClient) ChanOptionsWithContext(ctx context.Context, url string, headers ...http.Header) <-chan *rest.Response {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, url)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ChanOptionsWithContext")
	}

	var r0 <-chan *rest.Response
	if rf, ok := ret.Get(0).(func(context.Context, string, ...http.Header) <-chan *rest.Response); ok {
		r0 = rf(ctx, url, headers...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan *rest.Response)
		}
	}

	return r0
}

// MockAsyncChanHTTPClient_ChanOptionsWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChanOptionsWithContext'
type MockAsyncChanHTTPClient_ChanOptionsWithContext_Call struct {
	*mock.Call
}

// ChanOptionsWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - headers ...http.Header
func (_e *MockAsyncChanHTTPClient_Expecter) ChanOptionsWithContext(ctx interface{}, url interface{}, headers ...interface{}) *MockAsyncChanHTTPClient_ChanOptionsWithContext_Call {
	return &MockAsyncChanHTTPClient_ChanOptionsWithContext_Call{Call: _e.mock.On("ChanOptionsWithContext",
		append([]interface{}{ctx, url}, headers...)...)}
}

func (_c *MockAsyncChanHTTPClient_ChanOptionsWithContext_Call) Run(run func(ctx context.Context, url string, headers ...http.Header)) *MockAsyncChanHTTPClient_ChanOptionsWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockAsyncChanHTTPClient_ChanOptionsWithContext_Call) Return(_a0 <-chan *rest.Response) *MockAsyncChanHTTPClient_ChanOptionsWithContext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAsyncChanHTTPClient_ChanOptionsWithContext_Call) RunAndReturn(run func(context.Context, string, ...http.Header) <-chan *rest.Response) *MockAsyncChanHTTPClient_ChanOptionsWithContext_Call {
	_c.Call.Return(run)
	return _c
}

// ChanPatch provides a mock function with given fields: url, body, headers
func (_m *MockAsyncChanHTTPClient) ChanPatch(url string, body any, headers ...http.Header) <-chan *rest.Response {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, url, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ChanPatch")
	}

	var r0 <-chan *rest.Response
	if rf, ok := ret.Get(0).(func(string, any, ...http.Header) <-chan *rest.Response); ok {
		r0 = rf(url, body, headers...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan *rest.Response)
		}
	}

	return r0
}

// MockAsyncChanHTTPClient_ChanPatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChanPatch'
type MockAsyncChanHTTPClient_ChanPatch_Call struct {
	*mock.Call
}

// ChanPatch is a helper method to define mock.On call
//   - url string
//   - body any
//   - headers ...http.Header
func (_e *MockAsyncChanHTTPClient_Expecter) ChanPatch(url interface{}, body interface{}, headers ...interface{}) *MockAsyncChanHTTPClient_ChanPatch_Call {
	return &MockAsyncChanHTTPClient_ChanPatch_Call{Call: _e.mock.On("ChanPatch",
		append([]interface{}{url, body}, headers...)...)}
}

func (_c *MockAsyncChanHTTPClient_ChanPatch_Call) Run(run func(url string, body any, headers ...http.Header)) *MockAsyncChanHTTPClient_ChanPatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(string), args[1].(any), variadicArgs...)
	})
	return _c
}

func (_c *MockAsyncChanHTTPClient_ChanPatch_Call) Return(_a0 <-chan *rest.Response) *MockAsyncChanHTTPClient_ChanPatch_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAsyncChanHTTPClient_ChanPatch_Call) RunAndReturn(run func(string, any, ...http.Header) <-chan *rest.Response) *MockAsyncChanHTTPClient_ChanPatch_Call {
	_c.Call.Return(run)
	return _c
}

// ChanPatchWithContext provides a mock function with given fields: ctx, url, body, headers
func (_m *MockAsyncChanHTTPClient) ChanPatchWithContext(ctx context.Context, url string, body any, headers ...http.Header) <-chan *rest.Response {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, url, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ChanPatchWithContext")
	}

	var r0 <-chan *rest.Response
	if rf, ok := ret.Get(0).(func(context.Context, string, any, ...http.Header) <-chan *rest.Response); ok {
		r0 = rf(ctx, url, body, headers...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan *rest.Response)
		}
	}

	return r0
}

// MockAsyncChanHTTPClient_ChanPatchWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChanPatchWithContext'
type MockAsyncChanHTTPClient_ChanPatchWithContext_Call struct {
	*mock.Call
}

// ChanPatchWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - body any
//   - headers ...http.Header
func (_e *MockAsyncChanHTTPClient_Expecter) ChanPatchWithContext(ctx interface{}, url interface{}, body interface{}, headers ...interface{}) *MockAsyncChanHTTPClient_ChanPatchWithContext_Call {
	return &MockAsyncChanHTTPClient_ChanPatchWithContext_Call{Call: _e.mock.On("ChanPatchWithContext",
		append([]interface{}{ctx, url, body}, headers...)...)}
}

func (_c *MockAsyncChanHTTPClient_ChanPatchWithContext_Call) Run(run func(ctx context.Context, url string, body any, headers ...http.Header)) *MockAsyncChanHTTPClient_ChanPatchWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(any), variadicArgs...)
	})
	return _c
}

func (_c *MockAsyncChanHTTPClient_ChanPatchWithContext_Call) Return(_a0 <-chan *rest.Response) *MockAsyncChanHTTPClient_ChanPatchWithContext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAsyncChanHTTPClient_ChanPatchWithContext_Call) RunAndReturn(run func(context.Context, string, any, ...http.Header) <-chan *rest.Response) *MockAsyncChanHTTPClient_ChanPatchWithContext_Call {
	_c.Call.Return(run)
	return _c
}

// ChanPost provides a mock function with given fields: url, body, headers
func (_m *MockAsyncChanHTTPClient) ChanPost(url string, body any, headers ...http.Header) <-chan *rest.Response {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, url, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ChanPost")
	}

	var r0 <-chan *rest.Response
	if rf, ok := ret.Get(0).(func(string, any, ...http.Header) <-chan *rest.Response); ok {
		r0 = rf(url, body, headers...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan *rest.Response)
		}
	}

	return r0
}

// MockAsyncChanHTTPClient_ChanPost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChanPost'
type MockAsyncChanHTTPClient_ChanPost_Call struct {
	*mock.Call
}

// ChanPost is a helper method to define mock.On call
//   - url string
//   - body any
//   - headers ...http.Header
func (_e *MockAsyncChanHTTPClient_Expecter) ChanPost(url interface{}, body interface{}, headers ...interface{}) *MockAsyncChanHTTPClient_ChanPost_Call {
	return &MockAsyncChanHTTPClient_ChanPost_Call{Call: _e.mock.On("ChanPost",
		append([]interface{}{url, body}, headers...)...)}
}

func (_c *MockAsyncChanHTTPClient_ChanPost_Call) Run(run func(url string, body any, headers ...http.Header)) *MockAsyncChanHTTPClient_ChanPost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(string), args[1].(any), variadicArgs...)
	})
	return _c
}

func (_c *MockAsyncChanHTTPClient_ChanPost_Call) Return(_a0 <-chan *rest.Response) *MockAsyncChanHTTPClient_ChanPost_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAsyncChanHTTPClient_ChanPost_Call) RunAndReturn(run func(string, any, ...http.Header) <-chan *rest.Response) *MockAsyncChanHTTPClient_ChanPost_Call {
	_c.Call.Return(run)
	return _c
}

// ChanPostWithContext provides a mock function with given fields: ctx, url, body, headers
func (_m *MockAsyncChanHTTPClient) ChanPostWithContext(ctx context.Context, url string, body any, headers ...http.Header) <-chan *rest.Response {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, url, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ChanPostWithContext")
	}

	var r0 <-chan *rest.Response
	if rf, ok := ret.Get(0).(func(context.Context, string, any, ...http.Header) <-chan *rest.Response); ok {
		r0 = rf(ctx, url, body, headers...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan *rest.Response)
		}
	}

	return r0
}

// MockAsyncChanHTTPClient_ChanPostWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChanPostWithContext'
type MockAsyncChanHTTPClient_ChanPostWithContext_Call struct {
	*mock.Call
}

// ChanPostWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - body any
//   - headers ...http.Header
func (_e *MockAsyncChanHTTPClient_Expecter) ChanPostWithContext(ctx interface{}, url interface{}, body interface{}, headers ...interface{}) *MockAsyncChanHTTPClient_ChanPostWithContext_Call {
	return &MockAsyncChanHTTPClient_ChanPostWithContext_Call{Call: _e.mock.On("ChanPostWithContext",
		append([]interface{}{ctx, url, body}, headers...)...)}
}

func (_c *MockAsyncChanHTTPClient_ChanPostWithContext_Call) Run(run func(ctx context.Context, url string, body any, headers ...http.Header)) *MockAsyncChanHTTPClient_ChanPostWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(any), variadicArgs...)
	})
	return _c
}

func (_c *MockAsyncChanHTTPClient_ChanPostWithContext_Call) Return(_a0 <-chan *rest.Response) *MockAsyncChanHTTPClient_ChanPostWithContext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAsyncChanHTTPClient_ChanPostWithContext_Call) RunAndReturn(run func(context.Context, string, any, ...http.Header) <-chan *rest.Response) *MockAsyncChanHTTPClient_ChanPostWithContext_Call {
	_c.Call.Return(run)
	return _c
}

// ChanPut provides a mock function with given fields: url, body, headers
func (_m *MockAsyncChanHTTPClient) ChanPut(url string, body any, headers ...http.Header) <-chan *rest.Response {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, url, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ChanPut")
	}

	var r0 <-chan *rest.Response
	if rf, ok := ret.Get(0).(func(string, any, ...http.Header) <-chan *rest.Response); ok {
		r0 = rf(url, body, headers...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan *rest.Response)
		}
	}

	return r0
}

// MockAsyncChanHTTPClient_ChanPut_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChanPut'
type MockAsyncChanHTTPClient_ChanPut_Call struct {
	*mock.Call
}

// ChanPut is a helper method to define mock.On call
//   - url string
//   - body any
//   - headers ...http.Header
func (_e *MockAsyncChanHTTPClient_Expecter) ChanPut(url interface{}, body interface{}, headers ...interface{}) *MockAsyncChanHTTPClient_ChanPut_Call {
	return &MockAsyncChanHTTPClient_ChanPut_Call{Call: _e.mock.On("ChanPut",
		append([]interface{}{url, body}, headers...)...)}
}

func (_c *MockAsyncChanHTTPClient_ChanPut_Call) Run(run func(url string, body any, headers ...http.Header)) *MockAsyncChanHTTPClient_ChanPut_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(string), args[1].(any), variadicArgs...)
	})
	return _c
}

func (_c *MockAsyncChanHTTPClient_ChanPut_Call) Return(_a0 <-chan *rest.Response) *MockAsyncChanHTTPClient_ChanPut_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAsyncChanHTTPClient_ChanPut_Call) RunAndReturn(run func(string, any, ...http.Header) <-chan *rest.Response) *MockAsyncChanHTTPClient_ChanPut_Call {
	_c.Call.Return(run)
	return _c
}

// ChanPutWithContext provides a mock function with given fields: ctx, url, body, headers
func (_m *MockAsyncChanHTTPClient) ChanPutWithContext(ctx context.Context, url string, body any, headers ...http.Header) <-chan *rest.Response {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, url, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ChanPutWithContext")
	}

	var r0 <-chan *rest.Response
	if rf, ok := ret.Get(0).(func(context.Context, string, any, ...http.Header) <-chan *rest.Response); ok {
		r0 = rf(ctx, url, body, headers...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan *rest.Response)
		}
	}

	return r0
}

// MockAsyncChanHTTPClient_ChanPutWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChanPutWithContext'
type MockAsyncChanHTTPClient_ChanPutWithContext_Call struct {
	*mock.Call
}

// ChanPutWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - body any
//   - headers ...http.Header
func (_e *MockAsyncChanHTTPClient_Expecter) ChanPutWithContext(ctx interface{}, url interface{}, body interface{}, headers ...interface{}) *MockAsyncChanHTTPClient_ChanPutWithContext_Call {
	return &MockAsyncChanHTTPClient_ChanPutWithContext_Call{Call: _e.mock.On("ChanPutWithContext",
		append([]interface{}{ctx, url, body}, headers...)...)}
}

func (_c *MockAsyncChanHTTPClient_ChanPutWithContext_Call) Run(run func(ctx context.Context, url string, body any, headers ...http.Header)) *MockAsyncChanHTTPClient_ChanPutWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(any), variadicArgs...)
	})
	return _c
}

func (_c *MockAsyncChanHTTPClient_ChanPutWithContext_Call) Return(_a0 <-chan *rest.Response) *MockAsyncChanHTTPClient_ChanPutWithContext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAsyncChanHTTPClient_ChanPutWithContext_Call) RunAndReturn(run func(context.Context, string, any, ...http.Header) <-chan *rest.Response) *MockAsyncChanHTTPClient_ChanPutWithContext_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAsyncChanHTTPClient creates a new instance of MockAsyncChanHTTPClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAsyncChanHTTPClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAsyncChanHTTPClient {
	mock := &MockAsyncChanHTTPClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
