// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// MockMedia is an autogenerated mock type for the Media type
type MockMedia struct {
	mock.Mock
}

type MockMedia_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMedia) EXPECT() *MockMedia_Expecter {
	return &MockMedia_Expecter{mock: &_m.Mock}
}

// Marshal provides a mock function with given fields: body
func (_m *MockMedia) Marshal(body any) (io.Reader, error) {
	ret := _m.Called(body)

	if len(ret) == 0 {
		panic("no return value specified for Marshal")
	}

	var r0 io.Reader
	var r1 error
	if rf, ok := ret.Get(0).(func(any) (io.Reader, error)); ok {
		return rf(body)
	}
	if rf, ok := ret.Get(0).(func(any) io.Reader); ok {
		r0 = rf(body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.Reader)
		}
	}

	if rf, ok := ret.Get(1).(func(any) error); ok {
		r1 = rf(body)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMedia_Marshal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Marshal'
type MockMedia_Marshal_Call struct {
	*mock.Call
}

// Marshal is a helper method to define mock.On call
//   - body any
func (_e *MockMedia_Expecter) Marshal(body interface{}) *MockMedia_Marshal_Call {
	return &MockMedia_Marshal_Call{Call: _e.mock.On("Marshal", body)}
}

func (_c *MockMedia_Marshal_Call) Run(run func(body any)) *MockMedia_Marshal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(any))
	})
	return _c
}

func (_c *MockMedia_Marshal_Call) Return(_a0 io.Reader, _a1 error) *MockMedia_Marshal_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMedia_Marshal_Call) RunAndReturn(run func(any) (io.Reader, error)) *MockMedia_Marshal_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function with given fields:
func (_m *MockMedia) Name() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockMedia_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockMedia_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockMedia_Expecter) Name() *MockMedia_Name_Call {
	return &MockMedia_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockMedia_Name_Call) Run(run func()) *MockMedia_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMedia_Name_Call) Return(_a0 string) *MockMedia_Name_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMedia_Name_Call) RunAndReturn(run func() string) *MockMedia_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Unmarshal provides a mock function with given fields: data, v
func (_m *MockMedia) Unmarshal(data []byte, v any) error {
	ret := _m.Called(data, v)

	if len(ret) == 0 {
		panic("no return value specified for Unmarshal")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]byte, any) error); ok {
		r0 = rf(data, v)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMedia_Unmarshal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unmarshal'
type MockMedia_Unmarshal_Call struct {
	*mock.Call
}

// Unmarshal is a helper method to define mock.On call
//   - data []byte
//   - v any
func (_e *MockMedia_Expecter) Unmarshal(data interface{}, v interface{}) *MockMedia_Unmarshal_Call {
	return &MockMedia_Unmarshal_Call{Call: _e.mock.On("Unmarshal", data, v)}
}

func (_c *MockMedia_Unmarshal_Call) Run(run func(data []byte, v any)) *MockMedia_Unmarshal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte), args[1].(any))
	})
	return _c
}

func (_c *MockMedia_Unmarshal_Call) Return(_a0 error) *MockMedia_Unmarshal_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMedia_Unmarshal_Call) RunAndReturn(run func([]byte, any) error) *MockMedia_Unmarshal_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMedia creates a new instance of MockMedia. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMedia(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMedia {
	mock := &MockMedia{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
