// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	http "net/http"

	mock "github.com/stretchr/testify/mock"

	rest "gitlab.com/iskaypetcom/digital/sre/tools/dev/go-restclient/rest"
)

// MockHTTPClient is an autogenerated mock type for the HTTPClient type
type MockHTTPClient struct {
	mock.Mock
}

type MockHTTPClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHTTPClient) EXPECT() *MockHTTPClient_Expecter {
	return &MockHTTPClient_Expecter{mock: &_m.Mock}
}

// AsyncDelete provides a mock function with given fields: url, f, headers
func (_m *MockHTTPClient) AsyncDelete(url string, f func(*rest.Response), headers ...http.Header) {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, url, f)
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// MockHTTPClient_AsyncDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AsyncDelete'
type MockHTTPClient_AsyncDelete_Call struct {
	*mock.Call
}

// AsyncDelete is a helper method to define mock.On call
//   - url string
//   - f func(*rest.Response)
//   - headers ...http.Header
func (_e *MockHTTPClient_Expecter) AsyncDelete(url interface{}, f interface{}, headers ...interface{}) *MockHTTPClient_AsyncDelete_Call {
	return &MockHTTPClient_AsyncDelete_Call{Call: _e.mock.On("AsyncDelete",
		append([]interface{}{url, f}, headers...)...)}
}

func (_c *MockHTTPClient_AsyncDelete_Call) Run(run func(url string, f func(*rest.Response), headers ...http.Header)) *MockHTTPClient_AsyncDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(string), args[1].(func(*rest.Response)), variadicArgs...)
	})
	return _c
}

func (_c *MockHTTPClient_AsyncDelete_Call) Return() *MockHTTPClient_AsyncDelete_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHTTPClient_AsyncDelete_Call) RunAndReturn(run func(string, func(*rest.Response), ...http.Header)) *MockHTTPClient_AsyncDelete_Call {
	_c.Call.Return(run)
	return _c
}

// AsyncDeleteWithContext provides a mock function with given fields: ctx, url, f, headers
func (_m *MockHTTPClient) AsyncDeleteWithContext(ctx context.Context, url string, f func(*rest.Response), headers ...http.Header) {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, url, f)
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// MockHTTPClient_AsyncDeleteWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AsyncDeleteWithContext'
type MockHTTPClient_AsyncDeleteWithContext_Call struct {
	*mock.Call
}

// AsyncDeleteWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - f func(*rest.Response)
//   - headers ...http.Header
func (_e *MockHTTPClient_Expecter) AsyncDeleteWithContext(ctx interface{}, url interface{}, f interface{}, headers ...interface{}) *MockHTTPClient_AsyncDeleteWithContext_Call {
	return &MockHTTPClient_AsyncDeleteWithContext_Call{Call: _e.mock.On("AsyncDeleteWithContext",
		append([]interface{}{ctx, url, f}, headers...)...)}
}

func (_c *MockHTTPClient_AsyncDeleteWithContext_Call) Run(run func(ctx context.Context, url string, f func(*rest.Response), headers ...http.Header)) *MockHTTPClient_AsyncDeleteWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(func(*rest.Response)), variadicArgs...)
	})
	return _c
}

func (_c *MockHTTPClient_AsyncDeleteWithContext_Call) Return() *MockHTTPClient_AsyncDeleteWithContext_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHTTPClient_AsyncDeleteWithContext_Call) RunAndReturn(run func(context.Context, string, func(*rest.Response), ...http.Header)) *MockHTTPClient_AsyncDeleteWithContext_Call {
	_c.Call.Return(run)
	return _c
}

// AsyncGet provides a mock function with given fields: url, f, headers
func (_m *MockHTTPClient) AsyncGet(url string, f func(*rest.Response), headers ...http.Header) {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, url, f)
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// MockHTTPClient_AsyncGet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AsyncGet'
type MockHTTPClient_AsyncGet_Call struct {
	*mock.Call
}

// AsyncGet is a helper method to define mock.On call
//   - url string
//   - f func(*rest.Response)
//   - headers ...http.Header
func (_e *MockHTTPClient_Expecter) AsyncGet(url interface{}, f interface{}, headers ...interface{}) *MockHTTPClient_AsyncGet_Call {
	return &MockHTTPClient_AsyncGet_Call{Call: _e.mock.On("AsyncGet",
		append([]interface{}{url, f}, headers...)...)}
}

func (_c *MockHTTPClient_AsyncGet_Call) Run(run func(url string, f func(*rest.Response), headers ...http.Header)) *MockHTTPClient_AsyncGet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(string), args[1].(func(*rest.Response)), variadicArgs...)
	})
	return _c
}

func (_c *MockHTTPClient_AsyncGet_Call) Return() *MockHTTPClient_AsyncGet_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHTTPClient_AsyncGet_Call) RunAndReturn(run func(string, func(*rest.Response), ...http.Header)) *MockHTTPClient_AsyncGet_Call {
	_c.Call.Return(run)
	return _c
}

// AsyncGetWithContext provides a mock function with given fields: ctx, url, f, headers
func (_m *MockHTTPClient) AsyncGetWithContext(ctx context.Context, url string, f func(*rest.Response), headers ...http.Header) {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, url, f)
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// MockHTTPClient_AsyncGetWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AsyncGetWithContext'
type MockHTTPClient_AsyncGetWithContext_Call struct {
	*mock.Call
}

// AsyncGetWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - f func(*rest.Response)
//   - headers ...http.Header
func (_e *MockHTTPClient_Expecter) AsyncGetWithContext(ctx interface{}, url interface{}, f interface{}, headers ...interface{}) *MockHTTPClient_AsyncGetWithContext_Call {
	return &MockHTTPClient_AsyncGetWithContext_Call{Call: _e.mock.On("AsyncGetWithContext",
		append([]interface{}{ctx, url, f}, headers...)...)}
}

func (_c *MockHTTPClient_AsyncGetWithContext_Call) Run(run func(ctx context.Context, url string, f func(*rest.Response), headers ...http.Header)) *MockHTTPClient_AsyncGetWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(func(*rest.Response)), variadicArgs...)
	})
	return _c
}

func (_c *MockHTTPClient_AsyncGetWithContext_Call) Return() *MockHTTPClient_AsyncGetWithContext_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHTTPClient_AsyncGetWithContext_Call) RunAndReturn(run func(context.Context, string, func(*rest.Response), ...http.Header)) *MockHTTPClient_AsyncGetWithContext_Call {
	_c.Call.Return(run)
	return _c
}

// AsyncHead provides a mock function with given fields: url, f, headers
func (_m *MockHTTPClient) AsyncHead(url string, f func(*rest.Response), headers ...http.Header) {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, url, f)
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// MockHTTPClient_AsyncHead_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AsyncHead'
type MockHTTPClient_AsyncHead_Call struct {
	*mock.Call
}

// AsyncHead is a helper method to define mock.On call
//   - url string
//   - f func(*rest.Response)
//   - headers ...http.Header
func (_e *MockHTTPClient_Expecter) AsyncHead(url interface{}, f interface{}, headers ...interface{}) *MockHTTPClient_AsyncHead_Call {
	return &MockHTTPClient_AsyncHead_Call{Call: _e.mock.On("AsyncHead",
		append([]interface{}{url, f}, headers...)...)}
}

func (_c *MockHTTPClient_AsyncHead_Call) Run(run func(url string, f func(*rest.Response), headers ...http.Header)) *MockHTTPClient_AsyncHead_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(string), args[1].(func(*rest.Response)), variadicArgs...)
	})
	return _c
}

func (_c *MockHTTPClient_AsyncHead_Call) Return() *MockHTTPClient_AsyncHead_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHTTPClient_AsyncHead_Call) RunAndReturn(run func(string, func(*rest.Response), ...http.Header)) *MockHTTPClient_AsyncHead_Call {
	_c.Call.Return(run)
	return _c
}

// AsyncHeadWithContext provides a mock function with given fields: ctx, url, f, headers
func (_m *MockHTTPClient) AsyncHeadWithContext(ctx context.Context, url string, f func(*rest.Response), headers ...http.Header) {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, url, f)
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// MockHTTPClient_AsyncHeadWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AsyncHeadWithContext'
type MockHTTPClient_AsyncHeadWithContext_Call struct {
	*mock.Call
}

// AsyncHeadWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - f func(*rest.Response)
//   - headers ...http.Header
func (_e *MockHTTPClient_Expecter) AsyncHeadWithContext(ctx interface{}, url interface{}, f interface{}, headers ...interface{}) *MockHTTPClient_AsyncHeadWithContext_Call {
	return &MockHTTPClient_AsyncHeadWithContext_Call{Call: _e.mock.On("AsyncHeadWithContext",
		append([]interface{}{ctx, url, f}, headers...)...)}
}

func (_c *MockHTTPClient_AsyncHeadWithContext_Call) Run(run func(ctx context.Context, url string, f func(*rest.Response), headers ...http.Header)) *MockHTTPClient_AsyncHeadWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(func(*rest.Response)), variadicArgs...)
	})
	return _c
}

func (_c *MockHTTPClient_AsyncHeadWithContext_Call) Return() *MockHTTPClient_AsyncHeadWithContext_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHTTPClient_AsyncHeadWithContext_Call) RunAndReturn(run func(context.Context, string, func(*rest.Response), ...http.Header)) *MockHTTPClient_AsyncHeadWithContext_Call {
	_c.Call.Return(run)
	return _c
}

// AsyncOptions provides a mock function with given fields: url, f, headers
func (_m *MockHTTPClient) AsyncOptions(url string, f func(*rest.Response), headers ...http.Header) {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, url, f)
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// MockHTTPClient_AsyncOptions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AsyncOptions'
type MockHTTPClient_AsyncOptions_Call struct {
	*mock.Call
}

// AsyncOptions is a helper method to define mock.On call
//   - url string
//   - f func(*rest.Response)
//   - headers ...http.Header
func (_e *MockHTTPClient_Expecter) AsyncOptions(url interface{}, f interface{}, headers ...interface{}) *MockHTTPClient_AsyncOptions_Call {
	return &MockHTTPClient_AsyncOptions_Call{Call: _e.mock.On("AsyncOptions",
		append([]interface{}{url, f}, headers...)...)}
}

func (_c *MockHTTPClient_AsyncOptions_Call) Run(run func(url string, f func(*rest.Response), headers ...http.Header)) *MockHTTPClient_AsyncOptions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(string), args[1].(func(*rest.Response)), variadicArgs...)
	})
	return _c
}

func (_c *MockHTTPClient_AsyncOptions_Call) Return() *MockHTTPClient_AsyncOptions_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHTTPClient_AsyncOptions_Call) RunAndReturn(run func(string, func(*rest.Response), ...http.Header)) *MockHTTPClient_AsyncOptions_Call {
	_c.Call.Return(run)
	return _c
}

// AsyncOptionsWithContext provides a mock function with given fields: ctx, url, f, headers
func (_m *MockHTTPClient) AsyncOptionsWithContext(ctx context.Context, url string, f func(*rest.Response), headers ...http.Header) {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, url, f)
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// MockHTTPClient_AsyncOptionsWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AsyncOptionsWithContext'
type MockHTTPClient_AsyncOptionsWithContext_Call struct {
	*mock.Call
}

// AsyncOptionsWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - f func(*rest.Response)
//   - headers ...http.Header
func (_e *MockHTTPClient_Expecter) AsyncOptionsWithContext(ctx interface{}, url interface{}, f interface{}, headers ...interface{}) *MockHTTPClient_AsyncOptionsWithContext_Call {
	return &MockHTTPClient_AsyncOptionsWithContext_Call{Call: _e.mock.On("AsyncOptionsWithContext",
		append([]interface{}{ctx, url, f}, headers...)...)}
}

func (_c *MockHTTPClient_AsyncOptionsWithContext_Call) Run(run func(ctx context.Context, url string, f func(*rest.Response), headers ...http.Header)) *MockHTTPClient_AsyncOptionsWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(func(*rest.Response)), variadicArgs...)
	})
	return _c
}

func (_c *MockHTTPClient_AsyncOptionsWithContext_Call) Return() *MockHTTPClient_AsyncOptionsWithContext_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHTTPClient_AsyncOptionsWithContext_Call) RunAndReturn(run func(context.Context, string, func(*rest.Response), ...http.Header)) *MockHTTPClient_AsyncOptionsWithContext_Call {
	_c.Call.Return(run)
	return _c
}

// AsyncPatch provides a mock function with given fields: url, body, f, headers
func (_m *MockHTTPClient) AsyncPatch(url string, body any, f func(*rest.Response), headers ...http.Header) {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, url, body, f)
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// MockHTTPClient_AsyncPatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AsyncPatch'
type MockHTTPClient_AsyncPatch_Call struct {
	*mock.Call
}

// AsyncPatch is a helper method to define mock.On call
//   - url string
//   - body any
//   - f func(*rest.Response)
//   - headers ...http.Header
func (_e *MockHTTPClient_Expecter) AsyncPatch(url interface{}, body interface{}, f interface{}, headers ...interface{}) *MockHTTPClient_AsyncPatch_Call {
	return &MockHTTPClient_AsyncPatch_Call{Call: _e.mock.On("AsyncPatch",
		append([]interface{}{url, body, f}, headers...)...)}
}

func (_c *MockHTTPClient_AsyncPatch_Call) Run(run func(url string, body any, f func(*rest.Response), headers ...http.Header)) *MockHTTPClient_AsyncPatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(string), args[1].(any), args[2].(func(*rest.Response)), variadicArgs...)
	})
	return _c
}

func (_c *MockHTTPClient_AsyncPatch_Call) Return() *MockHTTPClient_AsyncPatch_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHTTPClient_AsyncPatch_Call) RunAndReturn(run func(string, any, func(*rest.Response), ...http.Header)) *MockHTTPClient_AsyncPatch_Call {
	_c.Call.Return(run)
	return _c
}

// AsyncPatchWithContext provides a mock function with given fields: ctx, url, body, f, headers
func (_m *MockHTTPClient) AsyncPatchWithContext(ctx context.Context, url string, body any, f func(*rest.Response), headers ...http.Header) {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, url, body, f)
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// MockHTTPClient_AsyncPatchWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AsyncPatchWithContext'
type MockHTTPClient_AsyncPatchWithContext_Call struct {
	*mock.Call
}

// AsyncPatchWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - body any
//   - f func(*rest.Response)
//   - headers ...http.Header
func (_e *MockHTTPClient_Expecter) AsyncPatchWithContext(ctx interface{}, url interface{}, body interface{}, f interface{}, headers ...interface{}) *MockHTTPClient_AsyncPatchWithContext_Call {
	return &MockHTTPClient_AsyncPatchWithContext_Call{Call: _e.mock.On("AsyncPatchWithContext",
		append([]interface{}{ctx, url, body, f}, headers...)...)}
}

func (_c *MockHTTPClient_AsyncPatchWithContext_Call) Run(run func(ctx context.Context, url string, body any, f func(*rest.Response), headers ...http.Header)) *MockHTTPClient_AsyncPatchWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-4)
		for i, a := range args[4:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(any), args[3].(func(*rest.Response)), variadicArgs...)
	})
	return _c
}

func (_c *MockHTTPClient_AsyncPatchWithContext_Call) Return() *MockHTTPClient_AsyncPatchWithContext_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHTTPClient_AsyncPatchWithContext_Call) RunAndReturn(run func(context.Context, string, any, func(*rest.Response), ...http.Header)) *MockHTTPClient_AsyncPatchWithContext_Call {
	_c.Call.Return(run)
	return _c
}

// AsyncPost provides a mock function with given fields: url, body, f, headers
func (_m *MockHTTPClient) AsyncPost(url string, body any, f func(*rest.Response), headers ...http.Header) {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, url, body, f)
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// MockHTTPClient_AsyncPost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AsyncPost'
type MockHTTPClient_AsyncPost_Call struct {
	*mock.Call
}

// AsyncPost is a helper method to define mock.On call
//   - url string
//   - body any
//   - f func(*rest.Response)
//   - headers ...http.Header
func (_e *MockHTTPClient_Expecter) AsyncPost(url interface{}, body interface{}, f interface{}, headers ...interface{}) *MockHTTPClient_AsyncPost_Call {
	return &MockHTTPClient_AsyncPost_Call{Call: _e.mock.On("AsyncPost",
		append([]interface{}{url, body, f}, headers...)...)}
}

func (_c *MockHTTPClient_AsyncPost_Call) Run(run func(url string, body any, f func(*rest.Response), headers ...http.Header)) *MockHTTPClient_AsyncPost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(string), args[1].(any), args[2].(func(*rest.Response)), variadicArgs...)
	})
	return _c
}

func (_c *MockHTTPClient_AsyncPost_Call) Return() *MockHTTPClient_AsyncPost_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHTTPClient_AsyncPost_Call) RunAndReturn(run func(string, any, func(*rest.Response), ...http.Header)) *MockHTTPClient_AsyncPost_Call {
	_c.Call.Return(run)
	return _c
}

// AsyncPostWithContext provides a mock function with given fields: ctx, url, body, f, headers
func (_m *MockHTTPClient) AsyncPostWithContext(ctx context.Context, url string, body any, f func(*rest.Response), headers ...http.Header) {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, url, body, f)
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// MockHTTPClient_AsyncPostWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AsyncPostWithContext'
type MockHTTPClient_AsyncPostWithContext_Call struct {
	*mock.Call
}

// AsyncPostWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - body any
//   - f func(*rest.Response)
//   - headers ...http.Header
func (_e *MockHTTPClient_Expecter) AsyncPostWithContext(ctx interface{}, url interface{}, body interface{}, f interface{}, headers ...interface{}) *MockHTTPClient_AsyncPostWithContext_Call {
	return &MockHTTPClient_AsyncPostWithContext_Call{Call: _e.mock.On("AsyncPostWithContext",
		append([]interface{}{ctx, url, body, f}, headers...)...)}
}

func (_c *MockHTTPClient_AsyncPostWithContext_Call) Run(run func(ctx context.Context, url string, body any, f func(*rest.Response), headers ...http.Header)) *MockHTTPClient_AsyncPostWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-4)
		for i, a := range args[4:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(any), args[3].(func(*rest.Response)), variadicArgs...)
	})
	return _c
}

func (_c *MockHTTPClient_AsyncPostWithContext_Call) Return() *MockHTTPClient_AsyncPostWithContext_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHTTPClient_AsyncPostWithContext_Call) RunAndReturn(run func(context.Context, string, any, func(*rest.Response), ...http.Header)) *MockHTTPClient_AsyncPostWithContext_Call {
	_c.Call.Return(run)
	return _c
}

// AsyncPut provides a mock function with given fields: url, body, f, headers
func (_m *MockHTTPClient) AsyncPut(url string, body any, f func(*rest.Response), headers ...http.Header) {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, url, body, f)
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// MockHTTPClient_AsyncPut_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AsyncPut'
type MockHTTPClient_AsyncPut_Call struct {
	*mock.Call
}

// AsyncPut is a helper method to define mock.On call
//   - url string
//   - body any
//   - f func(*rest.Response)
//   - headers ...http.Header
func (_e *MockHTTPClient_Expecter) AsyncPut(url interface{}, body interface{}, f interface{}, headers ...interface{}) *MockHTTPClient_AsyncPut_Call {
	return &MockHTTPClient_AsyncPut_Call{Call: _e.mock.On("AsyncPut",
		append([]interface{}{url, body, f}, headers...)...)}
}

func (_c *MockHTTPClient_AsyncPut_Call) Run(run func(url string, body any, f func(*rest.Response), headers ...http.Header)) *MockHTTPClient_AsyncPut_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(string), args[1].(any), args[2].(func(*rest.Response)), variadicArgs...)
	})
	return _c
}

func (_c *MockHTTPClient_AsyncPut_Call) Return() *MockHTTPClient_AsyncPut_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHTTPClient_AsyncPut_Call) RunAndReturn(run func(string, any, func(*rest.Response), ...http.Header)) *MockHTTPClient_AsyncPut_Call {
	_c.Call.Return(run)
	return _c
}

// AsyncPutWithContext provides a mock function with given fields: ctx, url, body, f, headers
func (_m *MockHTTPClient) AsyncPutWithContext(ctx context.Context, url string, body any, f func(*rest.Response), headers ...http.Header) {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, url, body, f)
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// MockHTTPClient_AsyncPutWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AsyncPutWithContext'
type MockHTTPClient_AsyncPutWithContext_Call struct {
	*mock.Call
}

// AsyncPutWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - body any
//   - f func(*rest.Response)
//   - headers ...http.Header
func (_e *MockHTTPClient_Expecter) AsyncPutWithContext(ctx interface{}, url interface{}, body interface{}, f interface{}, headers ...interface{}) *MockHTTPClient_AsyncPutWithContext_Call {
	return &MockHTTPClient_AsyncPutWithContext_Call{Call: _e.mock.On("AsyncPutWithContext",
		append([]interface{}{ctx, url, body, f}, headers...)...)}
}

func (_c *MockHTTPClient_AsyncPutWithContext_Call) Run(run func(ctx context.Context, url string, body any, f func(*rest.Response), headers ...http.Header)) *MockHTTPClient_AsyncPutWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-4)
		for i, a := range args[4:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(any), args[3].(func(*rest.Response)), variadicArgs...)
	})
	return _c
}

func (_c *MockHTTPClient_AsyncPutWithContext_Call) Return() *MockHTTPClient_AsyncPutWithContext_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHTTPClient_AsyncPutWithContext_Call) RunAndReturn(run func(context.Context, string, any, func(*rest.Response), ...http.Header)) *MockHTTPClient_AsyncPutWithContext_Call {
	_c.Call.Return(run)
	return _c
}

// ChanDelete provides a mock function with given fields: url, headers
func (_m *MockHTTPClient) ChanDelete(url string, headers ...http.Header) <-chan *rest.Response {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, url)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ChanDelete")
	}

	var r0 <-chan *rest.Response
	if rf, ok := ret.Get(0).(func(string, ...http.Header) <-chan *rest.Response); ok {
		r0 = rf(url, headers...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan *rest.Response)
		}
	}

	return r0
}

// MockHTTPClient_ChanDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChanDelete'
type MockHTTPClient_ChanDelete_Call struct {
	*mock.Call
}

// ChanDelete is a helper method to define mock.On call
//   - url string
//   - headers ...http.Header
func (_e *MockHTTPClient_Expecter) ChanDelete(url interface{}, headers ...interface{}) *MockHTTPClient_ChanDelete_Call {
	return &MockHTTPClient_ChanDelete_Call{Call: _e.mock.On("ChanDelete",
		append([]interface{}{url}, headers...)...)}
}

func (_c *MockHTTPClient_ChanDelete_Call) Run(run func(url string, headers ...http.Header)) *MockHTTPClient_ChanDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockHTTPClient_ChanDelete_Call) Return(_a0 <-chan *rest.Response) *MockHTTPClient_ChanDelete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHTTPClient_ChanDelete_Call) RunAndReturn(run func(string, ...http.Header) <-chan *rest.Response) *MockHTTPClient_ChanDelete_Call {
	_c.Call.Return(run)
	return _c
}

// ChanDeleteWithContext provides a mock function with given fields: ctx, url, headers
func (_m *MockHTTPClient) ChanDeleteWithContext(ctx context.Context, url string, headers ...http.Header) <-chan *rest.Response {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, url)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ChanDeleteWithContext")
	}

	var r0 <-chan *rest.Response
	if rf, ok := ret.Get(0).(func(context.Context, string, ...http.Header) <-chan *rest.Response); ok {
		r0 = rf(ctx, url, headers...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan *rest.Response)
		}
	}

	return r0
}

// MockHTTPClient_ChanDeleteWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChanDeleteWithContext'
type MockHTTPClient_ChanDeleteWithContext_Call struct {
	*mock.Call
}

// ChanDeleteWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - headers ...http.Header
func (_e *MockHTTPClient_Expecter) ChanDeleteWithContext(ctx interface{}, url interface{}, headers ...interface{}) *MockHTTPClient_ChanDeleteWithContext_Call {
	return &MockHTTPClient_ChanDeleteWithContext_Call{Call: _e.mock.On("ChanDeleteWithContext",
		append([]interface{}{ctx, url}, headers...)...)}
}

func (_c *MockHTTPClient_ChanDeleteWithContext_Call) Run(run func(ctx context.Context, url string, headers ...http.Header)) *MockHTTPClient_ChanDeleteWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockHTTPClient_ChanDeleteWithContext_Call) Return(_a0 <-chan *rest.Response) *MockHTTPClient_ChanDeleteWithContext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHTTPClient_ChanDeleteWithContext_Call) RunAndReturn(run func(context.Context, string, ...http.Header) <-chan *rest.Response) *MockHTTPClient_ChanDeleteWithContext_Call {
	_c.Call.Return(run)
	return _c
}

// ChanGet provides a mock function with given fields: url, headers
func (_m *MockHTTPClient) ChanGet(url string, headers ...http.Header) <-chan *rest.Response {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, url)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ChanGet")
	}

	var r0 <-chan *rest.Response
	if rf, ok := ret.Get(0).(func(string, ...http.Header) <-chan *rest.Response); ok {
		r0 = rf(url, headers...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan *rest.Response)
		}
	}

	return r0
}

// MockHTTPClient_ChanGet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChanGet'
type MockHTTPClient_ChanGet_Call struct {
	*mock.Call
}

// ChanGet is a helper method to define mock.On call
//   - url string
//   - headers ...http.Header
func (_e *MockHTTPClient_Expecter) ChanGet(url interface{}, headers ...interface{}) *MockHTTPClient_ChanGet_Call {
	return &MockHTTPClient_ChanGet_Call{Call: _e.mock.On("ChanGet",
		append([]interface{}{url}, headers...)...)}
}

func (_c *MockHTTPClient_ChanGet_Call) Run(run func(url string, headers ...http.Header)) *MockHTTPClient_ChanGet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockHTTPClient_ChanGet_Call) Return(_a0 <-chan *rest.Response) *MockHTTPClient_ChanGet_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHTTPClient_ChanGet_Call) RunAndReturn(run func(string, ...http.Header) <-chan *rest.Response) *MockHTTPClient_ChanGet_Call {
	_c.Call.Return(run)
	return _c
}

// ChanGetWithContext provides a mock function with given fields: ctx, url, headers
func (_m *MockHTTPClient) ChanGetWithContext(ctx context.Context, url string, headers ...http.Header) <-chan *rest.Response {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, url)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ChanGetWithContext")
	}

	var r0 <-chan *rest.Response
	if rf, ok := ret.Get(0).(func(context.Context, string, ...http.Header) <-chan *rest.Response); ok {
		r0 = rf(ctx, url, headers...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan *rest.Response)
		}
	}

	return r0
}

// MockHTTPClient_ChanGetWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChanGetWithContext'
type MockHTTPClient_ChanGetWithContext_Call struct {
	*mock.Call
}

// ChanGetWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - headers ...http.Header
func (_e *MockHTTPClient_Expecter) ChanGetWithContext(ctx interface{}, url interface{}, headers ...interface{}) *MockHTTPClient_ChanGetWithContext_Call {
	return &MockHTTPClient_ChanGetWithContext_Call{Call: _e.mock.On("ChanGetWithContext",
		append([]interface{}{ctx, url}, headers...)...)}
}

func (_c *MockHTTPClient_ChanGetWithContext_Call) Run(run func(ctx context.Context, url string, headers ...http.Header)) *MockHTTPClient_ChanGetWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockHTTPClient_ChanGetWithContext_Call) Return(_a0 <-chan *rest.Response) *MockHTTPClient_ChanGetWithContext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHTTPClient_ChanGetWithContext_Call) RunAndReturn(run func(context.Context, string, ...http.Header) <-chan *rest.Response) *MockHTTPClient_ChanGetWithContext_Call {
	_c.Call.Return(run)
	return _c
}

// ChanHead provides a mock function with given fields: url, headers
func (_m *MockHTTPClient) ChanHead(url string, headers ...http.Header) <-chan *rest.Response {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, url)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ChanHead")
	}

	var r0 <-chan *rest.Response
	if rf, ok := ret.Get(0).(func(string, ...http.Header) <-chan *rest.Response); ok {
		r0 = rf(url, headers...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan *rest.Response)
		}
	}

	return r0
}

// MockHTTPClient_ChanHead_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChanHead'
type MockHTTPClient_ChanHead_Call struct {
	*mock.Call
}

// ChanHead is a helper method to define mock.On call
//   - url string
//   - headers ...http.Header
func (_e *MockHTTPClient_Expecter) ChanHead(url interface{}, headers ...interface{}) *MockHTTPClient_ChanHead_Call {
	return &MockHTTPClient_ChanHead_Call{Call: _e.mock.On("ChanHead",
		append([]interface{}{url}, headers...)...)}
}

func (_c *MockHTTPClient_ChanHead_Call) Run(run func(url string, headers ...http.Header)) *MockHTTPClient_ChanHead_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockHTTPClient_ChanHead_Call) Return(_a0 <-chan *rest.Response) *MockHTTPClient_ChanHead_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHTTPClient_ChanHead_Call) RunAndReturn(run func(string, ...http.Header) <-chan *rest.Response) *MockHTTPClient_ChanHead_Call {
	_c.Call.Return(run)
	return _c
}

// ChanHeadWithContext provides a mock function with given fields: ctx, url, headers
func (_m *MockHTTPClient) ChanHeadWithContext(ctx context.Context, url string, headers ...http.Header) <-chan *rest.Response {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, url)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ChanHeadWithContext")
	}

	var r0 <-chan *rest.Response
	if rf, ok := ret.Get(0).(func(context.Context, string, ...http.Header) <-chan *rest.Response); ok {
		r0 = rf(ctx, url, headers...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan *rest.Response)
		}
	}

	return r0
}

// MockHTTPClient_ChanHeadWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChanHeadWithContext'
type MockHTTPClient_ChanHeadWithContext_Call struct {
	*mock.Call
}

// ChanHeadWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - headers ...http.Header
func (_e *MockHTTPClient_Expecter) ChanHeadWithContext(ctx interface{}, url interface{}, headers ...interface{}) *MockHTTPClient_ChanHeadWithContext_Call {
	return &MockHTTPClient_ChanHeadWithContext_Call{Call: _e.mock.On("ChanHeadWithContext",
		append([]interface{}{ctx, url}, headers...)...)}
}

func (_c *MockHTTPClient_ChanHeadWithContext_Call) Run(run func(ctx context.Context, url string, headers ...http.Header)) *MockHTTPClient_ChanHeadWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockHTTPClient_ChanHeadWithContext_Call) Return(_a0 <-chan *rest.Response) *MockHTTPClient_ChanHeadWithContext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHTTPClient_ChanHeadWithContext_Call) RunAndReturn(run func(context.Context, string, ...http.Header) <-chan *rest.Response) *MockHTTPClient_ChanHeadWithContext_Call {
	_c.Call.Return(run)
	return _c
}

// ChanOptions provides a mock function with given fields: url, headers
func (_m *MockHTTPClient) ChanOptions(url string, headers ...http.Header) <-chan *rest.Response {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, url)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ChanOptions")
	}

	var r0 <-chan *rest.Response
	if rf, ok := ret.Get(0).(func(string, ...http.Header) <-chan *rest.Response); ok {
		r0 = rf(url, headers...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan *rest.Response)
		}
	}

	return r0
}

// MockHTTPClient_ChanOptions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChanOptions'
type MockHTTPClient_ChanOptions_Call struct {
	*mock.Call
}

// ChanOptions is a helper method to define mock.On call
//   - url string
//   - headers ...http.Header
func (_e *MockHTTPClient_Expecter) ChanOptions(url interface{}, headers ...interface{}) *MockHTTPClient_ChanOptions_Call {
	return &MockHTTPClient_ChanOptions_Call{Call: _e.mock.On("ChanOptions",
		append([]interface{}{url}, headers...)...)}
}

func (_c *MockHTTPClient_ChanOptions_Call) Run(run func(url string, headers ...http.Header)) *MockHTTPClient_ChanOptions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockHTTPClient_ChanOptions_Call) Return(_a0 <-chan *rest.Response) *MockHTTPClient_ChanOptions_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHTTPClient_ChanOptions_Call) RunAndReturn(run func(string, ...http.Header) <-chan *rest.Response) *MockHTTPClient_ChanOptions_Call {
	_c.Call.Return(run)
	return _c
}

// ChanOptionsWithContext provides a mock function with given fields: ctx, url, headers
func (_m *MockHTTPClient) ChanOptionsWithContext(ctx context.Context, url string, headers ...http.Header) <-chan *rest.Response {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, url)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ChanOptionsWithContext")
	}

	var r0 <-chan *rest.Response
	if rf, ok := ret.Get(0).(func(context.Context, string, ...http.Header) <-chan *rest.Response); ok {
		r0 = rf(ctx, url, headers...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan *rest.Response)
		}
	}

	return r0
}

// MockHTTPClient_ChanOptionsWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChanOptionsWithContext'
type MockHTTPClient_ChanOptionsWithContext_Call struct {
	*mock.Call
}

// ChanOptionsWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - headers ...http.Header
func (_e *MockHTTPClient_Expecter) ChanOptionsWithContext(ctx interface{}, url interface{}, headers ...interface{}) *MockHTTPClient_ChanOptionsWithContext_Call {
	return &MockHTTPClient_ChanOptionsWithContext_Call{Call: _e.mock.On("ChanOptionsWithContext",
		append([]interface{}{ctx, url}, headers...)...)}
}

func (_c *MockHTTPClient_ChanOptionsWithContext_Call) Run(run func(ctx context.Context, url string, headers ...http.Header)) *MockHTTPClient_ChanOptionsWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockHTTPClient_ChanOptionsWithContext_Call) Return(_a0 <-chan *rest.Response) *MockHTTPClient_ChanOptionsWithContext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHTTPClient_ChanOptionsWithContext_Call) RunAndReturn(run func(context.Context, string, ...http.Header) <-chan *rest.Response) *MockHTTPClient_ChanOptionsWithContext_Call {
	_c.Call.Return(run)
	return _c
}

// ChanPatch provides a mock function with given fields: url, body, headers
func (_m *MockHTTPClient) ChanPatch(url string, body any, headers ...http.Header) <-chan *rest.Response {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, url, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ChanPatch")
	}

	var r0 <-chan *rest.Response
	if rf, ok := ret.Get(0).(func(string, any, ...http.Header) <-chan *rest.Response); ok {
		r0 = rf(url, body, headers...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan *rest.Response)
		}
	}

	return r0
}

// MockHTTPClient_ChanPatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChanPatch'
type MockHTTPClient_ChanPatch_Call struct {
	*mock.Call
}

// ChanPatch is a helper method to define mock.On call
//   - url string
//   - body any
//   - headers ...http.Header
func (_e *MockHTTPClient_Expecter) ChanPatch(url interface{}, body interface{}, headers ...interface{}) *MockHTTPClient_ChanPatch_Call {
	return &MockHTTPClient_ChanPatch_Call{Call: _e.mock.On("ChanPatch",
		append([]interface{}{url, body}, headers...)...)}
}

func (_c *MockHTTPClient_ChanPatch_Call) Run(run func(url string, body any, headers ...http.Header)) *MockHTTPClient_ChanPatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(string), args[1].(any), variadicArgs...)
	})
	return _c
}

func (_c *MockHTTPClient_ChanPatch_Call) Return(_a0 <-chan *rest.Response) *MockHTTPClient_ChanPatch_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHTTPClient_ChanPatch_Call) RunAndReturn(run func(string, any, ...http.Header) <-chan *rest.Response) *MockHTTPClient_ChanPatch_Call {
	_c.Call.Return(run)
	return _c
}

// ChanPatchWithContext provides a mock function with given fields: ctx, url, body, headers
func (_m *MockHTTPClient) ChanPatchWithContext(ctx context.Context, url string, body any, headers ...http.Header) <-chan *rest.Response {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, url, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ChanPatchWithContext")
	}

	var r0 <-chan *rest.Response
	if rf, ok := ret.Get(0).(func(context.Context, string, any, ...http.Header) <-chan *rest.Response); ok {
		r0 = rf(ctx, url, body, headers...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan *rest.Response)
		}
	}

	return r0
}

// MockHTTPClient_ChanPatchWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChanPatchWithContext'
type MockHTTPClient_ChanPatchWithContext_Call struct {
	*mock.Call
}

// ChanPatchWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - body any
//   - headers ...http.Header
func (_e *MockHTTPClient_Expecter) ChanPatchWithContext(ctx interface{}, url interface{}, body interface{}, headers ...interface{}) *MockHTTPClient_ChanPatchWithContext_Call {
	return &MockHTTPClient_ChanPatchWithContext_Call{Call: _e.mock.On("ChanPatchWithContext",
		append([]interface{}{ctx, url, body}, headers...)...)}
}

func (_c *MockHTTPClient_ChanPatchWithContext_Call) Run(run func(ctx context.Context, url string, body any, headers ...http.Header)) *MockHTTPClient_ChanPatchWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(any), variadicArgs...)
	})
	return _c
}

func (_c *MockHTTPClient_ChanPatchWithContext_Call) Return(_a0 <-chan *rest.Response) *MockHTTPClient_ChanPatchWithContext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHTTPClient_ChanPatchWithContext_Call) RunAndReturn(run func(context.Context, string, any, ...http.Header) <-chan *rest.Response) *MockHTTPClient_ChanPatchWithContext_Call {
	_c.Call.Return(run)
	return _c
}

// ChanPost provides a mock function with given fields: url, body, headers
func (_m *MockHTTPClient) ChanPost(url string, body any, headers ...http.Header) <-chan *rest.Response {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, url, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ChanPost")
	}

	var r0 <-chan *rest.Response
	if rf, ok := ret.Get(0).(func(string, any, ...http.Header) <-chan *rest.Response); ok {
		r0 = rf(url, body, headers...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan *rest.Response)
		}
	}

	return r0
}

// MockHTTPClient_ChanPost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChanPost'
type MockHTTPClient_ChanPost_Call struct {
	*mock.Call
}

// ChanPost is a helper method to define mock.On call
//   - url string
//   - body any
//   - headers ...http.Header
func (_e *MockHTTPClient_Expecter) ChanPost(url interface{}, body interface{}, headers ...interface{}) *MockHTTPClient_ChanPost_Call {
	return &MockHTTPClient_ChanPost_Call{Call: _e.mock.On("ChanPost",
		append([]interface{}{url, body}, headers...)...)}
}

func (_c *MockHTTPClient_ChanPost_Call) Run(run func(url string, body any, headers ...http.Header)) *MockHTTPClient_ChanPost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(string), args[1].(any), variadicArgs...)
	})
	return _c
}

func (_c *MockHTTPClient_ChanPost_Call) Return(_a0 <-chan *rest.Response) *MockHTTPClient_ChanPost_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHTTPClient_ChanPost_Call) RunAndReturn(run func(string, any, ...http.Header) <-chan *rest.Response) *MockHTTPClient_ChanPost_Call {
	_c.Call.Return(run)
	return _c
}

// ChanPostWithContext provides a mock function with given fields: ctx, url, body, headers
func (_m *MockHTTPClient) ChanPostWithContext(ctx context.Context, url string, body any, headers ...http.Header) <-chan *rest.Response {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, url, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ChanPostWithContext")
	}

	var r0 <-chan *rest.Response
	if rf, ok := ret.Get(0).(func(context.Context, string, any, ...http.Header) <-chan *rest.Response); ok {
		r0 = rf(ctx, url, body, headers...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan *rest.Response)
		}
	}

	return r0
}

// MockHTTPClient_ChanPostWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChanPostWithContext'
type MockHTTPClient_ChanPostWithContext_Call struct {
	*mock.Call
}

// ChanPostWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - body any
//   - headers ...http.Header
func (_e *MockHTTPClient_Expecter) ChanPostWithContext(ctx interface{}, url interface{}, body interface{}, headers ...interface{}) *MockHTTPClient_ChanPostWithContext_Call {
	return &MockHTTPClient_ChanPostWithContext_Call{Call: _e.mock.On("ChanPostWithContext",
		append([]interface{}{ctx, url, body}, headers...)...)}
}

func (_c *MockHTTPClient_ChanPostWithContext_Call) Run(run func(ctx context.Context, url string, body any, headers ...http.Header)) *MockHTTPClient_ChanPostWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(any), variadicArgs...)
	})
	return _c
}

func (_c *MockHTTPClient_ChanPostWithContext_Call) Return(_a0 <-chan *rest.Response) *MockHTTPClient_ChanPostWithContext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHTTPClient_ChanPostWithContext_Call) RunAndReturn(run func(context.Context, string, any, ...http.Header) <-chan *rest.Response) *MockHTTPClient_ChanPostWithContext_Call {
	_c.Call.Return(run)
	return _c
}

// ChanPut provides a mock function with given fields: url, body, headers
func (_m *MockHTTPClient) ChanPut(url string, body any, headers ...http.Header) <-chan *rest.Response {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, url, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ChanPut")
	}

	var r0 <-chan *rest.Response
	if rf, ok := ret.Get(0).(func(string, any, ...http.Header) <-chan *rest.Response); ok {
		r0 = rf(url, body, headers...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan *rest.Response)
		}
	}

	return r0
}

// MockHTTPClient_ChanPut_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChanPut'
type MockHTTPClient_ChanPut_Call struct {
	*mock.Call
}

// ChanPut is a helper method to define mock.On call
//   - url string
//   - body any
//   - headers ...http.Header
func (_e *MockHTTPClient_Expecter) ChanPut(url interface{}, body interface{}, headers ...interface{}) *MockHTTPClient_ChanPut_Call {
	return &MockHTTPClient_ChanPut_Call{Call: _e.mock.On("ChanPut",
		append([]interface{}{url, body}, headers...)...)}
}

func (_c *MockHTTPClient_ChanPut_Call) Run(run func(url string, body any, headers ...http.Header)) *MockHTTPClient_ChanPut_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(string), args[1].(any), variadicArgs...)
	})
	return _c
}

func (_c *MockHTTPClient_ChanPut_Call) Return(_a0 <-chan *rest.Response) *MockHTTPClient_ChanPut_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHTTPClient_ChanPut_Call) RunAndReturn(run func(string, any, ...http.Header) <-chan *rest.Response) *MockHTTPClient_ChanPut_Call {
	_c.Call.Return(run)
	return _c
}

// ChanPutWithContext provides a mock function with given fields: ctx, url, body, headers
func (_m *MockHTTPClient) ChanPutWithContext(ctx context.Context, url string, body any, headers ...http.Header) <-chan *rest.Response {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, url, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ChanPutWithContext")
	}

	var r0 <-chan *rest.Response
	if rf, ok := ret.Get(0).(func(context.Context, string, any, ...http.Header) <-chan *rest.Response); ok {
		r0 = rf(ctx, url, body, headers...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan *rest.Response)
		}
	}

	return r0
}

// MockHTTPClient_ChanPutWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChanPutWithContext'
type MockHTTPClient_ChanPutWithContext_Call struct {
	*mock.Call
}

// ChanPutWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - body any
//   - headers ...http.Header
func (_e *MockHTTPClient_Expecter) ChanPutWithContext(ctx interface{}, url interface{}, body interface{}, headers ...interface{}) *MockHTTPClient_ChanPutWithContext_Call {
	return &MockHTTPClient_ChanPutWithContext_Call{Call: _e.mock.On("ChanPutWithContext",
		append([]interface{}{ctx, url, body}, headers...)...)}
}

func (_c *MockHTTPClient_ChanPutWithContext_Call) Run(run func(ctx context.Context, url string, body any, headers ...http.Header)) *MockHTTPClient_ChanPutWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(any), variadicArgs...)
	})
	return _c
}

func (_c *MockHTTPClient_ChanPutWithContext_Call) Return(_a0 <-chan *rest.Response) *MockHTTPClient_ChanPutWithContext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHTTPClient_ChanPutWithContext_Call) RunAndReturn(run func(context.Context, string, any, ...http.Header) <-chan *rest.Response) *MockHTTPClient_ChanPutWithContext_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: url, headers
func (_m *MockHTTPClient) Delete(url string, headers ...http.Header) *rest.Response {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, url)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 *rest.Response
	if rf, ok := ret.Get(0).(func(string, ...http.Header) *rest.Response); ok {
		r0 = rf(url, headers...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rest.Response)
		}
	}

	return r0
}

// MockHTTPClient_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockHTTPClient_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - url string
//   - headers ...http.Header
func (_e *MockHTTPClient_Expecter) Delete(url interface{}, headers ...interface{}) *MockHTTPClient_Delete_Call {
	return &MockHTTPClient_Delete_Call{Call: _e.mock.On("Delete",
		append([]interface{}{url}, headers...)...)}
}

func (_c *MockHTTPClient_Delete_Call) Run(run func(url string, headers ...http.Header)) *MockHTTPClient_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockHTTPClient_Delete_Call) Return(_a0 *rest.Response) *MockHTTPClient_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHTTPClient_Delete_Call) RunAndReturn(run func(string, ...http.Header) *rest.Response) *MockHTTPClient_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteWithContext provides a mock function with given fields: ctx, url, headers
func (_m *MockHTTPClient) DeleteWithContext(ctx context.Context, url string, headers ...http.Header) *rest.Response {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, url)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for DeleteWithContext")
	}

	var r0 *rest.Response
	if rf, ok := ret.Get(0).(func(context.Context, string, ...http.Header) *rest.Response); ok {
		r0 = rf(ctx, url, headers...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rest.Response)
		}
	}

	return r0
}

// MockHTTPClient_DeleteWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteWithContext'
type MockHTTPClient_DeleteWithContext_Call struct {
	*mock.Call
}

// DeleteWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - headers ...http.Header
func (_e *MockHTTPClient_Expecter) DeleteWithContext(ctx interface{}, url interface{}, headers ...interface{}) *MockHTTPClient_DeleteWithContext_Call {
	return &MockHTTPClient_DeleteWithContext_Call{Call: _e.mock.On("DeleteWithContext",
		append([]interface{}{ctx, url}, headers...)...)}
}

func (_c *MockHTTPClient_DeleteWithContext_Call) Run(run func(ctx context.Context, url string, headers ...http.Header)) *MockHTTPClient_DeleteWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockHTTPClient_DeleteWithContext_Call) Return(_a0 *rest.Response) *MockHTTPClient_DeleteWithContext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHTTPClient_DeleteWithContext_Call) RunAndReturn(run func(context.Context, string, ...http.Header) *rest.Response) *MockHTTPClient_DeleteWithContext_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: url, headers
func (_m *MockHTTPClient) Get(url string, headers ...http.Header) *rest.Response {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, url)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *rest.Response
	if rf, ok := ret.Get(0).(func(string, ...http.Header) *rest.Response); ok {
		r0 = rf(url, headers...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rest.Response)
		}
	}

	return r0
}

// MockHTTPClient_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockHTTPClient_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - url string
//   - headers ...http.Header
func (_e *MockHTTPClient_Expecter) Get(url interface{}, headers ...interface{}) *MockHTTPClient_Get_Call {
	return &MockHTTPClient_Get_Call{Call: _e.mock.On("Get",
		append([]interface{}{url}, headers...)...)}
}

func (_c *MockHTTPClient_Get_Call) Run(run func(url string, headers ...http.Header)) *MockHTTPClient_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockHTTPClient_Get_Call) Return(_a0 *rest.Response) *MockHTTPClient_Get_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHTTPClient_Get_Call) RunAndReturn(run func(string, ...http.Header) *rest.Response) *MockHTTPClient_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetWithContext provides a mock function with given fields: ctx, url, headers
func (_m *MockHTTPClient) GetWithContext(ctx context.Context, url string, headers ...http.Header) *rest.Response {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, url)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetWithContext")
	}

	var r0 *rest.Response
	if rf, ok := ret.Get(0).(func(context.Context, string, ...http.Header) *rest.Response); ok {
		r0 = rf(ctx, url, headers...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rest.Response)
		}
	}

	return r0
}

// MockHTTPClient_GetWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWithContext'
type MockHTTPClient_GetWithContext_Call struct {
	*mock.Call
}

// GetWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - headers ...http.Header
func (_e *MockHTTPClient_Expecter) GetWithContext(ctx interface{}, url interface{}, headers ...interface{}) *MockHTTPClient_GetWithContext_Call {
	return &MockHTTPClient_GetWithContext_Call{Call: _e.mock.On("GetWithContext",
		append([]interface{}{ctx, url}, headers...)...)}
}

func (_c *MockHTTPClient_GetWithContext_Call) Run(run func(ctx context.Context, url string, headers ...http.Header)) *MockHTTPClient_GetWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockHTTPClient_GetWithContext_Call) Return(_a0 *rest.Response) *MockHTTPClient_GetWithContext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHTTPClient_GetWithContext_Call) RunAndReturn(run func(context.Context, string, ...http.Header) *rest.Response) *MockHTTPClient_GetWithContext_Call {
	_c.Call.Return(run)
	return _c
}

// Head provides a mock function with given fields: url, headers
func (_m *MockHTTPClient) Head(url string, headers ...http.Header) *rest.Response {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, url)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Head")
	}

	var r0 *rest.Response
	if rf, ok := ret.Get(0).(func(string, ...http.Header) *rest.Response); ok {
		r0 = rf(url, headers...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rest.Response)
		}
	}

	return r0
}

// MockHTTPClient_Head_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Head'
type MockHTTPClient_Head_Call struct {
	*mock.Call
}

// Head is a helper method to define mock.On call
//   - url string
//   - headers ...http.Header
func (_e *MockHTTPClient_Expecter) Head(url interface{}, headers ...interface{}) *MockHTTPClient_Head_Call {
	return &MockHTTPClient_Head_Call{Call: _e.mock.On("Head",
		append([]interface{}{url}, headers...)...)}
}

func (_c *MockHTTPClient_Head_Call) Run(run func(url string, headers ...http.Header)) *MockHTTPClient_Head_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockHTTPClient_Head_Call) Return(_a0 *rest.Response) *MockHTTPClient_Head_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHTTPClient_Head_Call) RunAndReturn(run func(string, ...http.Header) *rest.Response) *MockHTTPClient_Head_Call {
	_c.Call.Return(run)
	return _c
}

// HeadWithContext provides a mock function with given fields: ctx, url, headers
func (_m *MockHTTPClient) HeadWithContext(ctx context.Context, url string, headers ...http.Header) *rest.Response {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, url)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for HeadWithContext")
	}

	var r0 *rest.Response
	if rf, ok := ret.Get(0).(func(context.Context, string, ...http.Header) *rest.Response); ok {
		r0 = rf(ctx, url, headers...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rest.Response)
		}
	}

	return r0
}

// MockHTTPClient_HeadWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HeadWithContext'
type MockHTTPClient_HeadWithContext_Call struct {
	*mock.Call
}

// HeadWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - headers ...http.Header
func (_e *MockHTTPClient_Expecter) HeadWithContext(ctx interface{}, url interface{}, headers ...interface{}) *MockHTTPClient_HeadWithContext_Call {
	return &MockHTTPClient_HeadWithContext_Call{Call: _e.mock.On("HeadWithContext",
		append([]interface{}{ctx, url}, headers...)...)}
}

func (_c *MockHTTPClient_HeadWithContext_Call) Run(run func(ctx context.Context, url string, headers ...http.Header)) *MockHTTPClient_HeadWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockHTTPClient_HeadWithContext_Call) Return(_a0 *rest.Response) *MockHTTPClient_HeadWithContext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHTTPClient_HeadWithContext_Call) RunAndReturn(run func(context.Context, string, ...http.Header) *rest.Response) *MockHTTPClient_HeadWithContext_Call {
	_c.Call.Return(run)
	return _c
}

// Options provides a mock function with given fields: url, headers
func (_m *MockHTTPClient) Options(url string, headers ...http.Header) *rest.Response {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, url)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Options")
	}

	var r0 *rest.Response
	if rf, ok := ret.Get(0).(func(string, ...http.Header) *rest.Response); ok {
		r0 = rf(url, headers...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rest.Response)
		}
	}

	return r0
}

// MockHTTPClient_Options_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Options'
type MockHTTPClient_Options_Call struct {
	*mock.Call
}

// Options is a helper method to define mock.On call
//   - url string
//   - headers ...http.Header
func (_e *MockHTTPClient_Expecter) Options(url interface{}, headers ...interface{}) *MockHTTPClient_Options_Call {
	return &MockHTTPClient_Options_Call{Call: _e.mock.On("Options",
		append([]interface{}{url}, headers...)...)}
}

func (_c *MockHTTPClient_Options_Call) Run(run func(url string, headers ...http.Header)) *MockHTTPClient_Options_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockHTTPClient_Options_Call) Return(_a0 *rest.Response) *MockHTTPClient_Options_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHTTPClient_Options_Call) RunAndReturn(run func(string, ...http.Header) *rest.Response) *MockHTTPClient_Options_Call {
	_c.Call.Return(run)
	return _c
}

// OptionsWithContext provides a mock function with given fields: ctx, url, headers
func (_m *MockHTTPClient) OptionsWithContext(ctx context.Context, url string, headers ...http.Header) *rest.Response {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, url)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for OptionsWithContext")
	}

	var r0 *rest.Response
	if rf, ok := ret.Get(0).(func(context.Context, string, ...http.Header) *rest.Response); ok {
		r0 = rf(ctx, url, headers...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rest.Response)
		}
	}

	return r0
}

// MockHTTPClient_OptionsWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OptionsWithContext'
type MockHTTPClient_OptionsWithContext_Call struct {
	*mock.Call
}

// OptionsWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - headers ...http.Header
func (_e *MockHTTPClient_Expecter) OptionsWithContext(ctx interface{}, url interface{}, headers ...interface{}) *MockHTTPClient_OptionsWithContext_Call {
	return &MockHTTPClient_OptionsWithContext_Call{Call: _e.mock.On("OptionsWithContext",
		append([]interface{}{ctx, url}, headers...)...)}
}

func (_c *MockHTTPClient_OptionsWithContext_Call) Run(run func(ctx context.Context, url string, headers ...http.Header)) *MockHTTPClient_OptionsWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockHTTPClient_OptionsWithContext_Call) Return(_a0 *rest.Response) *MockHTTPClient_OptionsWithContext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHTTPClient_OptionsWithContext_Call) RunAndReturn(run func(context.Context, string, ...http.Header) *rest.Response) *MockHTTPClient_OptionsWithContext_Call {
	_c.Call.Return(run)
	return _c
}

// Patch provides a mock function with given fields: url, body, headers
func (_m *MockHTTPClient) Patch(url string, body any, headers ...http.Header) *rest.Response {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, url, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Patch")
	}

	var r0 *rest.Response
	if rf, ok := ret.Get(0).(func(string, any, ...http.Header) *rest.Response); ok {
		r0 = rf(url, body, headers...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rest.Response)
		}
	}

	return r0
}

// MockHTTPClient_Patch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Patch'
type MockHTTPClient_Patch_Call struct {
	*mock.Call
}

// Patch is a helper method to define mock.On call
//   - url string
//   - body any
//   - headers ...http.Header
func (_e *MockHTTPClient_Expecter) Patch(url interface{}, body interface{}, headers ...interface{}) *MockHTTPClient_Patch_Call {
	return &MockHTTPClient_Patch_Call{Call: _e.mock.On("Patch",
		append([]interface{}{url, body}, headers...)...)}
}

func (_c *MockHTTPClient_Patch_Call) Run(run func(url string, body any, headers ...http.Header)) *MockHTTPClient_Patch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(string), args[1].(any), variadicArgs...)
	})
	return _c
}

func (_c *MockHTTPClient_Patch_Call) Return(_a0 *rest.Response) *MockHTTPClient_Patch_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHTTPClient_Patch_Call) RunAndReturn(run func(string, any, ...http.Header) *rest.Response) *MockHTTPClient_Patch_Call {
	_c.Call.Return(run)
	return _c
}

// PatchWithContext provides a mock function with given fields: ctx, url, body, headers
func (_m *MockHTTPClient) PatchWithContext(ctx context.Context, url string, body any, headers ...http.Header) *rest.Response {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, url, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for PatchWithContext")
	}

	var r0 *rest.Response
	if rf, ok := ret.Get(0).(func(context.Context, string, any, ...http.Header) *rest.Response); ok {
		r0 = rf(ctx, url, body, headers...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rest.Response)
		}
	}

	return r0
}

// MockHTTPClient_PatchWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PatchWithContext'
type MockHTTPClient_PatchWithContext_Call struct {
	*mock.Call
}

// PatchWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - body any
//   - headers ...http.Header
func (_e *MockHTTPClient_Expecter) PatchWithContext(ctx interface{}, url interface{}, body interface{}, headers ...interface{}) *MockHTTPClient_PatchWithContext_Call {
	return &MockHTTPClient_PatchWithContext_Call{Call: _e.mock.On("PatchWithContext",
		append([]interface{}{ctx, url, body}, headers...)...)}
}

func (_c *MockHTTPClient_PatchWithContext_Call) Run(run func(ctx context.Context, url string, body any, headers ...http.Header)) *MockHTTPClient_PatchWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(any), variadicArgs...)
	})
	return _c
}

func (_c *MockHTTPClient_PatchWithContext_Call) Return(_a0 *rest.Response) *MockHTTPClient_PatchWithContext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHTTPClient_PatchWithContext_Call) RunAndReturn(run func(context.Context, string, any, ...http.Header) *rest.Response) *MockHTTPClient_PatchWithContext_Call {
	_c.Call.Return(run)
	return _c
}

// Post provides a mock function with given fields: url, body, headers
func (_m *MockHTTPClient) Post(url string, body any, headers ...http.Header) *rest.Response {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, url, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Post")
	}

	var r0 *rest.Response
	if rf, ok := ret.Get(0).(func(string, any, ...http.Header) *rest.Response); ok {
		r0 = rf(url, body, headers...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rest.Response)
		}
	}

	return r0
}

// MockHTTPClient_Post_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Post'
type MockHTTPClient_Post_Call struct {
	*mock.Call
}

// Post is a helper method to define mock.On call
//   - url string
//   - body any
//   - headers ...http.Header
func (_e *MockHTTPClient_Expecter) Post(url interface{}, body interface{}, headers ...interface{}) *MockHTTPClient_Post_Call {
	return &MockHTTPClient_Post_Call{Call: _e.mock.On("Post",
		append([]interface{}{url, body}, headers...)...)}
}

func (_c *MockHTTPClient_Post_Call) Run(run func(url string, body any, headers ...http.Header)) *MockHTTPClient_Post_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(string), args[1].(any), variadicArgs...)
	})
	return _c
}

func (_c *MockHTTPClient_Post_Call) Return(_a0 *rest.Response) *MockHTTPClient_Post_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHTTPClient_Post_Call) RunAndReturn(run func(string, any, ...http.Header) *rest.Response) *MockHTTPClient_Post_Call {
	_c.Call.Return(run)
	return _c
}

// PostWithContext provides a mock function with given fields: ctx, url, body, headers
func (_m *MockHTTPClient) PostWithContext(ctx context.Context, url string, body any, headers ...http.Header) *rest.Response {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, url, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for PostWithContext")
	}

	var r0 *rest.Response
	if rf, ok := ret.Get(0).(func(context.Context, string, any, ...http.Header) *rest.Response); ok {
		r0 = rf(ctx, url, body, headers...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rest.Response)
		}
	}

	return r0
}

// MockHTTPClient_PostWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostWithContext'
type MockHTTPClient_PostWithContext_Call struct {
	*mock.Call
}

// PostWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - body any
//   - headers ...http.Header
func (_e *MockHTTPClient_Expecter) PostWithContext(ctx interface{}, url interface{}, body interface{}, headers ...interface{}) *MockHTTPClient_PostWithContext_Call {
	return &MockHTTPClient_PostWithContext_Call{Call: _e.mock.On("PostWithContext",
		append([]interface{}{ctx, url, body}, headers...)...)}
}

func (_c *MockHTTPClient_PostWithContext_Call) Run(run func(ctx context.Context, url string, body any, headers ...http.Header)) *MockHTTPClient_PostWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(any), variadicArgs...)
	})
	return _c
}

func (_c *MockHTTPClient_PostWithContext_Call) Return(_a0 *rest.Response) *MockHTTPClient_PostWithContext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHTTPClient_PostWithContext_Call) RunAndReturn(run func(context.Context, string, any, ...http.Header) *rest.Response) *MockHTTPClient_PostWithContext_Call {
	_c.Call.Return(run)
	return _c
}

// Put provides a mock function with given fields: url, body, headers
func (_m *MockHTTPClient) Put(url string, body any, headers ...http.Header) *rest.Response {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, url, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Put")
	}

	var r0 *rest.Response
	if rf, ok := ret.Get(0).(func(string, any, ...http.Header) *rest.Response); ok {
		r0 = rf(url, body, headers...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rest.Response)
		}
	}

	return r0
}

// MockHTTPClient_Put_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Put'
type MockHTTPClient_Put_Call struct {
	*mock.Call
}

// Put is a helper method to define mock.On call
//   - url string
//   - body any
//   - headers ...http.Header
func (_e *MockHTTPClient_Expecter) Put(url interface{}, body interface{}, headers ...interface{}) *MockHTTPClient_Put_Call {
	return &MockHTTPClient_Put_Call{Call: _e.mock.On("Put",
		append([]interface{}{url, body}, headers...)...)}
}

func (_c *MockHTTPClient_Put_Call) Run(run func(url string, body any, headers ...http.Header)) *MockHTTPClient_Put_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(string), args[1].(any), variadicArgs...)
	})
	return _c
}

func (_c *MockHTTPClient_Put_Call) Return(_a0 *rest.Response) *MockHTTPClient_Put_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHTTPClient_Put_Call) RunAndReturn(run func(string, any, ...http.Header) *rest.Response) *MockHTTPClient_Put_Call {
	_c.Call.Return(run)
	return _c
}

// PutWithContext provides a mock function with given fields: ctx, url, body, headers
func (_m *MockHTTPClient) PutWithContext(ctx context.Context, url string, body any, headers ...http.Header) *rest.Response {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, url, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for PutWithContext")
	}

	var r0 *rest.Response
	if rf, ok := ret.Get(0).(func(context.Context, string, any, ...http.Header) *rest.Response); ok {
		r0 = rf(ctx, url, body, headers...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rest.Response)
		}
	}

	return r0
}

// MockHTTPClient_PutWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutWithContext'
type MockHTTPClient_PutWithContext_Call struct {
	*mock.Call
}

// PutWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - body any
//   - headers ...http.Header
func (_e *MockHTTPClient_Expecter) PutWithContext(ctx interface{}, url interface{}, body interface{}, headers ...interface{}) *MockHTTPClient_PutWithContext_Call {
	return &MockHTTPClient_PutWithContext_Call{Call: _e.mock.On("PutWithContext",
		append([]interface{}{ctx, url, body}, headers...)...)}
}

func (_c *MockHTTPClient_PutWithContext_Call) Run(run func(ctx context.Context, url string, body any, headers ...http.Header)) *MockHTTPClient_PutWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(any), variadicArgs...)
	})
	return _c
}

func (_c *MockHTTPClient_PutWithContext_Call) Return(_a0 *rest.Response) *MockHTTPClient_PutWithContext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHTTPClient_PutWithContext_Call) RunAndReturn(run func(context.Context, string, any, ...http.Header) *rest.Response) *MockHTTPClient_PutWithContext_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHTTPClient creates a new instance of MockHTTPClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHTTPClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHTTPClient {
	mock := &MockHTTPClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
