// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	http "net/http"

	mock "github.com/stretchr/testify/mock"

	rest "gitlab.com/iskaypetcom/digital/sre/tools/dev/go-restclient/rest"
)

// MockChanHTTPClient is an autogenerated mock type for the ChanHTTPClient type
type MockChanHTTPClient struct {
	mock.Mock
}

type MockChanHTTPClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChanHTTPClient) EXPECT() *MockChanHTTPClient_Expecter {
	return &MockChanHTTPClient_Expecter{mock: &_m.Mock}
}

// DeleteChan provides a mock function with given fields: url, rChan, headers
func (_m *MockChanHTTPClient) DeleteChan(url string, rChan chan<- *rest.Response, headers ...http.Header) {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, url, rChan)
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// MockChanHTTPClient_DeleteChan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteChan'
type MockChanHTTPClient_DeleteChan_Call struct {
	*mock.Call
}

// DeleteChan is a helper method to define mock.On call
//   - url string
//   - rChan chan<- *rest.Response
//   - headers ...http.Header
func (_e *MockChanHTTPClient_Expecter) DeleteChan(url interface{}, rChan interface{}, headers ...interface{}) *MockChanHTTPClient_DeleteChan_Call {
	return &MockChanHTTPClient_DeleteChan_Call{Call: _e.mock.On("DeleteChan",
		append([]interface{}{url, rChan}, headers...)...)}
}

func (_c *MockChanHTTPClient_DeleteChan_Call) Run(run func(url string, rChan chan<- *rest.Response, headers ...http.Header)) *MockChanHTTPClient_DeleteChan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(string), args[1].(chan<- *rest.Response), variadicArgs...)
	})
	return _c
}

func (_c *MockChanHTTPClient_DeleteChan_Call) Return() *MockChanHTTPClient_DeleteChan_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockChanHTTPClient_DeleteChan_Call) RunAndReturn(run func(string, chan<- *rest.Response, ...http.Header)) *MockChanHTTPClient_DeleteChan_Call {
	_c.Run(run)
	return _c
}

// DeleteChanWithContext provides a mock function with given fields: ctx, url, rChan, headers
func (_m *MockChanHTTPClient) DeleteChanWithContext(ctx context.Context, url string, rChan chan<- *rest.Response, headers ...http.Header) {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, url, rChan)
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// MockChanHTTPClient_DeleteChanWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteChanWithContext'
type MockChanHTTPClient_DeleteChanWithContext_Call struct {
	*mock.Call
}

// DeleteChanWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - rChan chan<- *rest.Response
//   - headers ...http.Header
func (_e *MockChanHTTPClient_Expecter) DeleteChanWithContext(ctx interface{}, url interface{}, rChan interface{}, headers ...interface{}) *MockChanHTTPClient_DeleteChanWithContext_Call {
	return &MockChanHTTPClient_DeleteChanWithContext_Call{Call: _e.mock.On("DeleteChanWithContext",
		append([]interface{}{ctx, url, rChan}, headers...)...)}
}

func (_c *MockChanHTTPClient_DeleteChanWithContext_Call) Run(run func(ctx context.Context, url string, rChan chan<- *rest.Response, headers ...http.Header)) *MockChanHTTPClient_DeleteChanWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(chan<- *rest.Response), variadicArgs...)
	})
	return _c
}

func (_c *MockChanHTTPClient_DeleteChanWithContext_Call) Return() *MockChanHTTPClient_DeleteChanWithContext_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockChanHTTPClient_DeleteChanWithContext_Call) RunAndReturn(run func(context.Context, string, chan<- *rest.Response, ...http.Header)) *MockChanHTTPClient_DeleteChanWithContext_Call {
	_c.Run(run)
	return _c
}

// GetChan provides a mock function with given fields: url, rChan, headers
func (_m *MockChanHTTPClient) GetChan(url string, rChan chan<- *rest.Response, headers ...http.Header) {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, url, rChan)
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// MockChanHTTPClient_GetChan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChan'
type MockChanHTTPClient_GetChan_Call struct {
	*mock.Call
}

// GetChan is a helper method to define mock.On call
//   - url string
//   - rChan chan<- *rest.Response
//   - headers ...http.Header
func (_e *MockChanHTTPClient_Expecter) GetChan(url interface{}, rChan interface{}, headers ...interface{}) *MockChanHTTPClient_GetChan_Call {
	return &MockChanHTTPClient_GetChan_Call{Call: _e.mock.On("GetChan",
		append([]interface{}{url, rChan}, headers...)...)}
}

func (_c *MockChanHTTPClient_GetChan_Call) Run(run func(url string, rChan chan<- *rest.Response, headers ...http.Header)) *MockChanHTTPClient_GetChan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(string), args[1].(chan<- *rest.Response), variadicArgs...)
	})
	return _c
}

func (_c *MockChanHTTPClient_GetChan_Call) Return() *MockChanHTTPClient_GetChan_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockChanHTTPClient_GetChan_Call) RunAndReturn(run func(string, chan<- *rest.Response, ...http.Header)) *MockChanHTTPClient_GetChan_Call {
	_c.Run(run)
	return _c
}

// GetChanWithContext provides a mock function with given fields: ctx, url, rChan, headers
func (_m *MockChanHTTPClient) GetChanWithContext(ctx context.Context, url string, rChan chan<- *rest.Response, headers ...http.Header) {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, url, rChan)
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// MockChanHTTPClient_GetChanWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChanWithContext'
type MockChanHTTPClient_GetChanWithContext_Call struct {
	*mock.Call
}

// GetChanWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - rChan chan<- *rest.Response
//   - headers ...http.Header
func (_e *MockChanHTTPClient_Expecter) GetChanWithContext(ctx interface{}, url interface{}, rChan interface{}, headers ...interface{}) *MockChanHTTPClient_GetChanWithContext_Call {
	return &MockChanHTTPClient_GetChanWithContext_Call{Call: _e.mock.On("GetChanWithContext",
		append([]interface{}{ctx, url, rChan}, headers...)...)}
}

func (_c *MockChanHTTPClient_GetChanWithContext_Call) Run(run func(ctx context.Context, url string, rChan chan<- *rest.Response, headers ...http.Header)) *MockChanHTTPClient_GetChanWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(chan<- *rest.Response), variadicArgs...)
	})
	return _c
}

func (_c *MockChanHTTPClient_GetChanWithContext_Call) Return() *MockChanHTTPClient_GetChanWithContext_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockChanHTTPClient_GetChanWithContext_Call) RunAndReturn(run func(context.Context, string, chan<- *rest.Response, ...http.Header)) *MockChanHTTPClient_GetChanWithContext_Call {
	_c.Run(run)
	return _c
}

// HeadChan provides a mock function with given fields: url, rChan, headers
func (_m *MockChanHTTPClient) HeadChan(url string, rChan chan<- *rest.Response, headers ...http.Header) {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, url, rChan)
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// MockChanHTTPClient_HeadChan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HeadChan'
type MockChanHTTPClient_HeadChan_Call struct {
	*mock.Call
}

// HeadChan is a helper method to define mock.On call
//   - url string
//   - rChan chan<- *rest.Response
//   - headers ...http.Header
func (_e *MockChanHTTPClient_Expecter) HeadChan(url interface{}, rChan interface{}, headers ...interface{}) *MockChanHTTPClient_HeadChan_Call {
	return &MockChanHTTPClient_HeadChan_Call{Call: _e.mock.On("HeadChan",
		append([]interface{}{url, rChan}, headers...)...)}
}

func (_c *MockChanHTTPClient_HeadChan_Call) Run(run func(url string, rChan chan<- *rest.Response, headers ...http.Header)) *MockChanHTTPClient_HeadChan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(string), args[1].(chan<- *rest.Response), variadicArgs...)
	})
	return _c
}

func (_c *MockChanHTTPClient_HeadChan_Call) Return() *MockChanHTTPClient_HeadChan_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockChanHTTPClient_HeadChan_Call) RunAndReturn(run func(string, chan<- *rest.Response, ...http.Header)) *MockChanHTTPClient_HeadChan_Call {
	_c.Run(run)
	return _c
}

// HeadChanWithContext provides a mock function with given fields: ctx, url, rChan, headers
func (_m *MockChanHTTPClient) HeadChanWithContext(ctx context.Context, url string, rChan chan<- *rest.Response, headers ...http.Header) {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, url, rChan)
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// MockChanHTTPClient_HeadChanWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HeadChanWithContext'
type MockChanHTTPClient_HeadChanWithContext_Call struct {
	*mock.Call
}

// HeadChanWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - rChan chan<- *rest.Response
//   - headers ...http.Header
func (_e *MockChanHTTPClient_Expecter) HeadChanWithContext(ctx interface{}, url interface{}, rChan interface{}, headers ...interface{}) *MockChanHTTPClient_HeadChanWithContext_Call {
	return &MockChanHTTPClient_HeadChanWithContext_Call{Call: _e.mock.On("HeadChanWithContext",
		append([]interface{}{ctx, url, rChan}, headers...)...)}
}

func (_c *MockChanHTTPClient_HeadChanWithContext_Call) Run(run func(ctx context.Context, url string, rChan chan<- *rest.Response, headers ...http.Header)) *MockChanHTTPClient_HeadChanWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(chan<- *rest.Response), variadicArgs...)
	})
	return _c
}

func (_c *MockChanHTTPClient_HeadChanWithContext_Call) Return() *MockChanHTTPClient_HeadChanWithContext_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockChanHTTPClient_HeadChanWithContext_Call) RunAndReturn(run func(context.Context, string, chan<- *rest.Response, ...http.Header)) *MockChanHTTPClient_HeadChanWithContext_Call {
	_c.Run(run)
	return _c
}

// OptionsChan provides a mock function with given fields: url, rChan, headers
func (_m *MockChanHTTPClient) OptionsChan(url string, rChan chan<- *rest.Response, headers ...http.Header) {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, url, rChan)
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// MockChanHTTPClient_OptionsChan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OptionsChan'
type MockChanHTTPClient_OptionsChan_Call struct {
	*mock.Call
}

// OptionsChan is a helper method to define mock.On call
//   - url string
//   - rChan chan<- *rest.Response
//   - headers ...http.Header
func (_e *MockChanHTTPClient_Expecter) OptionsChan(url interface{}, rChan interface{}, headers ...interface{}) *MockChanHTTPClient_OptionsChan_Call {
	return &MockChanHTTPClient_OptionsChan_Call{Call: _e.mock.On("OptionsChan",
		append([]interface{}{url, rChan}, headers...)...)}
}

func (_c *MockChanHTTPClient_OptionsChan_Call) Run(run func(url string, rChan chan<- *rest.Response, headers ...http.Header)) *MockChanHTTPClient_OptionsChan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(string), args[1].(chan<- *rest.Response), variadicArgs...)
	})
	return _c
}

func (_c *MockChanHTTPClient_OptionsChan_Call) Return() *MockChanHTTPClient_OptionsChan_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockChanHTTPClient_OptionsChan_Call) RunAndReturn(run func(string, chan<- *rest.Response, ...http.Header)) *MockChanHTTPClient_OptionsChan_Call {
	_c.Run(run)
	return _c
}

// OptionsChanWithContext provides a mock function with given fields: ctx, url, rChan, headers
func (_m *MockChanHTTPClient) OptionsChanWithContext(ctx context.Context, url string, rChan chan<- *rest.Response, headers ...http.Header) {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, url, rChan)
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// MockChanHTTPClient_OptionsChanWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OptionsChanWithContext'
type MockChanHTTPClient_OptionsChanWithContext_Call struct {
	*mock.Call
}

// OptionsChanWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - rChan chan<- *rest.Response
//   - headers ...http.Header
func (_e *MockChanHTTPClient_Expecter) OptionsChanWithContext(ctx interface{}, url interface{}, rChan interface{}, headers ...interface{}) *MockChanHTTPClient_OptionsChanWithContext_Call {
	return &MockChanHTTPClient_OptionsChanWithContext_Call{Call: _e.mock.On("OptionsChanWithContext",
		append([]interface{}{ctx, url, rChan}, headers...)...)}
}

func (_c *MockChanHTTPClient_OptionsChanWithContext_Call) Run(run func(ctx context.Context, url string, rChan chan<- *rest.Response, headers ...http.Header)) *MockChanHTTPClient_OptionsChanWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(chan<- *rest.Response), variadicArgs...)
	})
	return _c
}

func (_c *MockChanHTTPClient_OptionsChanWithContext_Call) Return() *MockChanHTTPClient_OptionsChanWithContext_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockChanHTTPClient_OptionsChanWithContext_Call) RunAndReturn(run func(context.Context, string, chan<- *rest.Response, ...http.Header)) *MockChanHTTPClient_OptionsChanWithContext_Call {
	_c.Run(run)
	return _c
}

// PatchChan provides a mock function with given fields: url, body, rChan, headers
func (_m *MockChanHTTPClient) PatchChan(url string, body any, rChan chan<- *rest.Response, headers ...http.Header) {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, url, body, rChan)
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// MockChanHTTPClient_PatchChan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PatchChan'
type MockChanHTTPClient_PatchChan_Call struct {
	*mock.Call
}

// PatchChan is a helper method to define mock.On call
//   - url string
//   - body any
//   - rChan chan<- *rest.Response
//   - headers ...http.Header
func (_e *MockChanHTTPClient_Expecter) PatchChan(url interface{}, body interface{}, rChan interface{}, headers ...interface{}) *MockChanHTTPClient_PatchChan_Call {
	return &MockChanHTTPClient_PatchChan_Call{Call: _e.mock.On("PatchChan",
		append([]interface{}{url, body, rChan}, headers...)...)}
}

func (_c *MockChanHTTPClient_PatchChan_Call) Run(run func(url string, body any, rChan chan<- *rest.Response, headers ...http.Header)) *MockChanHTTPClient_PatchChan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(string), args[1].(any), args[2].(chan<- *rest.Response), variadicArgs...)
	})
	return _c
}

func (_c *MockChanHTTPClient_PatchChan_Call) Return() *MockChanHTTPClient_PatchChan_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockChanHTTPClient_PatchChan_Call) RunAndReturn(run func(string, any, chan<- *rest.Response, ...http.Header)) *MockChanHTTPClient_PatchChan_Call {
	_c.Run(run)
	return _c
}

// PatchChanWithContext provides a mock function with given fields: ctx, url, body, rChan, headers
func (_m *MockChanHTTPClient) PatchChanWithContext(ctx context.Context, url string, body any, rChan chan<- *rest.Response, headers ...http.Header) {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, url, body, rChan)
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// MockChanHTTPClient_PatchChanWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PatchChanWithContext'
type MockChanHTTPClient_PatchChanWithContext_Call struct {
	*mock.Call
}

// PatchChanWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - body any
//   - rChan chan<- *rest.Response
//   - headers ...http.Header
func (_e *MockChanHTTPClient_Expecter) PatchChanWithContext(ctx interface{}, url interface{}, body interface{}, rChan interface{}, headers ...interface{}) *MockChanHTTPClient_PatchChanWithContext_Call {
	return &MockChanHTTPClient_PatchChanWithContext_Call{Call: _e.mock.On("PatchChanWithContext",
		append([]interface{}{ctx, url, body, rChan}, headers...)...)}
}

func (_c *MockChanHTTPClient_PatchChanWithContext_Call) Run(run func(ctx context.Context, url string, body any, rChan chan<- *rest.Response, headers ...http.Header)) *MockChanHTTPClient_PatchChanWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-4)
		for i, a := range args[4:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(any), args[3].(chan<- *rest.Response), variadicArgs...)
	})
	return _c
}

func (_c *MockChanHTTPClient_PatchChanWithContext_Call) Return() *MockChanHTTPClient_PatchChanWithContext_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockChanHTTPClient_PatchChanWithContext_Call) RunAndReturn(run func(context.Context, string, any, chan<- *rest.Response, ...http.Header)) *MockChanHTTPClient_PatchChanWithContext_Call {
	_c.Run(run)
	return _c
}

// PostChan provides a mock function with given fields: url, body, rChan, headers
func (_m *MockChanHTTPClient) PostChan(url string, body any, rChan chan<- *rest.Response, headers ...http.Header) {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, url, body, rChan)
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// MockChanHTTPClient_PostChan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostChan'
type MockChanHTTPClient_PostChan_Call struct {
	*mock.Call
}

// PostChan is a helper method to define mock.On call
//   - url string
//   - body any
//   - rChan chan<- *rest.Response
//   - headers ...http.Header
func (_e *MockChanHTTPClient_Expecter) PostChan(url interface{}, body interface{}, rChan interface{}, headers ...interface{}) *MockChanHTTPClient_PostChan_Call {
	return &MockChanHTTPClient_PostChan_Call{Call: _e.mock.On("PostChan",
		append([]interface{}{url, body, rChan}, headers...)...)}
}

func (_c *MockChanHTTPClient_PostChan_Call) Run(run func(url string, body any, rChan chan<- *rest.Response, headers ...http.Header)) *MockChanHTTPClient_PostChan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(string), args[1].(any), args[2].(chan<- *rest.Response), variadicArgs...)
	})
	return _c
}

func (_c *MockChanHTTPClient_PostChan_Call) Return() *MockChanHTTPClient_PostChan_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockChanHTTPClient_PostChan_Call) RunAndReturn(run func(string, any, chan<- *rest.Response, ...http.Header)) *MockChanHTTPClient_PostChan_Call {
	_c.Run(run)
	return _c
}

// PostChanWithContext provides a mock function with given fields: ctx, url, body, rChan, headers
func (_m *MockChanHTTPClient) PostChanWithContext(ctx context.Context, url string, body any, rChan chan<- *rest.Response, headers ...http.Header) {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, url, body, rChan)
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// MockChanHTTPClient_PostChanWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostChanWithContext'
type MockChanHTTPClient_PostChanWithContext_Call struct {
	*mock.Call
}

// PostChanWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - body any
//   - rChan chan<- *rest.Response
//   - headers ...http.Header
func (_e *MockChanHTTPClient_Expecter) PostChanWithContext(ctx interface{}, url interface{}, body interface{}, rChan interface{}, headers ...interface{}) *MockChanHTTPClient_PostChanWithContext_Call {
	return &MockChanHTTPClient_PostChanWithContext_Call{Call: _e.mock.On("PostChanWithContext",
		append([]interface{}{ctx, url, body, rChan}, headers...)...)}
}

func (_c *MockChanHTTPClient_PostChanWithContext_Call) Run(run func(ctx context.Context, url string, body any, rChan chan<- *rest.Response, headers ...http.Header)) *MockChanHTTPClient_PostChanWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-4)
		for i, a := range args[4:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(any), args[3].(chan<- *rest.Response), variadicArgs...)
	})
	return _c
}

func (_c *MockChanHTTPClient_PostChanWithContext_Call) Return() *MockChanHTTPClient_PostChanWithContext_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockChanHTTPClient_PostChanWithContext_Call) RunAndReturn(run func(context.Context, string, any, chan<- *rest.Response, ...http.Header)) *MockChanHTTPClient_PostChanWithContext_Call {
	_c.Run(run)
	return _c
}

// PutChan provides a mock function with given fields: url, body, rChan, headers
func (_m *MockChanHTTPClient) PutChan(url string, body any, rChan chan<- *rest.Response, headers ...http.Header) {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, url, body, rChan)
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// MockChanHTTPClient_PutChan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutChan'
type MockChanHTTPClient_PutChan_Call struct {
	*mock.Call
}

// PutChan is a helper method to define mock.On call
//   - url string
//   - body any
//   - rChan chan<- *rest.Response
//   - headers ...http.Header
func (_e *MockChanHTTPClient_Expecter) PutChan(url interface{}, body interface{}, rChan interface{}, headers ...interface{}) *MockChanHTTPClient_PutChan_Call {
	return &MockChanHTTPClient_PutChan_Call{Call: _e.mock.On("PutChan",
		append([]interface{}{url, body, rChan}, headers...)...)}
}

func (_c *MockChanHTTPClient_PutChan_Call) Run(run func(url string, body any, rChan chan<- *rest.Response, headers ...http.Header)) *MockChanHTTPClient_PutChan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(string), args[1].(any), args[2].(chan<- *rest.Response), variadicArgs...)
	})
	return _c
}

func (_c *MockChanHTTPClient_PutChan_Call) Return() *MockChanHTTPClient_PutChan_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockChanHTTPClient_PutChan_Call) RunAndReturn(run func(string, any, chan<- *rest.Response, ...http.Header)) *MockChanHTTPClient_PutChan_Call {
	_c.Run(run)
	return _c
}

// PutChanWithContext provides a mock function with given fields: ctx, url, body, rChan, headers
func (_m *MockChanHTTPClient) PutChanWithContext(ctx context.Context, url string, body any, rChan chan<- *rest.Response, headers ...http.Header) {
	_va := make([]interface{}, len(headers))
	for _i := range headers {
		_va[_i] = headers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, url, body, rChan)
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// MockChanHTTPClient_PutChanWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutChanWithContext'
type MockChanHTTPClient_PutChanWithContext_Call struct {
	*mock.Call
}

// PutChanWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - body any
//   - rChan chan<- *rest.Response
//   - headers ...http.Header
func (_e *MockChanHTTPClient_Expecter) PutChanWithContext(ctx interface{}, url interface{}, body interface{}, rChan interface{}, headers ...interface{}) *MockChanHTTPClient_PutChanWithContext_Call {
	return &MockChanHTTPClient_PutChanWithContext_Call{Call: _e.mock.On("PutChanWithContext",
		append([]interface{}{ctx, url, body, rChan}, headers...)...)}
}

func (_c *MockChanHTTPClient_PutChanWithContext_Call) Run(run func(ctx context.Context, url string, body any, rChan chan<- *rest.Response, headers ...http.Header)) *MockChanHTTPClient_PutChanWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]http.Header, len(args)-4)
		for i, a := range args[4:] {
			if a != nil {
				variadicArgs[i] = a.(http.Header)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(any), args[3].(chan<- *rest.Response), variadicArgs...)
	})
	return _c
}

func (_c *MockChanHTTPClient_PutChanWithContext_Call) Return() *MockChanHTTPClient_PutChanWithContext_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockChanHTTPClient_PutChanWithContext_Call) RunAndReturn(run func(context.Context, string, any, chan<- *rest.Response, ...http.Header)) *MockChanHTTPClient_PutChanWithContext_Call {
	_c.Run(run)
	return _c
}

// NewMockChanHTTPClient creates a new instance of MockChanHTTPClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChanHTTPClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChanHTTPClient {
	mock := &MockChanHTTPClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
