// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockCache is an autogenerated mock type for the Cache type
type MockCache[K any, V any] struct {
	mock.Mock
}

type MockCache_Expecter[K any, V any] struct {
	mock *mock.Mock
}

func (_m *MockCache[K, V]) EXPECT() *MockCache_Expecter[K, V] {
	return &MockCache_Expecter[K, V]{mock: &_m.Mock}
}

// Get provides a mock function with given fields: key
func (_m *MockCache[K, V]) Get(key K) (V, bool) {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 V
	var r1 bool
	if rf, ok := ret.Get(0).(func(K) (V, bool)); ok {
		return rf(key)
	}
	if rf, ok := ret.Get(0).(func(K) V); ok {
		r0 = rf(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(V)
		}
	}

	if rf, ok := ret.Get(1).(func(K) bool); ok {
		r1 = rf(key)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// MockCache_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockCache_Get_Call[K any, V any] struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - key K
func (_e *MockCache_Expecter[K, V]) Get(key interface{}) *MockCache_Get_Call[K, V] {
	return &MockCache_Get_Call[K, V]{Call: _e.mock.On("Get", key)}
}

func (_c *MockCache_Get_Call[K, V]) Run(run func(key K)) *MockCache_Get_Call[K, V] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(K))
	})
	return _c
}

func (_c *MockCache_Get_Call[K, V]) Return(_a0 V, _a1 bool) *MockCache_Get_Call[K, V] {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCache_Get_Call[K, V]) RunAndReturn(run func(K) (V, bool)) *MockCache_Get_Call[K, V] {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function with given fields: key, value, cost
func (_m *MockCache[K, V]) Set(key K, value V, cost int64) bool {
	ret := _m.Called(key, value, cost)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(K, V, int64) bool); ok {
		r0 = rf(key, value, cost)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockCache_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockCache_Set_Call[K any, V any] struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - key K
//   - value V
//   - cost int64
func (_e *MockCache_Expecter[K, V]) Set(key interface{}, value interface{}, cost interface{}) *MockCache_Set_Call[K, V] {
	return &MockCache_Set_Call[K, V]{Call: _e.mock.On("Set", key, value, cost)}
}

func (_c *MockCache_Set_Call[K, V]) Run(run func(key K, value V, cost int64)) *MockCache_Set_Call[K, V] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(K), args[1].(V), args[2].(int64))
	})
	return _c
}

func (_c *MockCache_Set_Call[K, V]) Return(_a0 bool) *MockCache_Set_Call[K, V] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCache_Set_Call[K, V]) RunAndReturn(run func(K, V, int64) bool) *MockCache_Set_Call[K, V] {
	_c.Call.Return(run)
	return _c
}

// SetWithTTL provides a mock function with given fields: key, value, cost, ttl
func (_m *MockCache[K, V]) SetWithTTL(key K, value V, cost int64, ttl time.Duration) bool {
	ret := _m.Called(key, value, cost, ttl)

	if len(ret) == 0 {
		panic("no return value specified for SetWithTTL")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(K, V, int64, time.Duration) bool); ok {
		r0 = rf(key, value, cost, ttl)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockCache_SetWithTTL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetWithTTL'
type MockCache_SetWithTTL_Call[K any, V any] struct {
	*mock.Call
}

// SetWithTTL is a helper method to define mock.On call
//   - key K
//   - value V
//   - cost int64
//   - ttl time.Duration
func (_e *MockCache_Expecter[K, V]) SetWithTTL(key interface{}, value interface{}, cost interface{}, ttl interface{}) *MockCache_SetWithTTL_Call[K, V] {
	return &MockCache_SetWithTTL_Call[K, V]{Call: _e.mock.On("SetWithTTL", key, value, cost, ttl)}
}

func (_c *MockCache_SetWithTTL_Call[K, V]) Run(run func(key K, value V, cost int64, ttl time.Duration)) *MockCache_SetWithTTL_Call[K, V] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(K), args[1].(V), args[2].(int64), args[3].(time.Duration))
	})
	return _c
}

func (_c *MockCache_SetWithTTL_Call[K, V]) Return(_a0 bool) *MockCache_SetWithTTL_Call[K, V] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCache_SetWithTTL_Call[K, V]) RunAndReturn(run func(K, V, int64, time.Duration) bool) *MockCache_SetWithTTL_Call[K, V] {
	_c.Call.Return(run)
	return _c
}

// NewMockCache creates a new instance of MockCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCache[K any, V any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCache[K, V] {
	mock := &MockCache[K, V]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
