// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// MockNamedMedia is an autogenerated mock type for the NamedMedia type
type MockNamedMedia struct {
	mock.Mock
}

type MockNamedMedia_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNamedMedia) EXPECT() *MockNamedMedia_Expecter {
	return &MockNamedMedia_Expecter{mock: &_m.Mock}
}

// DefaultHeaders provides a mock function with given fields:
func (_m *MockNamedMedia) DefaultHeaders() http.Header {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for DefaultHeaders")
	}

	var r0 http.Header
	if rf, ok := ret.Get(0).(func() http.Header); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http.Header)
		}
	}

	return r0
}

// MockNamedMedia_DefaultHeaders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DefaultHeaders'
type MockNamedMedia_DefaultHeaders_Call struct {
	*mock.Call
}

// DefaultHeaders is a helper method to define mock.On call
func (_e *MockNamedMedia_Expecter) DefaultHeaders() *MockNamedMedia_DefaultHeaders_Call {
	return &MockNamedMedia_DefaultHeaders_Call{Call: _e.mock.On("DefaultHeaders")}
}

func (_c *MockNamedMedia_DefaultHeaders_Call) Run(run func()) *MockNamedMedia_DefaultHeaders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNamedMedia_DefaultHeaders_Call) Return(_a0 http.Header) *MockNamedMedia_DefaultHeaders_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNamedMedia_DefaultHeaders_Call) RunAndReturn(run func() http.Header) *MockNamedMedia_DefaultHeaders_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockNamedMedia creates a new instance of MockNamedMedia. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNamedMedia(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNamedMedia {
	mock := &MockNamedMedia{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
