// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// MockMediaUnmarshaler is an autogenerated mock type for the MediaUnmarshaler type
type MockMediaUnmarshaler struct {
	mock.Mock
}

type MockMediaUnmarshaler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMediaUnmarshaler) EXPECT() *MockMediaUnmarshaler_Expecter {
	return &MockMediaUnmarshaler_Expecter{mock: &_m.Mock}
}

// DefaultHeaders provides a mock function with given fields:
func (_m *MockMediaUnmarshaler) DefaultHeaders() http.Header {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for DefaultHeaders")
	}

	var r0 http.Header
	if rf, ok := ret.Get(0).(func() http.Header); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http.Header)
		}
	}

	return r0
}

// MockMediaUnmarshaler_DefaultHeaders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DefaultHeaders'
type MockMediaUnmarshaler_DefaultHeaders_Call struct {
	*mock.Call
}

// DefaultHeaders is a helper method to define mock.On call
func (_e *MockMediaUnmarshaler_Expecter) DefaultHeaders() *MockMediaUnmarshaler_DefaultHeaders_Call {
	return &MockMediaUnmarshaler_DefaultHeaders_Call{Call: _e.mock.On("DefaultHeaders")}
}

func (_c *MockMediaUnmarshaler_DefaultHeaders_Call) Run(run func()) *MockMediaUnmarshaler_DefaultHeaders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMediaUnmarshaler_DefaultHeaders_Call) Return(_a0 http.Header) *MockMediaUnmarshaler_DefaultHeaders_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMediaUnmarshaler_DefaultHeaders_Call) RunAndReturn(run func() http.Header) *MockMediaUnmarshaler_DefaultHeaders_Call {
	_c.Call.Return(run)
	return _c
}

// Unmarshal provides a mock function with given fields: data, v
func (_m *MockMediaUnmarshaler) Unmarshal(data []byte, v any) error {
	ret := _m.Called(data, v)

	if len(ret) == 0 {
		panic("no return value specified for Unmarshal")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]byte, any) error); ok {
		r0 = rf(data, v)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMediaUnmarshaler_Unmarshal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unmarshal'
type MockMediaUnmarshaler_Unmarshal_Call struct {
	*mock.Call
}

// Unmarshal is a helper method to define mock.On call
//   - data []byte
//   - v any
func (_e *MockMediaUnmarshaler_Expecter) Unmarshal(data interface{}, v interface{}) *MockMediaUnmarshaler_Unmarshal_Call {
	return &MockMediaUnmarshaler_Unmarshal_Call{Call: _e.mock.On("Unmarshal", data, v)}
}

func (_c *MockMediaUnmarshaler_Unmarshal_Call) Run(run func(data []byte, v any)) *MockMediaUnmarshaler_Unmarshal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte), args[1].(any))
	})
	return _c
}

func (_c *MockMediaUnmarshaler_Unmarshal_Call) Return(_a0 error) *MockMediaUnmarshaler_Unmarshal_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMediaUnmarshaler_Unmarshal_Call) RunAndReturn(run func([]byte, any) error) *MockMediaUnmarshaler_Unmarshal_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMediaUnmarshaler creates a new instance of MockMediaUnmarshaler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMediaUnmarshaler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMediaUnmarshaler {
	mock := &MockMediaUnmarshaler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
