// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package rest

import (
	"context"
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// NewMockHTTPExporter creates a new instance of MockHTTPExporter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHTTPExporter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHTTPExporter {
	mock := &MockHTTPExporter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHTTPExporter is an autogenerated mock type for the HTTPExporter type
type MockHTTPExporter struct {
	mock.Mock
}

type MockHTTPExporter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHTTPExporter) EXPECT() *MockHTTPExporter_Expecter {
	return &MockHTTPExporter_Expecter{mock: &_m.Mock}
}

// Do provides a mock function for the type MockHTTPExporter
func (_mock *MockHTTPExporter) Do(request *http.Request) (*http.Response, error) {
	ret := _mock.Called(request)

	if len(ret) == 0 {
		panic("no return value specified for Do")
	}

	var r0 *http.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*http.Request) (*http.Response, error)); ok {
		return returnFunc(request)
	}
	if returnFunc, ok := ret.Get(0).(func(*http.Request) *http.Response); ok {
		r0 = returnFunc(request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*http.Request) error); ok {
		r1 = returnFunc(request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHTTPExporter_Do_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Do'
type MockHTTPExporter_Do_Call struct {
	*mock.Call
}

// Do is a helper method to define mock.On call
//   - request *http.Request
func (_e *MockHTTPExporter_Expecter) Do(request interface{}) *MockHTTPExporter_Do_Call {
	return &MockHTTPExporter_Do_Call{Call: _e.mock.On("Do", request)}
}

func (_c *MockHTTPExporter_Do_Call) Run(run func(request *http.Request)) *MockHTTPExporter_Do_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *http.Request
		if args[0] != nil {
			arg0 = args[0].(*http.Request)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHTTPExporter_Do_Call) Return(response *http.Response, err error) *MockHTTPExporter_Do_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockHTTPExporter_Do_Call) RunAndReturn(run func(request *http.Request) (*http.Response, error)) *MockHTTPExporter_Do_Call {
	_c.Call.Return(run)
	return _c
}

// RawClient provides a mock function for the type MockHTTPExporter
func (_mock *MockHTTPExporter) RawClient(ctx context.Context) *http.Client {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for RawClient")
	}

	var r0 *http.Client
	if returnFunc, ok := ret.Get(0).(func(context.Context) *http.Client); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Client)
		}
	}
	return r0
}

// MockHTTPExporter_RawClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RawClient'
type MockHTTPExporter_RawClient_Call struct {
	*mock.Call
}

// RawClient is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockHTTPExporter_Expecter) RawClient(ctx interface{}) *MockHTTPExporter_RawClient_Call {
	return &MockHTTPExporter_RawClient_Call{Call: _e.mock.On("RawClient", ctx)}
}

func (_c *MockHTTPExporter_RawClient_Call) Run(run func(ctx context.Context)) *MockHTTPExporter_RawClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHTTPExporter_RawClient_Call) Return(client *http.Client) *MockHTTPExporter_RawClient_Call {
	_c.Call.Return(client)
	return _c
}

func (_c *MockHTTPExporter_RawClient_Call) RunAndReturn(run func(ctx context.Context) *http.Client) *MockHTTPExporter_RawClient_Call {
	_c.Call.Return(run)
	return _c
}
