{
 "title": "HTTP Clients",
 "tags": [
  "http ",
  "timeout",
  "instrumentation"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "environment", "label": "Environment", "query": "dev,uat,prod" },
   {
    "name": "application",
    "label": "Application",
    "query": {
     "query": "label_values({environment=~\"(?i)($environment)\", service_type=\"http_client\"},application)"
    }
   },
   {
    "name": "client_name",
    "label": "Client name",
    "query": {
     "query": "label_values({environment=~\"(?i)($environment)\", service_type=\"http_client\", application=~\"$application\"},client_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "HTTP time (ms)",
   "type": "timeseries",
   "description": "Average, P95, P99",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "services_dashboard_services_timers{environment=~\"(?i)($environment)\", application=~\"$application\", client_name=~\"$client_name\", service_type=\"http_client\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP connection total errors",
   "type": "timeseries",
   "description": "Network, timeouts, etc.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "increase(services_dashboard_services_counters_total{environment=~\"(?i)($environment)\", application=~\"$application\", client_name=~\"$client_name\", event_type=\"http_connection_error\", event_subtype=\"network\", service_type=\"http_client\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP connection timeout",
   "type": "timeseries",
   "description": "Network, timeouts, etc.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "increase(services_dashboard_services_counters_total{environment=~\"(?i)($environment)\", application=~\"$application\", client_name=~\"$client_name\", event_type=\"http_connection_error\", event_subtype=\"timeout\", service_type=\"http_client\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP 20x",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "increase(services_dashboard_services_counters_total{environment=~\"(?i)($environment)\", application=~\"$application\", client_name=~\"$client_name\", event_type=\"http_status\", event_subtype=~\"20*\", service_type=\"http_client\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP 40x",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "targets": [
    {
     "expr": "increase(services_dashboard_services_counters_total{environment=~\"(?i)($environment)\", application=~\"$application\", client_name=~\"$client_name\", event_type=\"http_status\", event_subtype=~\"4.*\", service_type=\"http_client\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP 50x",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "expr": "increase(services_dashboard_services_counters_total{environment=~\"(?i)($environment)\", application=~\"$application\", client_name=~\"$client_name\", event_type=\"http_status\", event_subtype=~\"5.*\", service_type=\"http_client\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP status",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "increase(services_dashboard_services_counters_total{environment=~\"(?i)($environment)\", application=~\"$application\", client_name=~\"$client_name\", event_type=\"http_status\", service_type=\"http_client\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}