// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package rest

import (
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// NewMockMedia creates a new instance of MockMedia. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMedia(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMedia {
	mock := &MockMedia{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMedia is an autogenerated mock type for the Media type
type MockMedia struct {
	mock.Mock
}

type MockMedia_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMedia) EXPECT() *MockMedia_Expecter {
	return &MockMedia_Expecter{mock: &_m.Mock}
}

// DefaultHeaders provides a mock function for the type MockMedia
func (_mock *MockMedia) DefaultHeaders() http.Header {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DefaultHeaders")
	}

	var r0 http.Header
	if returnFunc, ok := ret.Get(0).(func() http.Header); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http.Header)
		}
	}
	return r0
}

// MockMedia_DefaultHeaders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DefaultHeaders'
type MockMedia_DefaultHeaders_Call struct {
	*mock.Call
}

// DefaultHeaders is a helper method to define mock.On call
func (_e *MockMedia_Expecter) DefaultHeaders() *MockMedia_DefaultHeaders_Call {
	return &MockMedia_DefaultHeaders_Call{Call: _e.mock.On("DefaultHeaders")}
}

func (_c *MockMedia_DefaultHeaders_Call) Run(run func()) *MockMedia_DefaultHeaders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMedia_DefaultHeaders_Call) Return(header http.Header) *MockMedia_DefaultHeaders_Call {
	_c.Call.Return(header)
	return _c
}

func (_c *MockMedia_DefaultHeaders_Call) RunAndReturn(run func() http.Header) *MockMedia_DefaultHeaders_Call {
	_c.Call.Return(run)
	return _c
}
